from __future__ import annotations

import json
import os
import re
import socket
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import Any
from urllib.parse import urlsplit

from main_computer.local_platform_registry import (
    LocalPlatformLane,
    LocalPlatformRegistry,
    LocalPlatformRegistryError,
    default_registry_data,
    load_local_platform_registry,
    normalize_registry_lane,
    parse_local_platform_registry,
)


COMPOSE_PROJECT_NAME = "main-computer-local-platform-unleashed"
ENV_COMPOSE_PROJECT = "MAIN_COMPUTER_LOCAL_PLATFORM_COMPOSE_PROJECT"
ENV_GENERATED_COMPOSE_PATH = "MAIN_COMPUTER_LOCAL_PLATFORM_GENERATED_COMPOSE_PATH"
GENERATED_COMPOSE_RELATIVE_PATH = PurePosixPath("deploy/local-platform/generated/docker-compose.websites.yml")
SITE_GENERATED_COMPOSE_RELATIVE_SUFFIX = PurePosixPath(".main-computer/local-platform/docker-compose.yml")
GENERATED_FILE_HEADER = """# This file is generated by tools/local-platform/generate-websites-compose.py.
# Do not edit by hand. Update runtime/local-platform/sites.json and regenerate.
"""
GENERATED_SITE_FILE_HEADER = """# This file is generated by Main Computer local-platform website tools.
# Do not edit by hand. Regenerate it from this runtime website and runtime/local-platform/sites.json.
"""
SITE_SERVER_BUILD_CONTEXT = "../site-server"
WEBSITES_VOLUME = "../../../runtime/websites:/app/runtime/websites:ro"
CONTAINER_CONTENT_ROOT = "/app/runtime/websites"
SERVICE_NAME_RE = re.compile(r"^[a-z0-9][a-z0-9_.-]*$")
SAFE_SLUG_RE = re.compile(r"[^a-z0-9-]+")
COMPOSE_VOLUME_RE = re.compile(r"^[a-zA-Z0-9][a-zA-Z0-9_.-]*$")
DIRECTUS_INTERNAL_PORT = 8055
DIRECTUS_HOST_PORT_START = 28200
DIRECTUS_HOST_PORT_END = 28999
ENV_DIRECTUS_HOST_PORT_START = "MAIN_COMPUTER_LOCAL_PLATFORM_DIRECTUS_PORT_START"
ENV_DIRECTUS_HOST_PORT_END = "MAIN_COMPUTER_LOCAL_PLATFORM_DIRECTUS_PORT_END"
LANE_RENDER_ORDER = ("prod", "dev")
BUILTIN_SITE_KIND_OVERRIDES = {
    "hub-site": "hub",
    "blog-site": "blog",
}


class LocalPlatformComposeError(ValueError):
    """Raised when the generated website Compose file cannot be rendered safely."""


@dataclass(frozen=True)
class GeneratedComposeService:
    site_id: str
    lane: str
    service: str
    port: int
    image: str
    site_name: str
    site_kind: str
    site_lane: str
    directus_service: str = ""
    directus_internal_url: str = ""
    directus_public_url: str = ""
    directus_managed: bool = False
    blog_enabled: bool = False
    blog_provider: str = ""
    blog_content_runtime: str = ""
    blog_collection: str = ""


@dataclass(frozen=True)
class GeneratedDirectusService:
    site_id: str
    service: str
    image: str
    internal_url: str
    public_url: str
    public_port: int
    database_volume: str
    uploads_volume: str
    admin_email_env: str
    admin_password_env: str
    secret_env: str
    managed: bool = True


def compose_project_name() -> str:
    return str(os.environ.get(ENV_COMPOSE_PROJECT) or COMPOSE_PROJECT_NAME).strip() or COMPOSE_PROJECT_NAME


def generated_compose_path(repo_root: Path) -> Path:
    override = str(os.environ.get(ENV_GENERATED_COMPOSE_PATH) or "").strip()
    if override:
        path = Path(override)
        if not path.is_absolute():
            path = repo_root / path
        return path.resolve()
    return repo_root / GENERATED_COMPOSE_RELATIVE_PATH


def _uses_default_generated_compose_path(repo_root: Path) -> bool:
    return generated_compose_path(repo_root).resolve() == (repo_root / GENERATED_COMPOSE_RELATIVE_PATH).resolve()


def _site_for_generated_compose(
    repo_root: Path,
    site_id: object,
    registry: LocalPlatformRegistry | None = None,
):
    registry = registry or load_local_platform_registry(repo_root)
    clean_site_id = str(site_id or "").strip().lower()
    if not clean_site_id:
        raise LocalPlatformComposeError("Missing website id for per-site Compose generation.")
    site = registry.sites.get(clean_site_id)
    if site is None:
        raise LocalPlatformComposeError(f"Website is not registered with the local platform: {clean_site_id}")
    return site


def site_generated_compose_relative_path(
    repo_root: Path,
    site_id: object,
    registry: LocalPlatformRegistry | None = None,
) -> PurePosixPath:
    site = _site_for_generated_compose(repo_root, site_id, registry)
    return PurePosixPath(site.repo_relative_path) / SITE_GENERATED_COMPOSE_RELATIVE_SUFFIX


def site_generated_compose_path(
    repo_root: Path,
    site_id: object,
    registry: LocalPlatformRegistry | None = None,
) -> Path:
    relative_path = site_generated_compose_relative_path(repo_root, site_id, registry)
    return repo_root.joinpath(*relative_path.parts)


def site_server_build_context(repo_root: Path, compose_path: Path | None = None) -> str:
    if compose_path is not None:
        return _compose_relative_host_path(compose_path, repo_root / "deploy" / "local-platform" / "site-server")
    if _uses_default_generated_compose_path(repo_root):
        return SITE_SERVER_BUILD_CONTEXT
    return _compose_host_path(repo_root / "deploy" / "local-platform" / "site-server")


def websites_volume_mount(repo_root: Path, compose_path: Path | None = None) -> str:
    if compose_path is not None:
        host_path = _compose_relative_host_path(compose_path, repo_root / "runtime" / "websites")
    elif _uses_default_generated_compose_path(repo_root):
        return WEBSITES_VOLUME
    else:
        host_path = _compose_host_path(repo_root / "runtime" / "websites")
    return f"{host_path}:/app/runtime/websites:ro"


def _compose_relative_host_path(compose_path: Path, target_path: Path) -> str:
    """Return a Compose host path relative to the given Compose file."""
    start = compose_path.resolve().parent
    target = target_path.resolve()
    return os.path.relpath(target, start).replace(os.sep, "/")


def _compose_host_path(path: Path) -> str:
    """Return a Docker Compose host path that is stable across Windows and POSIX."""
    return path.resolve().as_posix()


def safe_image_slug(value: object) -> str:
    slug = SAFE_SLUG_RE.sub("-", str(value or "").strip().lower()).strip("-")
    slug = re.sub(r"-{2,}", "-", slug)
    if not slug or not re.search(r"[a-z0-9]", slug):
        raise LocalPlatformComposeError(f"Cannot build a safe Compose image slug from: {value!r}")
    return slug


def validate_compose_service_name(value: object) -> str:
    service = str(value or "").strip()
    if not SERVICE_NAME_RE.fullmatch(service):
        raise LocalPlatformComposeError(f"Unsafe generated Compose service name: {service!r}")
    return service


def image_name_for_site_lane(site_id: object, lane: object) -> str:
    lane_name = normalize_registry_lane(lane)
    return f"main-computer-site-{safe_image_slug(site_id)}-{lane_name}:latest"


def compose_environment_lane(lane: object) -> str:
    lane_name = normalize_registry_lane(lane)
    return "local" if lane_name == "prod" else lane_name


def load_runtime_site_manifest(repo_root: Path, site) -> dict[str, Any]:
    manifest_path = repo_root / site.repo_relative_path / "site.json"
    try:
        payload = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (FileNotFoundError, json.JSONDecodeError, OSError):
        return {}
    return payload if isinstance(payload, dict) else {}


def load_runtime_site_metadata(repo_root: Path, site) -> dict[str, str]:
    metadata = {
        "name": site.name,
        "kind": BUILTIN_SITE_KIND_OVERRIDES.get(site.id, site.kind),
    }
    payload = load_runtime_site_manifest(repo_root, site)
    name = str(payload.get("name") or "").strip()
    if name:
        metadata["name"] = name
    kind = str(payload.get("kind") or "").strip()
    if kind:
        metadata["kind"] = BUILTIN_SITE_KIND_OVERRIDES.get(site.id, kind)
    return metadata


def _cms_contract(payload: dict[str, Any]) -> dict[str, Any]:
    backend = payload.get("backend")
    if not isinstance(backend, dict):
        return {}
    cms = backend.get("cms")
    return cms if isinstance(cms, dict) else {}


def _blog_feature_contract(payload: dict[str, Any]) -> dict[str, Any]:
    features = payload.get("features")
    if not isinstance(features, dict):
        return {}
    blog = features.get("blog")
    return blog if isinstance(blog, dict) else {}


def _blog_requires_directus(payload: dict[str, Any]) -> bool:
    return _blog_runtime_enabled(payload) or _blog_directus_service_prep_requested(payload)


def _blog_directus_service_prep_requested(payload: dict[str, Any]) -> bool:
    """Return True only for an explicit Blog CMS-prep request.

    Blog intent alone must not materialize Directus.  During the Directus
    service-prep phase, Blog is still disabled, so this checks the narrow
    blog_install markers/layer state instead of features.blog.enabled.
    """

    blog = _blog_feature_contract(payload)
    if not isinstance(blog, dict) or blog.get("selected") is not True or blog.get("enabled") is True:
        return False
    if str(blog.get("cms") or "").strip().lower() != "directus":
        return False

    install = payload.get("blog_install")
    if not isinstance(install, dict):
        return False

    runtime_preparation = install.get("runtime_preparation")
    if isinstance(runtime_preparation, dict):
        marker = runtime_preparation.get("directus_service")
        if marker is True:
            return True
        if isinstance(marker, dict):
            status = str(marker.get("status") or "").strip().lower()
            if marker.get("requested") is True or status in {"pending_deploy", "deploying", "configured", "ready"}:
                return True

    layers = install.get("layers")
    cms_layer = layers.get("cms") if isinstance(layers, dict) else None
    if isinstance(cms_layer, dict):
        return str(cms_layer.get("status") or "").strip().lower() in {"configured", "deploying", "ready"}

    return False


def _blog_runtime_enabled(payload: dict[str, Any]) -> bool:
    features = payload.get("features")
    blog = _blog_feature_contract(payload)
    if not blog:
        return features.get("blog") is True if isinstance(features, dict) else False
    if blog.get("enabled") is not True:
        return False
    cms = str(blog.get("cms") or "").strip().lower()
    content = blog.get("content")
    provider = str(content.get("provider") or "").strip().lower() if isinstance(content, dict) else ""
    return cms == "directus" or provider == "directus"


def _directus_required(payload: dict[str, Any]) -> bool:
    blog = _blog_feature_contract(payload)
    if blog:
        return _blog_requires_directus(payload)
    cms = _cms_contract(payload)
    cms_required = cms.get("required") is True and str(cms.get("provider") or "").strip().lower() == "directus"
    return cms_required


def _directus_collection(payload: dict[str, Any]) -> str:
    cms = _cms_contract(payload)
    schema = cms.get("schema")
    if isinstance(schema, dict):
        collection = str(schema.get("collection") or "").strip()
        if collection:
            return collection
    blog = _blog_feature_contract(payload)
    content = blog.get("content")
    if isinstance(content, dict):
        collection = str(content.get("collection") or "").strip()
        if collection:
            return collection
    runtime_config = payload.get("runtime_config")
    runtime_content = runtime_config.get("content") if isinstance(runtime_config, dict) else None
    if isinstance(runtime_content, dict):
        collection = str(runtime_content.get("collection") or "").strip()
        if collection:
            return collection
    return "posts"


def _directus_local_connection_from_cms(cms: dict[str, Any]) -> dict[str, Any]:
    connection = cms.get("local_connection")
    return connection if isinstance(connection, dict) else {}


def _directus_local_connection_service_name(cms: dict[str, Any]) -> str:
    connection = _directus_local_connection_from_cms(cms)
    return str(connection.get("service_name") or "").strip()


def _directus_local_connection_volume(cms: dict[str, Any], key: str) -> str:
    connection = _directus_local_connection_from_cms(cms)
    return str(connection.get(key) or "").strip()


def _directus_local_connection_public_port(cms: dict[str, Any]) -> int | None:
    connection = _directus_local_connection_from_cms(cms)
    raw_port = connection.get("public_port")
    if raw_port in (None, ""):
        return None
    try:
        port = int(raw_port)
    except (TypeError, ValueError) as exc:
        raise LocalPlatformComposeError(f"Directus local_connection.public_port must be an integer TCP port: {raw_port!r}") from exc
    if port < 1 or port > 65535:
        raise LocalPlatformComposeError(f"Directus local_connection.public_port is outside 1-65535: {raw_port!r}")
    return port


def _directus_default_service_name(site_id: object) -> str:
    return validate_compose_service_name(f"{safe_image_slug(site_id)}-directus")


def _directus_local_connection_mode(cms: dict[str, Any]) -> str:
    connection = _directus_local_connection_from_cms(cms)
    return str(connection.get("mode") or "").strip().lower().replace("-", "_")


def _directus_local_connection_managed(site_id: object, cms: dict[str, Any], service_name: str) -> bool:
    connection = _directus_local_connection_from_cms(cms)
    if connection.get("managed") is False or connection.get("external") is True:
        return False
    mode = _directus_local_connection_mode(cms)
    if mode == "use_existing" and service_name != _directus_default_service_name(site_id):
        return False
    return True


def _ensure_directus_contract_for_blog(site_id: str, payload: dict[str, Any]) -> dict[str, Any]:
    """Backfill the Directus CMS contract for older Blog manifests.

    Earlier Blog installs could record the Blog feature intent without a complete
    backend.cms.required Directus contract. Compose generation still needs that
    contract so the generated site receives BLOG_* and DIRECTUS_* env vars.
    """

    if not _blog_requires_directus(payload):
        return payload

    backend = payload.get("backend")
    if not isinstance(backend, dict):
        backend = {}
        payload["backend"] = backend
    cms = backend.get("cms")
    if not isinstance(cms, dict):
        cms = {}
        backend["cms"] = cms

    cms["provider"] = "directus"
    cms["required"] = True
    cms["runtime"] = "deployed"
    cms.setdefault("database_connection", "content")

    service = cms.get("service")
    if not isinstance(service, dict):
        service = {}
        cms["service"] = service
    service.setdefault("kind", "directus")
    service.setdefault("image", "directus/directus:11.5.1")
    service.setdefault("internal_url", f"http://{safe_image_slug(site_id)}-directus:8055")
    service.setdefault("public_url", "")
    service.setdefault("admin_secret_ref", "directus_admin_token")

    storage = cms.get("storage")
    if not isinstance(storage, dict):
        storage = {}
        cms["storage"] = storage
    storage.setdefault("database_volume", f"{site_id}_directus_database")
    storage.setdefault("uploads_volume", f"{site_id}_directus_uploads")

    schema = cms.get("schema")
    if not isinstance(schema, dict):
        schema = {}
        cms["schema"] = schema
    schema.setdefault("collection", _directus_collection(payload))
    schema.setdefault("status", "pending_deploy")

    permissions = cms.get("permissions")
    if not isinstance(permissions, dict):
        permissions = {}
        cms["permissions"] = permissions
    permissions.setdefault("public_read_published_posts", True)
    permissions.setdefault("public_read_files", True)
    permissions.setdefault("status", "pending_deploy")

    cms.setdefault("schema_status", "pending_deploy")
    cms.setdefault("permissions_status", "pending_deploy")
    cms.setdefault("uploads_status", "pending_deploy")
    return payload


def _directus_service_host(site_id: str, cms: dict[str, Any]) -> str:
    connection_service = _directus_local_connection_service_name(cms)
    if connection_service:
        return validate_compose_service_name(connection_service)

    service = cms.get("service")
    raw_url = ""
    if isinstance(service, dict):
        raw_url = str(service.get("internal_url") or "").strip()
    if raw_url:
        try:
            hostname = str(urlsplit(raw_url).hostname or "").strip()
        except ValueError:
            hostname = ""
        if hostname:
            return validate_compose_service_name(hostname)
    return _directus_default_service_name(site_id)


def _directus_image(cms: dict[str, Any]) -> str:
    service = cms.get("service")
    if isinstance(service, dict):
        image = str(service.get("image") or "").strip()
        if image:
            return image
    return "directus/directus:11.5.1"


def _directus_volume(value: object, fallback: str) -> str:
    name = str(value or fallback).strip()
    if not COMPOSE_VOLUME_RE.fullmatch(name):
        raise LocalPlatformComposeError(f"Unsafe generated Compose volume name: {name!r}")
    return name


def _site_env_prefix(site_id: str) -> str:
    return re.sub(r"[^A-Z0-9]+", "_", str(site_id or "").upper()).strip("_") or "SITE"


def _directus_port_range() -> tuple[int, int]:
    start = _env_port(ENV_DIRECTUS_HOST_PORT_START, DIRECTUS_HOST_PORT_START)
    end = _env_port(ENV_DIRECTUS_HOST_PORT_END, DIRECTUS_HOST_PORT_END)
    if start > end:
        raise LocalPlatformComposeError(
            f"{ENV_DIRECTUS_HOST_PORT_START} must be less than or equal to {ENV_DIRECTUS_HOST_PORT_END}."
        )
    return start, end


def _env_port(name: str, default: int) -> int:
    value = str(os.environ.get(name) or "").strip()
    if not value:
        return default
    try:
        port = int(value)
    except ValueError as exc:
        raise LocalPlatformComposeError(f"Environment variable {name} must be an integer TCP port.") from exc
    if port < 1 or port > 65535:
        raise LocalPlatformComposeError(f"Environment variable {name} must be a TCP port in 1-65535.")
    return port


def _host_port_can_bind(port: int) -> bool:
    try:
        clean_port = int(port)
    except (TypeError, ValueError):
        return False
    if clean_port < 1 or clean_port > 65535:
        return False
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 0)
        try:
            sock.bind(("127.0.0.1", clean_port))
        except OSError:
            return False
    return True


def _directus_public_port_from_cms(cms: dict[str, Any]) -> int | None:
    connection_port = _directus_local_connection_public_port(cms)
    if connection_port is not None:
        return connection_port

    service = cms.get("service")
    if not isinstance(service, dict):
        return None
    raw_url = str(service.get("public_url") or "").strip()
    if not raw_url:
        return None
    try:
        parsed = urlsplit(raw_url)
    except ValueError as exc:
        raise LocalPlatformComposeError(f"Directus public_url is not a valid URL: {raw_url!r}") from exc
    if parsed.scheme.lower() not in {"http", "https"} or not parsed.hostname or parsed.port is None:
        raise LocalPlatformComposeError(f"Directus public_url must include http(s), host, and port: {raw_url!r}")
    if parsed.port < 1 or parsed.port > 65535:
        raise LocalPlatformComposeError(f"Directus public_url port is outside 1-65535: {raw_url!r}")
    return int(parsed.port)


def _manifest_path_for_site(repo_root: Path, site) -> Path:
    return repo_root / site.repo_relative_path / "site.json"


def _write_runtime_site_manifest(repo_root: Path, site, payload: dict[str, Any]) -> None:
    path = _manifest_path_for_site(repo_root, site)
    path.parent.mkdir(parents=True, exist_ok=True)
    text = json.dumps(payload, indent=2, sort_keys=True) + "\n"
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", dir=path.parent, delete=False) as handle:
        handle.write(text)
        tmp_name = handle.name
    Path(tmp_name).replace(path)


def _persist_directus_urls(repo_root: Path, site, payload: dict[str, Any], *, internal_url: str, public_url: str) -> None:
    backend = payload.setdefault("backend", {})
    if not isinstance(backend, dict):
        backend = {}
        payload["backend"] = backend
    cms = backend.setdefault("cms", {})
    if not isinstance(cms, dict):
        cms = {}
        backend["cms"] = cms
    service = cms.setdefault("service", {})
    if not isinstance(service, dict):
        service = {}
        cms["service"] = service
    changed = False
    if service.get("internal_url") != internal_url:
        service["internal_url"] = internal_url
        changed = True
    if service.get("public_url") != public_url:
        service["public_url"] = public_url
        changed = True
    if changed:
        _write_runtime_site_manifest(repo_root, site, payload)


def _used_manifest_directus_ports(repo_root: Path, registry: LocalPlatformRegistry, *, exclude_site_id: str = "") -> set[int]:
    ports: set[int] = set()
    for other in registry.list_sites():
        if str(other.id) == str(exclude_site_id):
            continue
        manifest = load_runtime_site_manifest(repo_root, other)
        cms = _cms_contract(manifest)
        try:
            port = _directus_public_port_from_cms(cms)
        except LocalPlatformComposeError:
            continue
        if port is not None:
            ports.add(port)
    return ports


def _used_registry_ports(registry: LocalPlatformRegistry) -> set[int]:
    return {lane.port for site in registry.sites.values() for lane in site.lanes.values()}


def _docker_port_owners(port: int) -> list[str]:
    try:
        completed = subprocess.run(
            [
                "docker",
                "ps",
                "-a",
                "--filter",
                f"publish={int(port)}",
                "--format",
                "{{.Names}} {{.Image}} {{.Status}} {{.Ports}}",
            ],
            text=True,
            capture_output=True,
            timeout=4.0,
            check=False,
        )
    except Exception:
        return []
    if completed.returncode != 0:
        return []
    return [line.strip() for line in completed.stdout.splitlines() if line.strip()]


def _compose_service_from_container_name(container_name: str) -> str:
    project_prefix = f"{compose_project_name()}-"
    suffix = "-1"
    if not container_name.startswith(project_prefix) or not container_name.endswith(suffix):
        return ""
    service_name = container_name[len(project_prefix) : -len(suffix)]
    try:
        return validate_compose_service_name(service_name)
    except LocalPlatformComposeError:
        return ""


def _existing_directus_service_for_port(port: int) -> str:
    for owner in _docker_port_owners(port):
        if "directus/" not in owner.lower() and "directus:" not in owner.lower():
            continue
        name = owner.split(" ", 1)[0]
        service = _compose_service_from_container_name(name)
        if service:
            return service
    return ""


def _port_owner_conflict_message(port: int, service_name: str) -> str:
    owners = _docker_port_owners(port)
    expected_name_fragment = f"-{service_name}-"
    expected_suffix = f"-{service_name}-1"
    for owner in owners:
        name = owner.split(" ", 1)[0]
        if expected_name_fragment in name or name.endswith(expected_suffix):
            return ""
    if owners:
        return f"Directus public port {port} is already used by {owners[0]}."
    return f"Directus public port {port} is already used by another local process."


def _validate_persisted_directus_port(port: int, service_name: str) -> int:
    if _host_port_can_bind(port):
        return port
    conflict = _port_owner_conflict_message(port, service_name)
    if conflict:
        raise LocalPlatformComposeError(conflict)
    return port


def _allocate_directus_host_port(repo_root: Path, site, registry: LocalPlatformRegistry) -> int:
    reserved = _used_registry_ports(registry)
    reserved.update(_used_manifest_directus_ports(repo_root, registry, exclude_site_id=site.id))
    start, end = _directus_port_range()
    for port in range(start, end + 1):
        if port in reserved:
            continue
        if _host_port_can_bind(port):
            return port
    raise LocalPlatformComposeError(f"No Directus public port is available in {start}-{end}.")


def _directus_host_port(repo_root: Path, site, cms: dict[str, Any], service_name: str, registry: LocalPlatformRegistry) -> int:
    persisted = _directus_public_port_from_cms(cms)
    if persisted is not None:
        return _validate_persisted_directus_port(persisted, service_name)
    return _allocate_directus_host_port(repo_root, site, registry)


def directus_service_for_site(
    repo_root: Path,
    site,
    registry: LocalPlatformRegistry | None = None,
) -> GeneratedDirectusService | None:
    manifest = load_runtime_site_manifest(repo_root, site)
    manifest = _ensure_directus_contract_for_blog(str(site.id), manifest)
    if not _directus_required(manifest):
        return None
    registry = registry or load_local_platform_registry(repo_root)
    cms = _cms_contract(manifest)
    service_name = _directus_service_host(site.id, cms)
    connection = _directus_local_connection_from_cms(cms)
    persisted_public_port = _directus_public_port_from_cms(cms)
    if (
        _directus_local_connection_mode(cms) == "use_existing"
        and service_name == _directus_default_service_name(site.id)
        and persisted_public_port is not None
    ):
        owner_service = _existing_directus_service_for_port(persisted_public_port)
        if owner_service and owner_service != service_name:
            service_name = owner_service
            connection = {
                **connection,
                "service_name": owner_service,
                "internal_url": f"http://{owner_service}:{DIRECTUS_INTERNAL_PORT}",
                "managed": False,
                "external": True,
            }
    managed = _directus_local_connection_managed(site.id, cms, service_name)
    if connection.get("managed") is False or connection.get("external") is True:
        managed = False
    storage = cms.get("storage")
    storage = storage if isinstance(storage, dict) else {}
    database_volume = _directus_volume(
        _directus_local_connection_volume(cms, "database_volume") or storage.get("database_volume"),
        f"{site.id}_directus_database",
    )
    uploads_volume = _directus_volume(
        _directus_local_connection_volume(cms, "uploads_volume") or storage.get("uploads_volume"),
        f"{site.id}_directus_uploads",
    )
    public_port = _directus_host_port(repo_root, site, cms, service_name, registry) if managed else (
        _directus_public_port_from_cms(cms) or _directus_host_port(repo_root, site, cms, service_name, registry)
    )
    internal_url = str(connection.get("internal_url") or "").strip() or f"http://{service_name}:{DIRECTUS_INTERNAL_PORT}"
    public_url = str(connection.get("public_url") or "").strip() or f"http://127.0.0.1:{public_port}"
    _persist_directus_urls(repo_root, site, manifest, internal_url=internal_url, public_url=public_url)
    prefix = _site_env_prefix(site.id)
    return GeneratedDirectusService(
        site_id=site.id,
        service=service_name,
        image=_directus_image(cms),
        internal_url=internal_url,
        public_url=public_url,
        public_port=public_port,
        database_volume=database_volume,
        uploads_volume=uploads_volume,
        admin_email_env=f"${{{prefix}_DIRECTUS_ADMIN_EMAIL:-admin@example.com}}",
        admin_password_env=f"${{{prefix}_DIRECTUS_ADMIN_PASSWORD:-Admin-password-1!}}",
        secret_env=f"${{{prefix}_DIRECTUS_SECRET:-main-computer-local-{safe_image_slug(site.id)}-directus-secret}}",
        managed=managed,
    )


def generated_directus_services(
    repo_root: Path,
    registry: LocalPlatformRegistry | None = None,
    *,
    directus_site_ids: object = None,
    site_ids: object = None,
) -> list[GeneratedDirectusService]:
    registry = registry or load_local_platform_registry(repo_root)
    directus_scope = _normalize_site_id_scope(directus_site_ids)
    site_scope = _normalize_site_id_scope(site_ids)
    services: list[GeneratedDirectusService] = []
    seen_services: set[str] = set()
    seen_ports: set[int] = set()
    for site in registry.list_sites():
        if site_scope is not None and site.id not in site_scope:
            continue
        if directus_scope is not None and site.id not in directus_scope:
            continue
        directus = directus_service_for_site(repo_root, site, registry)
        if directus is None or not directus.managed:
            continue
        if directus.service in seen_services:
            raise LocalPlatformComposeError(f"Duplicate generated Directus service name: {directus.service}")
        if directus.public_port in seen_ports:
            raise LocalPlatformComposeError(f"Duplicate generated Directus public port: {directus.public_port}")
        seen_services.add(directus.service)
        seen_ports.add(directus.public_port)
        services.append(directus)
    return services


def directus_dependency_services_for_site(
    repo_root: Path,
    site_id: object,
    registry: LocalPlatformRegistry | None = None,
) -> list[GeneratedDirectusService]:
    clean_site_id = str(site_id or "").strip()
    if not clean_site_id:
        return []
    registry = registry or load_local_platform_registry(repo_root)
    site = registry.sites.get(clean_site_id)
    if site is None:
        return []
    directus = directus_service_for_site(repo_root, site, registry)
    return [directus] if directus is not None else []


def cms_dependency_service_names_for_site(repo_root: Path, site_id: object) -> list[str]:
    return [
        service.service
        for service in directus_dependency_services_for_site(repo_root, site_id)
        if service.service and service.managed
    ]


def _normalize_site_id_scope(site_ids: object) -> set[str] | None:
    if site_ids is None:
        return None
    if isinstance(site_ids, str):
        value = site_ids.strip()
        return {value} if value else set()
    try:
        return {str(value).strip() for value in site_ids if str(value).strip()}
    except TypeError:
        value = str(site_ids).strip()
        return {value} if value else set()


def generated_compose_services(
    repo_root: Path,
    registry: LocalPlatformRegistry | None = None,
    *,
    directus_site_ids: object = None,
    site_ids: object = None,
) -> list[GeneratedComposeService]:
    registry = registry or load_local_platform_registry(repo_root)
    directus_scope = _normalize_site_id_scope(directus_site_ids)
    site_scope = _normalize_site_id_scope(site_ids)
    services: list[GeneratedComposeService] = []
    seen_services: set[str] = set()
    for site in registry.list_sites():
        if site_scope is not None and site.id not in site_scope:
            continue
        metadata = load_runtime_site_metadata(repo_root, site)
        manifest = load_runtime_site_manifest(repo_root, site)
        directus = (
            directus_service_for_site(repo_root, site, registry)
            if directus_scope is None or site.id in directus_scope
            else None
        )
        ordered_lanes = [lane for lane in LANE_RENDER_ORDER if lane in site.lanes]
        ordered_lanes.extend(sorted(lane for lane in site.lanes if lane not in set(ordered_lanes)))
        for lane_name in ordered_lanes:
            lane = site.lanes[lane_name]
            service_name = validate_compose_service_name(lane.service)
            if service_name in seen_services:
                raise LocalPlatformComposeError(f"Duplicate generated Compose service name: {service_name}")
            seen_services.add(service_name)
            services.append(
                GeneratedComposeService(
                    site_id=site.id,
                    lane=lane_name,
                    service=service_name,
                    port=lane.port,
                    image=image_name_for_site_lane(site.id, lane_name),
                    site_name=metadata["name"],
                    site_kind=metadata["kind"],
                    site_lane=compose_environment_lane(lane_name),
                    directus_service=directus.service if directus else "",
                    directus_internal_url=directus.internal_url if directus else "",
                    directus_public_url=directus.public_url if directus else "",
                    directus_managed=bool(directus and directus.managed),
                    blog_enabled=bool(directus and _blog_runtime_enabled(manifest)),
                    blog_provider="directus" if directus and _blog_runtime_enabled(manifest) else "",
                    blog_content_runtime="directus" if directus and _blog_runtime_enabled(manifest) else "",
                    blog_collection=_directus_collection(manifest) if directus and _blog_runtime_enabled(manifest) else "",
                )
            )
    return services


def render_generated_websites_compose(
    repo_root: Path,
    registry: LocalPlatformRegistry | None = None,
    *,
    directus_site_ids: object = None,
    site_ids: object = None,
    compose_path: Path | None = None,
    file_header: str = GENERATED_FILE_HEADER,
) -> str:
    registry = registry or load_local_platform_registry(repo_root)
    services = generated_compose_services(
        repo_root,
        registry,
        directus_site_ids=directus_site_ids,
        site_ids=site_ids,
    )
    directus_services = generated_directus_services(
        repo_root,
        registry,
        directus_site_ids=directus_site_ids,
        site_ids=site_ids,
    )
    lines: list[str] = [
        file_header.rstrip(),
        f'name: "{compose_project_name()}"',
        "",
        "services:",
    ]
    if not services and not directus_services:
        lines.append("  {}")
        return "\n".join(lines) + "\n"
    for directus in directus_services:
        lines.extend(_render_directus_service(directus))
    for service in services:
        lines.extend(_render_service(service, repo_root, compose_path=compose_path))
    if directus_services:
        lines.extend(_render_directus_volumes(directus_services))
    return "\n".join(lines).rstrip() + "\n"


def render_generated_site_compose(
    repo_root: Path,
    site_id: object,
    registry: LocalPlatformRegistry | None = None,
) -> str:
    registry = registry or load_local_platform_registry(repo_root)
    site = _site_for_generated_compose(repo_root, site_id, registry)
    return render_generated_websites_compose(
        repo_root,
        registry,
        site_ids={site.id},
        compose_path=site_generated_compose_path(repo_root, site.id, registry),
        file_header=GENERATED_SITE_FILE_HEADER,
    )


def _write_generated_compose_file(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", dir=path.parent, delete=False) as handle:
        handle.write(text)
        tmp_name = handle.name
    Path(tmp_name).replace(path)


def write_generated_websites_compose(
    repo_root: Path,
    registry: LocalPlatformRegistry | None = None,
    *,
    directus_site_ids: object = None,
) -> dict[str, Any]:
    text = render_generated_websites_compose(repo_root, registry, directus_site_ids=directus_site_ids)
    path = generated_compose_path(repo_root)
    _write_generated_compose_file(path, text)
    registry = registry or load_local_platform_registry(repo_root)
    services = generated_compose_services(repo_root, registry, directus_site_ids=directus_site_ids)
    directus_services = generated_directus_services(repo_root, registry, directus_site_ids=directus_site_ids)
    return {
        "ok": True,
        "path": str(path),
        "repo_relative_path": GENERATED_COMPOSE_RELATIVE_PATH.as_posix(),
        "service_count": len(services) + len(directus_services),
        "services": [service.service for service in directus_services] + [service.service for service in services],
        "cms_services": [service.service for service in directus_services],
    }


def write_generated_site_compose(
    repo_root: Path,
    site_id: object,
    registry: LocalPlatformRegistry | None = None,
) -> dict[str, Any]:
    registry = registry or load_local_platform_registry(repo_root)
    site = _site_for_generated_compose(repo_root, site_id, registry)
    path = site_generated_compose_path(repo_root, site.id, registry)
    text = render_generated_site_compose(repo_root, site.id, registry)
    _write_generated_compose_file(path, text)
    services = generated_compose_services(repo_root, registry, site_ids={site.id})
    directus_services = generated_directus_services(repo_root, registry, site_ids={site.id})
    return {
        "ok": True,
        "path": str(path),
        "repo_relative_path": site_generated_compose_relative_path(repo_root, site.id, registry).as_posix(),
        "site_id": site.id,
        "service_count": len(services) + len(directus_services),
        "services": [service.service for service in directus_services] + [service.service for service in services],
        "cms_services": [service.service for service in directus_services],
    }


def default_generated_websites_compose(repo_root: Path) -> str:
    registry = parse_local_platform_registry(repo_root, default_registry_data())
    return render_generated_websites_compose(repo_root, registry)


def _render_service(
    service: GeneratedComposeService,
    repo_root: Path,
    *,
    compose_path: Path | None = None,
) -> list[str]:
    lines = [
        f"  {service.service}:",
        "    build:",
        f"      context: {_yaml_string(site_server_build_context(repo_root, compose_path=compose_path))}",
        f"    image: {_yaml_string(service.image)}",
        "    restart: unless-stopped",
    ]
    if service.directus_service and service.directus_managed:
        lines.extend(
            [
                "    depends_on:",
                f"      - {_yaml_string(service.directus_service)}",
            ]
        )
    lines.extend(
        [
            "    environment:",
            f"      SITE_ID: {_yaml_string(service.site_id)}",
            f"      SITE_NAME: {_yaml_string(service.site_name)}",
            f"      SITE_KIND: {_yaml_string(service.site_kind)}",
            f"      SITE_LANE: {_yaml_string(service.site_lane)}",
            f"      MC_SITE_ID: {_yaml_string(service.site_id)}",
            f"      MC_RUNTIME_LANE: {_yaml_string(service.site_lane)}",
            f"      CONTENT_ROOT: {_yaml_string(CONTAINER_CONTENT_ROOT)}",
        ]
    )
    if service.directus_service:
        lines.extend(
            [
                f"      MC_DIRECTUS_SERVICE: {_yaml_string(service.directus_service)}",
                f"      DIRECTUS_URL: {_yaml_string(service.directus_internal_url)}",
                f"      DIRECTUS_PUBLIC_URL: {_yaml_string(service.directus_public_url)}",
            ]
        )
    if service.blog_enabled:
        lines.extend(
            [
                '      BLOG_ENABLED: "true"',
                f"      BLOG_PROVIDER: {_yaml_string(service.blog_provider or 'directus')}",
                f"      BLOG_CONTENT_RUNTIME: {_yaml_string(service.blog_content_runtime or 'directus')}",
                f"      BLOG_COLLECTION: {_yaml_string(service.blog_collection or 'posts')}",
            ]
        )
    lines.extend(
        [
            "    volumes:",
            f"      - {_yaml_string(websites_volume_mount(repo_root, compose_path=compose_path))}",
            "    ports:",
            f"      - {_yaml_string(f'0.0.0.0:{service.port}:8080')}",
            "",
        ]
    )
    return lines


def _render_directus_service(service: GeneratedDirectusService) -> list[str]:
    return [
        f"  {service.service}:",
        f"    image: {_yaml_string(service.image)}",
        "    restart: unless-stopped",
        "    environment:",
        f"      SECRET: {_yaml_string(service.secret_env)}",
        f"      ADMIN_EMAIL: {_yaml_string(service.admin_email_env)}",
        f"      ADMIN_PASSWORD: {_yaml_string(service.admin_password_env)}",
        '      DB_CLIENT: "sqlite3"',
        '      DB_FILENAME: "/directus/database/data.db"',
        '      STORAGE_LOCATIONS: "local"',
        '      STORAGE_LOCAL_ROOT: "/directus/uploads"',
        f"      PUBLIC_URL: {_yaml_string(service.public_url)}",
        "    volumes:",
        f"      - {_yaml_string(f'{service.database_volume}:/directus/database')}",
        f"      - {_yaml_string(f'{service.uploads_volume}:/directus/uploads')}",
        "    ports:",
        f"      - {_yaml_string(f'127.0.0.1:{service.public_port}:{DIRECTUS_INTERNAL_PORT}')}",
        "",
    ]


def _render_directus_volumes(services: list[GeneratedDirectusService]) -> list[str]:
    lines = ["volumes:"]
    seen: set[str] = set()
    for volume_name in [service.database_volume for service in services] + [service.uploads_volume for service in services]:
        if volume_name in seen:
            continue
        seen.add(volume_name)
        lines.extend(
            [
                f"  {volume_name}:",
                f"    name: {_yaml_string(volume_name)}",
            ]
        )
    return lines


def _yaml_string(value: object) -> str:
    return json.dumps(str(value), ensure_ascii=False)


def main(argv: list[str] | None = None) -> int:
    import argparse

    parser = argparse.ArgumentParser(description="Generate Docker Compose services for managed local websites.")
    parser.add_argument("--repo-root", default=".")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the generated file is missing or stale, without writing it.",
    )
    args = parser.parse_args(argv)

    repo_root = Path(args.repo_root).resolve()
    rendered = render_generated_websites_compose(repo_root)
    path = generated_compose_path(repo_root)
    if args.check:
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        if current != rendered:
            print(
                json.dumps(
                    {
                        "ok": False,
                        "stale": True,
                        "path": str(path),
                        "repo_relative_path": GENERATED_COMPOSE_RELATIVE_PATH.as_posix(),
                    },
                    indent=2,
                    sort_keys=True,
                )
            )
            return 1
        print(
            json.dumps(
                {
                    "ok": True,
                    "stale": False,
                    "path": str(path),
                    "repo_relative_path": GENERATED_COMPOSE_RELATIVE_PATH.as_posix(),
                },
                indent=2,
                sort_keys=True,
            )
        )
        return 0
    result = write_generated_websites_compose(repo_root)
    print(json.dumps(result, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
