from __future__ import annotations

import json
import os
import re
import tempfile
import threading
import unittest
from contextlib import redirect_stdout
from io import StringIO
from pathlib import Path
from urllib.error import HTTPError
from urllib.request import Request, urlopen
from unittest.mock import patch

from main_computer.cli import _config_from_args
from main_computer.config import DEFAULT_ENERGY_CHAIN_ID, DEFAULT_ENERGY_CHAIN_RPC_URL, MainComputerConfig
from main_computer.energy import EnergyCreditLedger
from main_computer.governance import bridge_governance_status
from main_computer.models import ChatMessage, ChatResponse
from main_computer.revision import DebugAssetRevisionControl, RevisionControl
from main_computer.viewport import APPLICATIONS_INDEX_HTML, DEBUG_GRAPHICAL_INDEX_HTML, DEBUG_TEXT_INDEX_HTML, ENERGY_INDEX_HTML, GRAPHICAL_INDEX_HTML, REVISION_INDEX_HTML, TEXT_INDEX_HTML, ViewportHandler, ViewportServer, _application_route_target, serve


class ViewportApplicationsStaticChatTests(unittest.TestCase):
    def test_applications_index_contains_chat_console_hooks(self) -> None:
            self.assertIn("Terminal Analysis", APPLICATIONS_INDEX_HTML)
            self.assertIn("analyzeTerminalFailure", APPLICATIONS_INDEX_HTML)
            self.assertIn("renderAnalysisMarkdown", APPLICATIONS_INDEX_HTML)
            self.assertIn("renderInlineMarkdown", APPLICATIONS_INDEX_HTML)
            self.assertIn("terminalAnalysisRawMode", APPLICATIONS_INDEX_HTML)
            self.assertIn("terminalAnalysis.innerHTML = renderAnalysisMarkdown", APPLICATIONS_INDEX_HTML)
            self.assertIn("terminalAnalysis.textContent = text", APPLICATIONS_INDEX_HTML)
            self.assertIn("<pre><code>", APPLICATIONS_INDEX_HTML)
            self.assertIn("Analyze this failed Main Computer terminal command", APPLICATIONS_INDEX_HTML)
            self.assertIn('data-app="terminal"', APPLICATIONS_INDEX_HTML)
            self.assertIn('data-app="chat-console"', APPLICATIONS_INDEX_HTML)
            self.assertIn('id="chat-console-app"', APPLICATIONS_INDEX_HTML)
            self.assertIn("Chat Console", APPLICATIONS_INDEX_HTML)
            self.assertIn("AI/code/Terminal/Mathics notebook cells", APPLICATIONS_INDEX_HTML)
            self.assertIn('id="chat-console-notebook"', APPLICATIONS_INDEX_HTML)
            chat_console_html = (Path(__file__).resolve().parents[1] / "main_computer" / "web" / "applications" / "apps" / "chat-console.html").read_text(encoding="utf-8")
            self.assertNotIn('class="chat-console-toolbar chat-console-footer mc-toolbar"', chat_console_html)
            self.assertNotIn("New AI cell", chat_console_html)
            self.assertNotIn("New JS cell", chat_console_html)
            self.assertNotIn("New Python cell", chat_console_html)
            self.assertNotIn("New BASIC cell", chat_console_html)
            self.assertNotIn("New Calc cell", chat_console_html)
            self.assertNotIn("New Terminal cell", chat_console_html)
            self.assertNotIn("New Mathics cell", chat_console_html)
            self.assertNotIn("New Note cell", chat_console_html)
            self.assertNotIn("Clear notebook", chat_console_html)
            self.assertNotIn("chat-console-open-vars-spreadsheet", chat_console_html)
            self.assertNotIn("chat-console-clear", chat_console_html)
            chat_css_start = APPLICATIONS_INDEX_HTML.index(".chat-console-app")
            chat_css_end = APPLICATIONS_INDEX_HTML.index(".calculator-app")
            chat_css = APPLICATIONS_INDEX_HTML[chat_css_start:chat_css_end]
            self.assertIn("grid-template-rows: auto minmax(0, 1fr);", chat_css)
            self.assertIn("align-items: start;", chat_css)
            self.assertIn("overflow: visible;", chat_css)
            self.assertIn("resize: none;", chat_css)
            self.assertIn("overflow: hidden;", chat_css)
            self.assertNotIn("max-height: min(68vh, 760px);", chat_css)
            self.assertNotIn("grid-template-rows: auto minmax(0, 1fr) auto;", chat_css)
            self.assertIn("main-computer-chat-console-v1", APPLICATIONS_INDEX_HTML)
            self.assertIn("/api/applications/chat-console/cell/evaluate", APPLICATIONS_INDEX_HTML)
            self.assertIn("/api/applications/chat-console/attachments", APPLICATIONS_INDEX_HTML)
            self.assertIn('label: "AI"', APPLICATIONS_INDEX_HTML)
            self.assertIn('label: "JS"', APPLICATIONS_INDEX_HTML)
            self.assertIn('label: "Python"', APPLICATIONS_INDEX_HTML)
            self.assertIn('label: "BASIC"', APPLICATIONS_INDEX_HTML)
            self.assertIn('label: "Calc"', APPLICATIONS_INDEX_HTML)
            self.assertIn('label: "Term"', APPLICATIONS_INDEX_HTML)
            self.assertIn('label: "Math"', APPLICATIONS_INDEX_HTML)
            self.assertIn('label: "Note"', APPLICATIONS_INDEX_HTML)
            self.assertIn('label: "Out"', APPLICATIONS_INDEX_HTML)
            self.assertNotIn('label: "Plot"', APPLICATIONS_INDEX_HTML)
            self.assertIn('const chatConsoleInputCellTypes = chatConsoleCellTypes.filter((item) => item.type !== "output")', APPLICATIONS_INDEX_HTML)
            self.assertIn('const chatConsoleOutputCellTypes = chatConsoleCellTypes.filter((item) => item.type === "output")', APPLICATIONS_INDEX_HTML)
            self.assertIn('const tabItems = cell.type === "output" ? chatConsoleOutputCellTypes : chatConsoleInputCellTypes', APPLICATIONS_INDEX_HTML)
            self.assertIn('button.disabled = cell.type === "output"', APPLICATIONS_INDEX_HTML)
            self.assertIn("function renderChatConsoleInsertStrip", APPLICATIONS_INDEX_HTML)
            self.assertIn('thinking.dataset.chatCellTab = "thinking"', APPLICATIONS_INDEX_HTML)
            self.assertIn("function renderChatConsoleThinkingPanel", APPLICATIONS_INDEX_HTML)
            self.assertIn("chatConsoleShouldShowThinking(cell)", APPLICATIONS_INDEX_HTML)
            self.assertIn("chat-thinking-frame", APPLICATIONS_INDEX_HTML)
            self.assertIn("chat-thinking-grid", APPLICATIONS_INDEX_HTML)
            self.assertIn("Models in use on this computer", APPLICATIONS_INDEX_HTML)
            self.assertIn("/api/activity/ollama-ps", APPLICATIONS_INDEX_HTML)
            self.assertIn("chatConsoleThinkingEventCategory", APPLICATIONS_INDEX_HTML)
            self.assertIn("function chatConsoleThinkingEventDedupeKey", APPLICATIONS_INDEX_HTML)
            self.assertIn("model-content-stream", APPLICATIONS_INDEX_HTML)
            self.assertIn("function chatConsoleIsRecoverableFetchError", APPLICATIONS_INDEX_HTML)
            self.assertIn("pollChatConsoleAiRunResult", APPLICATIONS_INDEX_HTML)
            self.assertIn("/api/applications/chat-console/ai/run-result", APPLICATIONS_INDEX_HTML)
            self.assertIn("cell evaluation recovered after fetch loss", APPLICATIONS_INDEX_HTML)
            self.assertIn("newestUnique.slice(0, 16)", APPLICATIONS_INDEX_HTML)
            self.assertLess(
                APPLICATIONS_INDEX_HTML.index('data.latest_text ? `model stream: ${data.latest_text}` : ""'),
                APPLICATIONS_INDEX_HTML.index("data.running_text"),
            )
            self.assertIn("data-category=\"ollama\"", APPLICATIONS_INDEX_HTML)
            self.assertNotIn('window.MainComputerActivityDock?.open?.("ai")', APPLICATIONS_INDEX_HTML)
            self.assertIn('target.append(renderChatConsoleInsertStrip(""))', APPLICATIONS_INDEX_HTML)
            self.assertIn('chatConsoleButton("+ Insert", () => addChatConsoleCell("ai", "", afterId))', APPLICATIONS_INDEX_HTML)
            self.assertIn('button.dataset.chatConsoleInsert = "ai"', APPLICATIONS_INDEX_HTML)
            self.assertIn('const chatConsoleCodeCellTypes = new Set(["javascript", "python", "basic"])', APPLICATIONS_INDEX_HTML)
            self.assertIn("chat-console-js-worker-source", APPLICATIONS_INDEX_HTML)
            self.assertIn("chat-console-python-worker-source", APPLICATIONS_INDEX_HTML)
            self.assertIn("chat-console-basic-worker-source", APPLICATIONS_INDEX_HTML)
            self.assertIn("Chat Console JavaScript code-cell worker", APPLICATIONS_INDEX_HTML)
            self.assertIn("Chat Console Python code-cell worker", APPLICATIONS_INDEX_HTML)
            self.assertIn("Chat Console BASIC code-cell worker", APPLICATIONS_INDEX_HTML)
            self.assertIn("_mc_install_shared_globals", APPLICATIONS_INDEX_HTML)
            self.assertIn("globals()[_mc_name] = _mc_value", APPLICATIONS_INDEX_HTML)
            self.assertIn("globals()[_mc_name] = value", APPLICATIONS_INDEX_HTML)
            self.assertIn("chatBasicLookupVariable", APPLICATIONS_INDEX_HTML)
            self.assertIn("chatConsoleVariableSnapshot", APPLICATIONS_INDEX_HTML)
            self.assertIn("evaluateChatConsoleCalculatorCell", APPLICATIONS_INDEX_HTML)
            self.assertIn("evaluateChatConsoleCodeCell", APPLICATIONS_INDEX_HTML)
            self.assertIn("runChatConsoleCodeWorker", APPLICATIONS_INDEX_HTML)
            self.assertIn("Shared variables", APPLICATIONS_INDEX_HTML)
            self.assertNotIn("Open vars in spreadsheet", chat_console_html)
            self.assertNotIn("chat-console-open-vars-spreadsheet", chat_console_html)
            self.assertIn("/api/applications/chat-console/shared-variables/export", APPLICATIONS_INDEX_HTML)
            self.assertIn("exportChatConsoleVariablesToSpreadsheet", APPLICATIONS_INDEX_HTML)
            self.assertIn("chat_vars", APPLICATIONS_INDEX_HTML)
            self.assertIn("/api/applications/spreadsheet/import-chat-variables", APPLICATIONS_INDEX_HTML)
            self.assertIn("spreadsheetMaybeImportChatVariablesFromUrl", APPLICATIONS_INDEX_HTML)
            self.assertIn("chat-console-cell-input", APPLICATIONS_INDEX_HTML)
            self.assertIn("chat-console-cell-output chat-console-output-indent", APPLICATIONS_INDEX_HTML)
            self.assertIn(".chat-console-cell-output.chat-console-output-indent", APPLICATIONS_INDEX_HTML)
            self.assertIn(".chat-console-insert-strip", APPLICATIONS_INDEX_HTML)
            self.assertIn("promoteChatConsoleSnippet", APPLICATIONS_INDEX_HTML)
            self.assertIn("isChatConsoleActiveOutput", APPLICATIONS_INDEX_HTML)
            self.assertIn("thread_parent_output_cell_id", APPLICATIONS_INDEX_HTML)
            self.assertIn("function getChatConsoleRootCells", APPLICATIONS_INDEX_HTML)
            self.assertIn("function getChatConsoleChildrenForOutput", APPLICATIONS_INDEX_HTML)
            self.assertIn("function getChatConsoleSelectedOutputForSource", APPLICATIONS_INDEX_HTML)
            self.assertIn("function renderChatConsoleVisibleThread", APPLICATIONS_INDEX_HTML)
            self.assertIn("function renderChatConsoleCellAndSelectedContinuation", APPLICATIONS_INDEX_HTML)
            self.assertIn("function collectChatConsoleCellAndSelectedContinuation", APPLICATIONS_INDEX_HTML)
            self.assertIn('if (cell.type === "output" && nextCell && nextCell.type !== "output")', APPLICATIONS_INDEX_HTML)
            self.assertIn('if (visibleCell.type === "output" && nextCell && nextCell.type !== "output")', APPLICATIONS_INDEX_HTML)
            self.assertIn("function getChatConsoleThreadContext", APPLICATIONS_INDEX_HTML)
            self.assertIn("function setChatConsoleSelectedCell", APPLICATIONS_INDEX_HTML)
            self.assertIn("const resizeTextarea = () =>", APPLICATIONS_INDEX_HTML)
            self.assertIn("textarea.style.height = `${textarea.scrollHeight}px`", APPLICATIONS_INDEX_HTML)
            self.assertIn("requestAnimationFrame(resizeTextarea)", APPLICATIONS_INDEX_HTML)
            self.assertIn("cell.promoted_from?.promoted_from_output_cell_id || null", APPLICATIONS_INDEX_HTML)
            self.assertIn("chatConsoleState.cells.push(outputCell)", APPLICATIONS_INDEX_HTML)
            self.assertIn("function ensureChatConsoleContinuationAfterOutput", APPLICATIONS_INDEX_HTML)
            self.assertIn("ensureChatConsoleContinuationAfterOutput(outputCell, cell)", APPLICATIONS_INDEX_HTML)
            self.assertIn("ensureChatConsoleContinuationAfterOutput(recoveredOutput, cell)", APPLICATIONS_INDEX_HTML)
            self.assertNotIn("+ 1 + variantIndex", APPLICATIONS_INDEX_HTML)
            self.assertIn('nav.className = "chat-output-navigation chat-output-variant-row"', APPLICATIONS_INDEX_HTML)
            self.assertIn('wrap.className = "chat-output-cell-block"', APPLICATIONS_INDEX_HTML)
            self.assertIn('chrome.className = "chat-output-cell-chrome"', APPLICATIONS_INDEX_HTML)
            self.assertIn('body.className = "chat-output-cell-body"', APPLICATIONS_INDEX_HTML)
            self.assertIn('chatConsoleButton("Copy", () => copyChatConsoleOutputCell(cell.id))', APPLICATIONS_INDEX_HTML)
            self.assertIn("function serializeOutputCellToPlainText", APPLICATIONS_INDEX_HTML)
            self.assertIn("function serializeOutputCellToHtml", APPLICATIONS_INDEX_HTML)
            self.assertIn("function serializeOutputCellToJson", APPLICATIONS_INDEX_HTML)
            self.assertIn("async function copyChatConsoleOutputCell", APPLICATIONS_INDEX_HTML)
            self.assertIn("application/x-main-computer-output-cell+json", APPLICATIONS_INDEX_HTML)
            self.assertIn("navigator.clipboard.write", APPLICATIONS_INDEX_HTML)
            self.assertIn("renderChatConsoleOutputTable", APPLICATIONS_INDEX_HTML)
            self.assertIn("metadata?.data_url", APPLICATIONS_INDEX_HTML)
            self.assertIn('part.kind === "image" || part.kind === "plot"', APPLICATIONS_INDEX_HTML)
            self.assertIn('content.className = part.kind === "plot" ? "chat-output-plot" : "chat-output-image"', APPLICATIONS_INDEX_HTML)
            self.assertIn('(cell.parts || []).forEach((part) => body.append(renderChatConsoleOutputPart(cell, part)))', APPLICATIONS_INDEX_HTML)
            self.assertIn('previous.setAttribute("aria-label", "Previous result")', APPLICATIONS_INDEX_HTML)
            self.assertIn('next.setAttribute("aria-label", "Next result")', APPLICATIONS_INDEX_HTML)
            self.assertIn('counter.textContent = `${index + 1}/${variants.length}`', APPLICATIONS_INDEX_HTML)
            self.assertIn("source.selected_output_variant_index = targetIndex", APPLICATIONS_INDEX_HTML)
            self.assertIn("renderChatConsoleMarkdown", APPLICATIONS_INDEX_HTML)
            self.assertIn('status: type === "terminal" ? "review-required" : "idle"', APPLICATIONS_INDEX_HTML)
            promotion_start = APPLICATIONS_INDEX_HTML.index("function promoteChatConsoleSnippet")
            promotion_end = APPLICATIONS_INDEX_HTML.index("async function systemFileExplorerApi")
            promotion_slice = APPLICATIONS_INDEX_HTML[promotion_start:promotion_end]
            self.assertNotIn("/api/applications/terminal/run", promotion_slice)
            self.assertIn("thread_parent_output_cell_id: outputCell.id", promotion_slice)
            output_start = APPLICATIONS_INDEX_HTML.index("function renderChatConsoleOutputCell")
            output_end = APPLICATIONS_INDEX_HTML.index("function renderChatConsoleSnippet")
            output_slice = APPLICATIONS_INDEX_HTML[output_start:output_end]
            self.assertNotIn('"Prev"', output_slice)
            self.assertNotIn('"Next"', output_slice)
            self.assertIn('"Delete output"', output_slice)
            self.assertIn("@xterm/xterm", APPLICATIONS_INDEX_HTML)
            self.assertIn("@xterm/addon-fit", APPLICATIONS_INDEX_HTML)
            self.assertIn("initXtermTerminal", APPLICATIONS_INDEX_HTML)
            self.assertIn("handleXtermData", APPLICATIONS_INDEX_HTML)
            self.assertIn("FitAddonCtor", APPLICATIONS_INDEX_HTML)
            self.assertIn("TerminalCtor", APPLICATIONS_INDEX_HTML)
            self.assertIn("Up/Down recalls history", APPLICATIONS_INDEX_HTML)
            self.assertIn("main-computer-terminal-history-v1", APPLICATIONS_INDEX_HTML)
            self.assertIn("terminalBuffer = \"\";", APPLICATIONS_INDEX_HTML)
            self.assertIn("terminalHistoryCursor = -1", APPLICATIONS_INDEX_HTML)
            self.assertIn("terminalHistoryCursor + 1", APPLICATIONS_INDEX_HTML)
            self.assertIn("terminalHistoryCursor - 1", APPLICATIONS_INDEX_HTML)
            self.assertNotIn('id="terminal-command"', APPLICATIONS_INDEX_HTML)
            self.assertNotIn('id="terminal-output"', APPLICATIONS_INDEX_HTML)
            self.assertNotIn('id="terminal-history"', APPLICATIONS_INDEX_HTML)
            self.assertNotIn('id="terminal-clear"', APPLICATIONS_INDEX_HTML)
            self.assertIn("runTerminalCommand", APPLICATIONS_INDEX_HTML)
            self.assertIn("/api/applications/terminal/run", APPLICATIONS_INDEX_HTML)
            self.assertIn("calculateExpression", APPLICATIONS_INDEX_HTML)
            self.assertIn("askCalculatorModel", APPLICATIONS_INDEX_HTML)
            self.assertIn("askCalculatorQa", APPLICATIONS_INDEX_HTML)
            self.assertIn("calculatorQaContext", APPLICATIONS_INDEX_HTML)
            self.assertNotIn('id="calculator-mode-chat"', APPLICATIONS_INDEX_HTML)
            self.assertIn('id="calculator-chat-notebook"', APPLICATIONS_INDEX_HTML)
            applications_html = Path(__file__).resolve().parents[1] / "main_computer" / "web" / "applications.html"
            self.assertIn('<!-- @include applications/scripts/chat-console-state.js -->', applications_html.read_text(encoding="utf-8"))
            calculator_js = (applications_html.parent / "applications" / "scripts" / "calculator.js").read_text(encoding="utf-8")
            self.assertNotIn("const chatConsoleStorageKey", calculator_js)
            self.assertIn("askScientificCalculatorModel", APPLICATIONS_INDEX_HTML)
            self.assertIn("extractCalculatorExpression", APPLICATIONS_INDEX_HTML)
            self.assertIn("extractCalculatorGraphExpression", APPLICATIONS_INDEX_HTML)
            self.assertIn("setCalculatorMode", APPLICATIONS_INDEX_HTML)
            self.assertIn("graphing-active", APPLICATIONS_INDEX_HTML)
            self.assertIn("calculatorMathicsPanel.hidden = !graphing", APPLICATIONS_INDEX_HTML)
            self.assertIn("askCalculatorMathicsModel", APPLICATIONS_INDEX_HTML)
            self.assertIn("evaluateCalculatorMathics", APPLICATIONS_INDEX_HTML)
            self.assertIn("/api/applications/calculator/mathics/ask", APPLICATIONS_INDEX_HTML)
            self.assertIn("/api/applications/calculator/mathics/evaluate", APPLICATIONS_INDEX_HTML)
            self.assertIn("normalizeGraphExpression", APPLICATIONS_INDEX_HTML)
            self.assertIn("compileGraphExpression", APPLICATIONS_INDEX_HTML)
            self.assertIn("drawCalculatorGraph", APPLICATIONS_INDEX_HTML)
            self.assertIn("calculatorGraphFunctions", APPLICATIONS_INDEX_HTML)
            self.assertIn("Translate this calculator word problem", APPLICATIONS_INDEX_HTML)
            self.assertIn("/api/chat", APPLICATIONS_INDEX_HTML)
            self.assertIn("normalizeCalculatorExpression", APPLICATIONS_INDEX_HTML)
            self.assertIn("calculator ready", APPLICATIONS_INDEX_HTML)
            self.assertIn('getContext("webgl2")', APPLICATIONS_INDEX_HTML)
            self.assertIn("compileShader", APPLICATIONS_INDEX_HTML)
            self.assertIn("requestAnimationFrame", APPLICATIONS_INDEX_HTML)
            self.assertIn("layoutDesktopIcons", APPLICATIONS_INDEX_HTML)
            self.assertIn("ensureDesktopIcons", APPLICATIONS_INDEX_HTML)
            self.assertIn("applicationFromPath", APPLICATIONS_INDEX_HTML)
            self.assertIn("syncApplicationRoute", APPLICATIONS_INDEX_HTML)


    def test_calculator_uses_shared_embedded_chat_mount(self) -> None:
        self.assertIn('id="calculator-chat-panel"', APPLICATIONS_INDEX_HTML)
        self.assertIn('id="calculator-chat-notebook"', APPLICATIONS_INDEX_HTML)
        self.assertIn('data-chat-console-embed="calculator"', APPLICATIONS_INDEX_HTML)
        self.assertIn('data-chat-console-active-app="calculator"', APPLICATIONS_INDEX_HTML)
        self.assertIn('data-chat-console-target-kind="calculator-session"', APPLICATIONS_INDEX_HTML)
        self.assertIn('data-chat-console-layout="compact"', APPLICATIONS_INDEX_HTML)
        self.assertIn('data-chat-console-show-thread-rail="0"', APPLICATIONS_INDEX_HTML)
        self.assertIn("function mountCalculatorEmbeddedChat", APPLICATIONS_INDEX_HTML)
        self.assertIn("const mount = api.mountEmbedded || window.chatConsoleMountEmbedded;", APPLICATIONS_INDEX_HTML)
        self.assertIn("getEmbeddedContext: calculatorEmbeddedChatContextSnapshot", APPLICATIONS_INDEX_HTML)
        self.assertIn("window.MainComputerCalculatorContext", APPLICATIONS_INDEX_HTML)
        self.assertIn("linked_targets: [{", APPLICATIONS_INDEX_HTML)
        self.assertIn("chatConsoleLegacyCalculatorNotebook", APPLICATIONS_INDEX_HTML)


    def test_spreadsheet_imports_embedded_chat_console_hooks(self) -> None:
        self.assertIn('data-app="spreadsheet"', APPLICATIONS_INDEX_HTML)
        self.assertIn('id="spreadsheet-chat-thread-panel"', APPLICATIONS_INDEX_HTML)
        self.assertIn('id="spreadsheet-embedded-chat-notebook"', APPLICATIONS_INDEX_HTML)
        self.assertIn('data-chat-thread-list', APPLICATIONS_INDEX_HTML)
        self.assertNotIn('data-chat-console-new="javascript"', APPLICATIONS_INDEX_HTML)
        self.assertIn("spreadsheetInitChatThreadIntegration", APPLICATIONS_INDEX_HTML)
        self.assertIn("spreadsheetMountChatThreadController", APPLICATIONS_INDEX_HTML)
        self.assertIn("window.chatConsoleMountSpreadsheetEmbedded(panel", APPLICATIONS_INDEX_HTML)
        self.assertIn("getLinkedThreadId: spreadsheetGetWorkbookChatThreadId", APPLICATIONS_INDEX_HTML)
        self.assertIn("setLinkedThreadId(threadId, threadValue, context = {})", APPLICATIONS_INDEX_HTML)
        self.assertIn("chatConsoleMountEmbedded", APPLICATIONS_INDEX_HTML)
        self.assertIn("chatConsoleMountSpreadsheetEmbedded", APPLICATIONS_INDEX_HTML)
        self.assertIn("window.MainComputerChatConsole", APPLICATIONS_INDEX_HTML)
        self.assertIn('host.dataset.chatConsoleActiveApp = config.activeApp;', APPLICATIONS_INDEX_HTML)
        self.assertIn("spreadsheetImportChatCodeSnippetFromChatConsole", APPLICATIONS_INDEX_HTML)
        self.assertIn("Import to selected cell", APPLICATIONS_INDEX_HTML)
        self.assertIn("spreadsheetRenderChatImportHistory", APPLICATIONS_INDEX_HTML)
        self.assertIn("restored original chat import", APPLICATIONS_INDEX_HTML.lower())


    def test_chat_console_embedded_mount_contract_is_additive(self) -> None:
        self.assertIn("window.chatConsoleMountEmbedded = chatConsoleMountEmbedded;", APPLICATIONS_INDEX_HTML)
        self.assertIn("window.chatConsoleMountSpreadsheetEmbedded = chatConsoleMountSpreadsheetEmbedded;", APPLICATIONS_INDEX_HTML)
        self.assertIn("mountEmbedded: chatConsoleMountEmbedded", APPLICATIONS_INDEX_HTML)
        self.assertIn("mountSpreadsheetEmbedded: chatConsoleMountSpreadsheetEmbedded", APPLICATIONS_INDEX_HTML)
        self.assertIn("function chatConsoleMountEmbedded(root, options = {})", APPLICATIONS_INDEX_HTML)
        self.assertIn("function chatConsoleMountSpreadsheetEmbedded(root, options = {})", APPLICATIONS_INDEX_HTML)
        self.assertIn("targetKind = String(options.targetKind", APPLICATIONS_INDEX_HTML)
        self.assertIn("targetId = String(options.targetId", APPLICATIONS_INDEX_HTML)
        self.assertIn("showThreadRail", APPLICATIONS_INDEX_HTML)
        self.assertIn("showCurrentThreadBar", APPLICATIONS_INDEX_HTML)
        self.assertIn("getEmbeddedContext", APPLICATIONS_INDEX_HTML)
        self.assertIn("buildThreadMetadata", APPLICATIONS_INDEX_HTML)
        self.assertIn("embedded_context_source", APPLICATIONS_INDEX_HTML)
        self.assertIn("payload.embedded_context = embeddedContext", APPLICATIONS_INDEX_HTML)
        self.assertIn("chat-console-embedded-no-thread-rail", APPLICATIONS_INDEX_HTML)
        self.assertIn("chat-console-embedded-layout-compact", APPLICATIONS_INDEX_HTML)

    def test_calculator_basic_controls_stay_bound_to_basic_calculator_in_scientific_mode(self) -> None:
        self.assertNotIn("askScientificCalculatorModel({useTopPrompt: true})", APPLICATIONS_INDEX_HTML)
        self.assertNotIn("insertCalculatorGraphText(key);", APPLICATIONS_INDEX_HTML)
        self.assertNotIn('calculatorGraphStatus.textContent = "graph expression cleared";', APPLICATIONS_INDEX_HTML)
        self.assertNotIn("keys edit f(x)", APPLICATIONS_INDEX_HTML)
        self.assertIn('document.querySelectorAll("[data-calc-key]")', APPLICATIONS_INDEX_HTML)
        self.assertIn('calculatorDisplay.value = key;', APPLICATIONS_INDEX_HTML)
        self.assertIn('document.querySelectorAll("[data-calc-graph-token]")', APPLICATIONS_INDEX_HTML)


if __name__ == "__main__":
    unittest.main()
