from __future__ import annotations

import unittest

from main_computer.viewport import APPLICATIONS_INDEX_HTML


class ViewportSceneSurfaceTests(unittest.TestCase):
    def test_game_surface_tab_renders_movable_shuttle3d_surface(self) -> None:
        self.assertIn("Game Surface", APPLICATIONS_INDEX_HTML)
        self.assertIn("Shuttle boarding defense is ready.", APPLICATIONS_INDEX_HTML)
        self.assertIn("Walk the vertex-built shuttle", APPLICATIONS_INDEX_HTML)
        self.assertIn("sprite-actor", APPLICATIONS_INDEX_HTML)
        self.assertIn("scene-object--sprite-actor", APPLICATIONS_INDEX_HTML)
        self.assertIn("scene-sprite-frame", APPLICATIONS_INDEX_HTML)
        self.assertIn("scene-sprite-rig-layer", APPLICATIONS_INDEX_HTML)
        self.assertIn("scene-particle-orbit", APPLICATIONS_INDEX_HTML)
        self.assertIn("spell-swirl", APPLICATIONS_INDEX_HTML)
        self.assertIn("spell-bolt", APPLICATIONS_INDEX_HTML)
        self.assertIn("impact-burst", APPLICATIONS_INDEX_HTML)
        self.assertIn("linkedParticleProjection", APPLICATIONS_INDEX_HTML)
        self.assertIn("scene-particle-bolt-run", APPLICATIONS_INDEX_HTML)
        self.assertIn("renderShuttle3dScene", APPLICATIONS_INDEX_HTML)
        self.assertIn("bindShuttle3dLookaround", APPLICATIONS_INDEX_HTML)
        self.assertIn("disposeShuttle3dLookaround", APPLICATIONS_INDEX_HTML)
        self.assertIn("class Shuttle3dVertexRenderer", APPLICATIONS_INDEX_HTML)
        self.assertIn("class Shuttle3dGeometryWriter", APPLICATIONS_INDEX_HTML)
        self.assertIn("shuttle3dBoundsVertices", APPLICATIONS_INDEX_HTML)
        self.assertIn("scene-shuttle3d-canvas", APPLICATIONS_INDEX_HTML)
        self.assertIn("gl.drawArrays(gl.TRIANGLES", APPLICATIONS_INDEX_HTML)
        self.assertIn("new Float32Array", APPLICATIONS_INDEX_HTML)
        self.assertIn('container.dataset.shuttle3d = "webgl-vertex-mesh"', APPLICATIONS_INDEX_HTML)
        self.assertNotIn("scene-shuttle3d-wall--forward", APPLICATIONS_INDEX_HTML)
        self.assertNotIn("scene-shuttle3d-console--helm", APPLICATIONS_INDEX_HTML)
        self.assertIn("shuttle3d-lookaround", APPLICATIONS_INDEX_HTML)
        self.assertIn("parentId", APPLICATIONS_INDEX_HTML)
        self.assertIn("particle-emitter", APPLICATIONS_INDEX_HTML)
        self.assertIn('id="webgl-particle-density"', APPLICATIONS_INDEX_HTML)
        self.assertIn('id="game-editor-particle-density"', APPLICATIONS_INDEX_HTML)
        self.assertIn("sceneVfxSettings", APPLICATIONS_INDEX_HTML)
        self.assertIn("particleMultiplier", APPLICATIONS_INDEX_HTML)
        self.assertIn("phase-5-shuttle-boarding-combat", APPLICATIONS_INDEX_HTML)
        self.assertIn("shuttle3dMovementConfig", APPLICATIONS_INDEX_HTML)
        self.assertIn("shuttle3dCombatConfig", APPLICATIONS_INDEX_HTML)
        self.assertIn("firePhaser(nowMs", APPLICATIONS_INDEX_HTML)
        self.assertIn("spawnAlien(nowMs)", APPLICATIONS_INDEX_HTML)
        self.assertIn("scene-shuttle3d-health", APPLICATIONS_INDEX_HTML)
        self.assertIn("setMovementKey(code, active)", APPLICATIONS_INDEX_HTML)
        self.assertIn("updateMovement(deltaSeconds)", APPLICATIONS_INDEX_HTML)
        self.assertIn('movementCodes = new Set(["KeyW", "KeyA", "KeyS", "KeyD"', APPLICATIONS_INDEX_HTML)
        self.assertIn('container.addEventListener("keyup", keyUp)', APPLICATIONS_INDEX_HTML)
        self.assertIn('window.addEventListener("blur", blur)', APPLICATIONS_INDEX_HTML)
        self.assertIn("W/A/S/D", APPLICATIONS_INDEX_HTML)
        self.assertIn("enableClickMovement", APPLICATIONS_INDEX_HTML)
        self.assertIn("screenPointToIsoWorld", APPLICATIONS_INDEX_HTML)
        self.assertIn("scene-movement-marker", APPLICATIONS_INDEX_HTML)
        self.assertIn("W/A/S/D to walk", APPLICATIONS_INDEX_HTML)
        self.assertIn("removeEventListener(\"pointerdown\", container.__mainComputerClickMovementHandler)", APPLICATIONS_INDEX_HTML)
        self.assertIn("startSceneMovement", APPLICATIONS_INDEX_HTML)
        self.assertIn("movementSpeed(scene)", APPLICATIONS_INDEX_HTML)
        self.assertIn("emitterProjectionState(object, scene, projected)", APPLICATIONS_INDEX_HTML)
        self.assertIn("updateEmitter(object, scene, projected)", APPLICATIONS_INDEX_HTML)
        self.assertIn("bufferSubData(", APPLICATIONS_INDEX_HTML)
        self.assertNotIn("scene-click-move", APPLICATIONS_INDEX_HTML)
        self.assertNotIn("player-capsule", APPLICATIONS_INDEX_HTML)
        self.assertNotIn("mesh-actor", APPLICATIONS_INDEX_HTML)
        self.assertIn('id="webgl-demo"', APPLICATIONS_INDEX_HTML)
        self.assertIn('aria-label="Scene-aware game surface"', APPLICATIONS_INDEX_HTML)
        self.assertIn('data-scene-id="default-empty-scene"', APPLICATIONS_INDEX_HTML)

    def test_game_surface_uses_shared_scene_viewer_not_engine_runtime(self) -> None:
        self.assertIn("function initWebgl(", APPLICATIONS_INDEX_HTML)
        self.assertIn("MainComputerSceneStore", APPLICATIONS_INDEX_HTML)
        self.assertIn("MainComputerSceneViewer", APPLICATIONS_INDEX_HTML)
        self.assertIn("sceneWebglShader", APPLICATIONS_INDEX_HTML)
        self.assertIn("sceneWebglProgram", APPLICATIONS_INDEX_HTML)
        self.assertNotIn("MainComputerBabylonPreview", APPLICATIONS_INDEX_HTML)
        self.assertNotIn("BABYLON", APPLICATIONS_INDEX_HTML)
        self.assertNotIn("MeshBuilder", APPLICATIONS_INDEX_HTML)
        self.assertNotIn("SceneLoader", APPLICATIONS_INDEX_HTML)


if __name__ == "__main__":
    unittest.main()
