from __future__ import annotations

import tempfile
import threading
import urllib.request
import unittest
from pathlib import Path

from main_computer.config import MainComputerConfig
from main_computer.viewport import ViewportServer


class GameEditorFunctionalSceneTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temp_dir = tempfile.TemporaryDirectory()
        self.root = Path(self.temp_dir.name)
        self.server = ViewportServer(("127.0.0.1", 0), MainComputerConfig(workspace=self.root), verbose=False)
        self.server.debug_root = self.root
        self.thread = threading.Thread(target=self.server.serve_forever, daemon=True)
        self.thread.start()
        self.base_url = f"http://127.0.0.1:{self.server.server_address[1]}"

    def tearDown(self) -> None:
        self.server.shutdown()
        self.server.server_close()
        self.thread.join(timeout=2)
        self.temp_dir.cleanup()

    def get_text(self, path: str) -> str:
        with urllib.request.urlopen(self.base_url + path, timeout=5) as response:
            return response.read().decode("utf-8")

    def test_game_surface_route_renders_scene_aware_surface(self) -> None:
        html = self.get_text("/applications/webgl")
        self.assertIn('id="webgl-demo"', html)
        self.assertIn('aria-label="Scene-aware game surface"', html)
        self.assertIn('data-scene-id="default-empty-scene"', html)
        self.assertIn("MainComputerSceneViewer", html)
        self.assertIn("main-computer-game-editor-scene-change", html)
        self.assertIn("loadWebglProject", html)
        self.assertIn("Vertex-built shuttle boarding-defense surface", html)
        self.assertIn("sprite-actor", html)
        self.assertIn("scene-object--sprite-actor", html)
        self.assertIn("scene-sprite-frame", html)
        self.assertIn("scene-sprite-rig-layer", html)
        self.assertIn("scene-particle-orbit", html)
        self.assertIn("spell-swirl", html)
        self.assertIn("spell-bolt", html)
        self.assertIn("impact-burst", html)
        self.assertIn("linkedParticleProjection", html)
        self.assertIn("parentId", html)
        self.assertIn("particle-emitter", html)
        self.assertIn('id="webgl-particle-density"', html)
        self.assertIn("particleMultiplier", html)
        self.assertIn("renderShuttle3dScene", html)
        self.assertIn("bindShuttle3dLookaround", html)
        self.assertIn("class Shuttle3dVertexRenderer", html)
        self.assertIn("class Shuttle3dGeometryWriter", html)
        self.assertIn("shuttle3dBoundsVertices", html)
        self.assertIn("scene-shuttle3d-canvas", html)
        self.assertIn("gl.drawArrays(gl.TRIANGLES", html)
        self.assertIn('container.dataset.shuttle3d = "webgl-vertex-mesh"', html)
        self.assertNotIn("scene-shuttle3d-wall--forward", html)
        self.assertIn("phase-5-shuttle-boarding-combat", html)
        self.assertIn("shuttle3dMovementConfig", html)
        self.assertIn("shuttle3dCombatConfig", html)
        self.assertIn("shuttle3dPilotStationsConfig", html)
        self.assertIn("shuttle3dFlightConfig", html)
        self.assertIn("shuttle3dMotherShipInteriorConfig", html)
        self.assertIn("createFlightState()", html)
        self.assertIn("createShipState()", html)
        self.assertIn("this.flight = this.createFlightState()", html)
        self.assertIn("this.shipState = this.createShipState()", html)
        self.assertIn("pickPilotStation(clientX, clientY)", html)
        self.assertIn("setPilotMode(active", html)
        self.assertIn("firePhaser(nowMs", html)
        self.assertIn("spawnAlien(nowMs)", html)
        self.assertIn("scene-shuttle3d-health", html)
        self.assertIn("scene-shuttle3d-pilot-prompt", html)
        self.assertIn("console-hover-e-key", html)
        self.assertIn("appendFlightScene(builder", html)
        self.assertIn("flightDistance", html)
        self.assertIn("startDockingCutscene(nowMs", html)
        self.assertIn("appendDockingCutscene(builder", html)
        self.assertIn("appendShuttleBayScene(builder", html)
        self.assertIn("alternateSceneActive = dockingCutsceneActive || shuttleBaySceneActive", html)
        self.assertIn("FIRST-PERSON CONTROL", html)
        self.assertIn("dockingCutsceneActive", html)
        self.assertIn("playerExitedToBay", html)
        self.assertIn("enterShuttleBayPlayerControl(force", html)
        self.assertIn("isShuttleBayPlayerControlActive()", html)
        self.assertIn("shuttleBayControlActive", html)
        self.assertIn("forceShuttleBayControl()", html)
        self.assertIn("scene-shuttle3d-twiddle-system", html)
        self.assertIn("scene-shuttle3d-ship-line", html)
        self.assertIn("Shuttle Bay Twiddle System", html)
        self.assertIn("door.bay-access", html)
        self.assertIn("Starboard Interior Access", html)
        self.assertIn("enterBayOpsAccess()", html)
        self.assertIn("Press E to enter through", html)
        self.assertIn("door.bay-inner", html)
        self.assertIn("bridge.access", html)
        self.assertIn("bridge.deck", html)
        self.assertIn("Bridge Viewscreen", html)
        self.assertIn("appendBridgeViewscreenEnemy(builder, nowMs", html)
        self.assertIn("Bridge tactical lock engaged. Enemy raider is tracked on the main viewscreen.", html)
        self.assertIn("Bridge Tactical Console", html)
        self.assertIn("shuttle3dMotherShipInteriorStateDefaults()", html)
        self.assertIn("createShipStateFromDefaults()", html)
        self.assertIn("game.motherShipInterior.stateDefaults.v1", html)
        self.assertIn("shuttle3dMotherShipInteriorLevelDefaults()", html)
        self.assertIn("game.motherShipInterior.level.v1", html)
        self.assertIn("Patch C: mother-ship movement bounds now come from the level definition", html)
        self.assertIn("Patch D makes E-key targets data-driven", html)
        self.assertIn("shuttle3dNormalizeMotherShipInteractables", html)
        self.assertIn("performShipInteractionAction(target)", html)
        self.assertIn("Patch E formalizes action ids as registry entries", html)
        self.assertIn("shuttle3dNormalizeMotherShipInteractions", html)
        self.assertIn("createShipInteractionRegistry()", html)
        self.assertIn("createShipInteractionHandlerMap()", html)
        self.assertIn("No interaction handler registered", html)
        self.assertIn("Patch F validates definition reachability before content patches ship", html)
        self.assertIn("shuttle3dValidateMotherShipInteriorConfig", html)
        self.assertIn("shuttle3dNormalizeMotherShipValidationRules", html)
        self.assertIn("validationReport", html)
        self.assertIn("this.shipDefinitionValidation", html)
        self.assertIn("requireOpenDoors", html)
        self.assertIn("Patch G: keep renderer bootstrapping in named seams", html)
        self.assertIn("initializeRendererFrameState(scene)", html)
        self.assertIn("initializeGameplaySubsystems(scene)", html)
        self.assertIn("initializeCombatRuntimeState()", html)
        self.assertIn("initializeGeometryBuffers()", html)
        self.assertIn("initializeCanvasLifecycle(canvas)", html)
        self.assertIn("rendererSubsystems", html)
        self.assertIn("Patch H makes ship visual content data-first", html)
        self.assertIn("shuttle3dNormalizeMotherShipProps", html)
        self.assertIn("appendMotherShipInteriorProps(builder, nowMs)", html)
        self.assertIn("requireRenderableProps", html)
        self.assertIn("prop.bridge-tactical-marker", html)
        self.assertIn("prop.bridge-viewscreen-status", html)
        self.assertIn("Patch I also moves", html)
        self.assertIn('kind === "map-marker"', html)
        self.assertIn("prop.marker.bridge-viewscreen", html)
        self.assertIn("Patch J keeps data-defined visual content honest by validating prop targets", html)
        self.assertIn("requirePropTargets", html)
        self.assertIn("propTargetIsKnown", html)
        self.assertIn("targets missing content", html)
        self.assertIn("game-runtime-patch-J-prop-target-validation", html)
        self.assertIn('action: "fireBridgeTacticalConsole"', html)
        self.assertIn("shuttle3dNormalizeMotherShipRooms", html)
        self.assertIn("shuttle3dMovementBoundsFromRooms", html)
        self.assertIn("Patch B keeps the no-locked-door rule centralized", html)
        self.assertIn("fireBridgeTacticalConsole()", html)
        self.assertIn("objective.enemy-attack", html)
        self.assertIn("objective.enemy-disabled", html)
        self.assertIn("enemyShipHullPercent", html)
        self.assertIn("Bridge tactical console fired", html)
        self.assertIn('setShipTerminalState("terminal.bridge-viewscreen", "tracking")', html)
        self.assertIn("objective.enemy-track", html)
        self.assertIn("bridgeViewscreenTrackingActive", html)
        self.assertIn('nextLocation === "bridge.deck"', html)
        self.assertIn("Door state is informational only", html)
        self.assertIn("No door lock is required", html)
        self.assertIn("shipInteractionTarget()", html)
        self.assertIn("interactWithShip()", html)
        self.assertIn("Engineering Power Console", html)
        self.assertIn("motherShipWalkableRegions()", html)
        self.assertIn("Keep the access vestibule, visible corridor, and walkable bounds aligned", html)
        self.assertIn("Bay Ops interior transit spine", html)
        self.assertIn("zone.location && zone.location !== activeLocation", html)
        self.assertIn("twiddleSystem.hidden = !(pilot.dockingCutsceneActive || (!pilot.shuttleBayControlActive", html)
        self.assertIn('event.code === "KeyT"', html)
        self.assertIn("const bayLookConfig = shuttle3dCameraConfig(scene)", html)
        self.assertIn("Shuttle bay control handoff callback failed", html)
        self.assertNotIn("setShuttle3dLook(container, bay.yaw, bay.pitch, config);", html)
        self.assertIn("W/A/S/D to walk the", html)
        self.assertIn("Face into the mother ship and toward the starboard/right side of the bay.", html)
        self.assertIn("yaw: 32", html)
        self.assertIn("pitch: -4", html)
        self.assertIn("Mother Ship Shuttle Bay", html)
        self.assertIn("setMovementKey(code, active)", html)
        self.assertIn("updateMovement(deltaSeconds)", html)
        self.assertIn('container.addEventListener("keyup", keyUp)', html)
        self.assertIn("W/A/S/D", html)
        self.assertIn("enableClickMovement", html)
        self.assertIn("screenPointToIsoWorld", html)
        self.assertIn("scene-movement-marker", html)
        self.assertIn("W/A/S/D to walk", html)
        self.assertIn("removeEventListener(\"pointerdown\", container.__mainComputerClickMovementHandler)", html)
        self.assertIn("startSceneMovement", html)
        self.assertIn("movementSpeed(scene)", html)
        self.assertNotIn("scene-click-move", html)
        self.assertNotIn("player-capsule", html)
        self.assertNotIn("mesh-actor", html)
        self.assertNotIn("MainComputerBabylonPreview", html)
        self.assertNotIn("MeshBuilder", html)
        self.assertNotIn("SceneLoader", html)

    def test_game_editor_route_renders_project_backed_scene_builder(self) -> None:
        html = self.get_text("/applications/game-editor")
        self.assertIn('data-app="game-editor"', html)
        self.assertIn('id="game-editor-app"', html)
        self.assertIn("Project-backed scene editor is ready.", html)
        self.assertIn("function initGameEditorApp()", html)
        self.assertIn("gameEditorApi", html)
        self.assertIn("main-computer-game-editor-scene-change", html)
        self.assertIn("syncGameEditorSceneStore({reason: message})", html)
        self.assertIn("MainComputerSceneStore", html)
        self.assertIn('id="game-editor-preview"', html)
        self.assertIn('id="game-editor-webgl-canvas"', html)
        self.assertIn('id="game-editor-scene-select"', html)
        self.assertIn('aria-label="Select project scene"', html)
        self.assertIn('id="game-editor-new-scene"', html)
        self.assertIn('id="game-editor-archive-scene"', html)
        self.assertIn("function selectGameEditorScene", html)
        self.assertIn("function createGameEditorProjectScene", html)
        self.assertIn("function archiveGameEditorProjectScene", html)
        self.assertIn("project.archivedScenes", html)
        self.assertIn('url.searchParams.set("scene"', html)
        self.assertIn('id="game-editor-chat-toggle"', html)
        self.assertIn('aria-controls="game-editor-chat-popout"', html)
        self.assertIn('id="game-editor-chat-popout"', html)
        self.assertIn('id="game-editor-chat-panel"', html)
        self.assertIn('data-chat-console-embed="game-editor"', html)
        self.assertIn('data-chat-console-layout="full"', html)
        self.assertIn('data-chat-console-show-thread-rail="1"', html)
        self.assertIn('layout: "full"', html)
        self.assertIn("showThreadRail: true", html)
        self.assertIn("width: min(980px, calc(100% - 28px));", html)
        self.assertIn("Game Assistant", html)
        self.assertIn("function setGameEditorChatOpen", html)
        self.assertIn("setGameEditorChatOpen(!gameEditorState.chatOpen)", html)
        self.assertIn('nodes.chatPopout?.addEventListener("click", (event) => {', html)
        self.assertIn("event.stopPropagation();", html)
        self.assertIn("window.MainComputerGameEditorContext", html)
        self.assertIn("getEmbeddedContext: gameEditorChatContextSnapshot", html)
        self.assertIn('id: "game-editor-edit"', html)
        self.assertIn('label: "Edit this game"', html)
        self.assertIn("defaultEnabled: true", html)
        self.assertIn('pathway: "game-editor-rag-edit-smoke"', html)
        self.assertIn("/api/applications/game-editor/project/write", html)
        self.assertIn("/api/applications/game-editor/asset/upload", html)
        self.assertIn('id="game-editor-particle-density"', html)
        self.assertIn('data-vfx-preset="4"', html)


if __name__ == "__main__":
    unittest.main()
