from __future__ import annotations

import json
import shutil
import subprocess
from dataclasses import replace
from pathlib import Path

from main_computer.mcel_application_definition_normalizer import (
    NORMALIZER_VERSION,
    NORMALIZED_PATH,
    build_normalization_plan,
    check_normalization,
)


ROOT = Path(__file__).resolve().parents[1]
APP_ID = "contract-workbench"


def test_workbench_definition_normalization_is_fresh_and_complete() -> None:
    plan = build_normalization_plan(APP_ID, ROOT)
    fresh, stale = check_normalization(plan)
    assert fresh is True
    assert stale == ()
    assert plan.generated_contract_count == 7
    assert plan.definition_fingerprint.startswith("sha256:")
    assert NORMALIZED_PATH in plan.files
    for name in ("domain", "intents", "adapter", "surface", "layout", "acceptance", "observation"):
        source = plan.files[f"contracts/{name}.js"].decode("utf-8")
        assert NORMALIZER_VERSION in source
        assert plan.definition_fingerprint in source
        assert "Do not edit this file directly." in source


def test_normalized_definition_carries_function_hashes_not_function_source() -> None:
    plan = build_normalization_plan(APP_ID, ROOT)
    normalized = json.loads(plan.files[NORMALIZED_PATH])
    assert normalized["schema"] == "mcel.application-definition.normalized.v1"
    assert normalized["definitionFingerprint"] == plan.definition_fingerprint
    assert normalized["definition"]["operations"]["add-contract"]["transition"]["kind"] == "function"
    assert normalized["definition"]["operations"]["add-contract"]["transition"]["sha256"].startswith("sha256:")
    assert "$function" not in plan.files[NORMALIZED_PATH].decode("utf-8")


def test_check_detects_generated_contract_drift_without_touching_repository(tmp_path: Path) -> None:
    plan = build_normalization_plan(APP_ID, ROOT)
    package = tmp_path / APP_ID
    for relative, content in plan.files.items():
        target = package / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(content)
    drifted = package / "contracts/surface.js"
    drifted.write_text(drifted.read_text(encoding="utf-8") + "// drift\n", encoding="utf-8")
    copied_plan = replace(plan, package_root=package)
    fresh, stale = check_normalization(copied_plan)
    assert fresh is False
    assert stale == ("contracts/surface.js",)


def test_generated_adapter_preserves_synchronous_operation_semantics() -> None:
    source = """
      import {ContractWorkbenchAdapter as adapter} from './runtime/build/mcel/web/applications/mcel-packages/contract-workbench/contracts/adapter.js';
      const state={contracts:[],nextContractId:1,revision:0};
      const input={expectedRevision:0,payload:{name:'Steel',quantity:12,category:'materials'}};
      const preflight=adapter.preflight({intentId:'add-contract',input,state});
      const after=adapter.transition({intentId:'add-contract',input,state});
      const valid=adapter.validateEffects({intentId:'add-contract',before:state,after,input});
      process.stdout.write(JSON.stringify({preflight,after,valid}));
    """
    completed = subprocess.run(
        [shutil.which("node") or "node", "--input-type=module", "-e", source],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
        timeout=45,
    )
    assert completed.returncode == 0, completed.stdout + completed.stderr
    payload = json.loads(completed.stdout)
    assert payload["preflight"] == {"ok": True}
    assert payload["after"]["contracts"][0]["id"] == "contract-1"
    assert payload["after"]["revision"] == 1
    assert payload["valid"] is True


def test_generated_domain_invariants_are_self_contained_and_executable() -> None:
    source = """
      import {ContractWorkbenchDomain as domain} from './runtime/build/mcel/web/applications/mcel-packages/contract-workbench/contracts/domain.js';
      const valid={contracts:[],nextContractId:1,revision:0};
      const invalid={contracts:[{id:'x',name:'',category:'materials',quantity:1,quoteStatus:'idle',quoteAmount:0}],nextContractId:1,revision:0};
      process.stdout.write(JSON.stringify({
        valid:domain.invariants.every((entry)=>entry.check(valid)),
        invalid:domain.invariants.every((entry)=>entry.check(invalid))
      }));
    """
    completed = subprocess.run(
        [shutil.which("node") or "node", "--input-type=module", "-e", source],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
        timeout=45,
    )
    assert completed.returncode == 0, completed.stdout + completed.stderr
    assert json.loads(completed.stdout) == {"valid": True, "invalid": False}


def test_manifest_records_full_definition_and_proof_convergence() -> None:
    manifest = json.loads((ROOT / "mcel_apps/contract-workbench/mcel.app.json").read_text(encoding="utf-8"))
    assert manifest["authoring"]["normalizedDefinition"] == NORMALIZED_PATH
    assert manifest["normalization"]["normalizer"] == NORMALIZER_VERSION
    assert manifest["normalization"]["definitionFingerprint"].startswith("sha256:")
    assert "application-definition-normalization" not in manifest["conformance"]["missingBridges"]
    assert "renderer-local-state" not in manifest["conformance"]["missingBridges"]
    assert "derived-state" not in manifest["conformance"]["missingBridges"]
    assert "dynamic-input-binding" not in manifest["conformance"]["missingBridges"]
    assert "control-payload-extraction" not in manifest["conformance"]["missingBridges"]
    assert "keyed-collection-reconciliation" not in manifest["conformance"]["missingBridges"]
    assert "dynamic-item-control-binding" not in manifest["conformance"]["missingBridges"]
    assert "provisional-state" not in manifest["conformance"]["missingBridges"]
    assert "provisional-state-runtime" not in manifest["conformance"]["missingBridges"]
    assert "capability-operation-runtime" not in manifest["conformance"]["missingBridges"]
    assert manifest["conformance"] == {
        "currentMode": "semantic-runtime-proven",
        "missingBridges": [],
        "targetMode": "semantic-runtime-proven",
    }
    assert manifest["authoring"]["status"] == "semantic-runtime-proven"


def test_generated_domain_materializes_runtime_state_and_capability_definitions() -> None:
    source = """
      import {ContractWorkbenchDomain as domain} from './runtime/build/mcel/web/applications/mcel-packages/contract-workbench/contracts/domain.js';
      const local=domain.rendererLocalStateDefinitions.map((entry)=>({id:entry.id,initial:entry.initial,schema:entry.schema.name}));
      const derived=domain.derivedState.map((entry)=>({id:entry.id,reads:entry.reads,schema:entry.schema.name,computeType:typeof entry.compute}));
      const provisional=domain.provisionalStateDefinitions.map((entry)=>({id:entry.id,initial:entry.initial,schema:entry.schema.name}));
      const capabilities=Object.fromEntries(Object.entries(domain.capabilities).map(([alias,entry])=>[alias,{id:entry.id,operations:Object.keys(entry.operations)}]));
      process.stdout.write(JSON.stringify({local,derived,provisional,capabilities}));
    """
    completed = subprocess.run(
        [shutil.which("node") or "node", "--input-type=module", "-e", source],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
        timeout=45,
    )
    assert completed.returncode == 0, completed.stdout + completed.stderr
    payload = json.loads(completed.stdout)
    assert [entry["id"] for entry in payload["local"]] == [
        "draftCategory",
        "draftName",
        "draftQuantity",
        "filterText",
        "sortMode",
    ]
    assert [entry["id"] for entry in payload["derived"]] == [
        "canSubmit",
        "totalQuantity",
        "visibleContracts",
    ]
    assert all(entry["computeType"] == "function" for entry in payload["derived"])
    assert payload["provisional"] == [{"id": "quoteProgress", "initial": {}, "schema": "object"}]
    assert payload["capabilities"] == {
        "quotes": {"id": "contract-workbench.quote-service", "operations": ["requestQuote"]}
    }
