from __future__ import annotations

import unittest

from main_computer.viewport import APPLICATIONS_INDEX_HTML


class ViewportSceneSurfaceTests(unittest.TestCase):
    def test_game_surface_tab_renders_movable_shuttle3d_surface(self) -> None:
        self.assertIn("Game Surface", APPLICATIONS_INDEX_HTML)
        self.assertIn("Shuttle boarding defense is ready.", APPLICATIONS_INDEX_HTML)
        self.assertIn("Walk the vertex-built shuttle", APPLICATIONS_INDEX_HTML)
        self.assertIn("sprite-actor", APPLICATIONS_INDEX_HTML)
        self.assertIn("scene-object--sprite-actor", APPLICATIONS_INDEX_HTML)
        self.assertIn("scene-sprite-frame", APPLICATIONS_INDEX_HTML)
        self.assertIn("scene-sprite-rig-layer", APPLICATIONS_INDEX_HTML)
        self.assertIn("scene-particle-orbit", APPLICATIONS_INDEX_HTML)
        self.assertIn("spell-swirl", APPLICATIONS_INDEX_HTML)
        self.assertIn("spell-bolt", APPLICATIONS_INDEX_HTML)
        self.assertIn("impact-burst", APPLICATIONS_INDEX_HTML)
        self.assertIn("linkedParticleProjection", APPLICATIONS_INDEX_HTML)
        self.assertIn("scene-particle-bolt-run", APPLICATIONS_INDEX_HTML)
        self.assertIn("renderShuttle3dScene", APPLICATIONS_INDEX_HTML)
        self.assertIn("bindShuttle3dLookaround", APPLICATIONS_INDEX_HTML)
        self.assertIn("disposeShuttle3dLookaround", APPLICATIONS_INDEX_HTML)
        self.assertIn("class Shuttle3dVertexRenderer", APPLICATIONS_INDEX_HTML)
        self.assertIn("class Shuttle3dGeometryWriter", APPLICATIONS_INDEX_HTML)
        self.assertIn("shuttle3dBoundsVertices", APPLICATIONS_INDEX_HTML)
        self.assertIn("scene-shuttle3d-canvas", APPLICATIONS_INDEX_HTML)
        self.assertIn("gl.drawArrays(gl.TRIANGLES", APPLICATIONS_INDEX_HTML)
        self.assertIn("new Float32Array", APPLICATIONS_INDEX_HTML)
        self.assertIn('container.dataset.shuttle3d = "webgl-vertex-mesh"', APPLICATIONS_INDEX_HTML)
        self.assertNotIn("scene-shuttle3d-wall--forward", APPLICATIONS_INDEX_HTML)
        self.assertNotIn("scene-shuttle3d-console--helm", APPLICATIONS_INDEX_HTML)
        self.assertIn("shuttle3d-lookaround", APPLICATIONS_INDEX_HTML)
        self.assertIn("parentId", APPLICATIONS_INDEX_HTML)
        self.assertIn("particle-emitter", APPLICATIONS_INDEX_HTML)
        self.assertIn('id="webgl-particle-density"', APPLICATIONS_INDEX_HTML)
        self.assertIn('id="game-editor-particle-density"', APPLICATIONS_INDEX_HTML)
        self.assertIn("sceneVfxSettings", APPLICATIONS_INDEX_HTML)
        self.assertIn("particleMultiplier", APPLICATIONS_INDEX_HTML)
        self.assertIn("phase-5-shuttle-boarding-combat", APPLICATIONS_INDEX_HTML)
        self.assertIn("shuttle3dMovementConfig", APPLICATIONS_INDEX_HTML)
        self.assertIn("shuttle3dCombatConfig", APPLICATIONS_INDEX_HTML)
        self.assertIn("shuttle3dPilotStationsConfig", APPLICATIONS_INDEX_HTML)
        self.assertIn("shuttle3dFlightConfig", APPLICATIONS_INDEX_HTML)
        self.assertIn("shuttle3dMotherShipInteriorConfig", APPLICATIONS_INDEX_HTML)
        self.assertIn("createFlightState()", APPLICATIONS_INDEX_HTML)
        self.assertIn("createShipState()", APPLICATIONS_INDEX_HTML)
        self.assertIn("this.flight = this.createFlightState()", APPLICATIONS_INDEX_HTML)
        self.assertIn("this.shipState = this.createShipState()", APPLICATIONS_INDEX_HTML)
        self.assertIn("pickPilotStation(clientX, clientY)", APPLICATIONS_INDEX_HTML)
        self.assertIn("setPilotMode(active", APPLICATIONS_INDEX_HTML)
        self.assertIn("firePhaser(nowMs", APPLICATIONS_INDEX_HTML)
        self.assertIn("spawnAlien(nowMs)", APPLICATIONS_INDEX_HTML)
        self.assertIn("scene-shuttle3d-health", APPLICATIONS_INDEX_HTML)
        self.assertIn("scene-shuttle3d-pilot-prompt", APPLICATIONS_INDEX_HTML)
        self.assertIn("console-hover-e-key", APPLICATIONS_INDEX_HTML)
        self.assertIn("appendFlightScene(builder", APPLICATIONS_INDEX_HTML)
        self.assertIn("flightDistance", APPLICATIONS_INDEX_HTML)
        self.assertIn("startDockingCutscene(nowMs", APPLICATIONS_INDEX_HTML)
        self.assertIn("appendDockingCutscene(builder", APPLICATIONS_INDEX_HTML)
        self.assertIn("appendShuttleBayScene(builder", APPLICATIONS_INDEX_HTML)
        self.assertIn("alternateSceneActive = dockingCutsceneActive || shuttleBaySceneActive", APPLICATIONS_INDEX_HTML)
        self.assertIn("FIRST-PERSON CONTROL", APPLICATIONS_INDEX_HTML)
        self.assertIn("dockingCutsceneActive", APPLICATIONS_INDEX_HTML)
        self.assertIn("playerExitedToBay", APPLICATIONS_INDEX_HTML)
        self.assertIn("enterShuttleBayPlayerControl(force", APPLICATIONS_INDEX_HTML)
        self.assertIn("isShuttleBayPlayerControlActive()", APPLICATIONS_INDEX_HTML)
        self.assertIn("shuttleBayControlActive", APPLICATIONS_INDEX_HTML)
        self.assertIn("forceShuttleBayControl()", APPLICATIONS_INDEX_HTML)
        self.assertIn("scene-shuttle3d-twiddle-system", APPLICATIONS_INDEX_HTML)
        self.assertIn("scene-shuttle3d-ship-line", APPLICATIONS_INDEX_HTML)
        self.assertIn("Shuttle Bay Twiddle System", APPLICATIONS_INDEX_HTML)
        self.assertIn("SHIP ${location}", APPLICATIONS_INDEX_HTML)
        self.assertIn("door.bay-access", APPLICATIONS_INDEX_HTML)
        self.assertIn("Starboard Interior Access", APPLICATIONS_INDEX_HTML)
        self.assertIn("enterBayOpsAccess()", APPLICATIONS_INDEX_HTML)
        self.assertIn("Press E to enter through", APPLICATIONS_INDEX_HTML)
        self.assertIn("door.bay-inner", APPLICATIONS_INDEX_HTML)
        self.assertIn("bridge.access", APPLICATIONS_INDEX_HTML)
        self.assertIn("bridge.deck", APPLICATIONS_INDEX_HTML)
        self.assertIn("Bridge Viewscreen", APPLICATIONS_INDEX_HTML)
        self.assertIn("appendBridgeViewscreenEnemy(builder, nowMs", APPLICATIONS_INDEX_HTML)
        self.assertIn("Bridge tactical lock engaged. Enemy raider is tracked on the main viewscreen.", APPLICATIONS_INDEX_HTML)
        self.assertIn("Bridge Tactical Console", APPLICATIONS_INDEX_HTML)
        self.assertIn("shuttle3dMotherShipInteriorStateDefaults()", APPLICATIONS_INDEX_HTML)
        self.assertIn("createShipStateFromDefaults()", APPLICATIONS_INDEX_HTML)
        self.assertIn("game.motherShipInterior.stateDefaults.v1", APPLICATIONS_INDEX_HTML)
        self.assertIn("shuttle3dMotherShipInteriorLevelDefaults()", APPLICATIONS_INDEX_HTML)
        self.assertIn("game.motherShipInterior.level.v1", APPLICATIONS_INDEX_HTML)
        self.assertIn("Patch C: mother-ship movement bounds now come from the level definition", APPLICATIONS_INDEX_HTML)
        self.assertIn("Patch D makes E-key targets data-driven", APPLICATIONS_INDEX_HTML)
        self.assertIn("shuttle3dNormalizeMotherShipInteractables", APPLICATIONS_INDEX_HTML)
        self.assertIn("performShipInteractionAction(target)", APPLICATIONS_INDEX_HTML)
        self.assertIn("Patch E formalizes action ids as registry entries", APPLICATIONS_INDEX_HTML)
        self.assertIn("shuttle3dNormalizeMotherShipInteractions", APPLICATIONS_INDEX_HTML)
        self.assertIn("createShipInteractionRegistry()", APPLICATIONS_INDEX_HTML)
        self.assertIn("createShipInteractionHandlerMap()", APPLICATIONS_INDEX_HTML)
        self.assertIn("No interaction handler registered", APPLICATIONS_INDEX_HTML)
        self.assertIn("Patch F validates definition reachability before content patches ship", APPLICATIONS_INDEX_HTML)
        self.assertIn("shuttle3dValidateMotherShipInteriorConfig", APPLICATIONS_INDEX_HTML)
        self.assertIn("shuttle3dNormalizeMotherShipValidationRules", APPLICATIONS_INDEX_HTML)
        self.assertIn("validationReport", APPLICATIONS_INDEX_HTML)
        self.assertIn("this.shipDefinitionValidation", APPLICATIONS_INDEX_HTML)
        self.assertIn("requireOpenDoors", APPLICATIONS_INDEX_HTML)
        self.assertIn("Patch G: keep renderer bootstrapping in named seams", APPLICATIONS_INDEX_HTML)
        self.assertIn("initializeRendererFrameState(scene)", APPLICATIONS_INDEX_HTML)
        self.assertIn("initializeGameplaySubsystems(scene)", APPLICATIONS_INDEX_HTML)
        self.assertIn("initializeCombatRuntimeState()", APPLICATIONS_INDEX_HTML)
        self.assertIn("initializeGeometryBuffers()", APPLICATIONS_INDEX_HTML)
        self.assertIn("initializeCanvasLifecycle(canvas)", APPLICATIONS_INDEX_HTML)
        self.assertIn("rendererSubsystems", APPLICATIONS_INDEX_HTML)
        self.assertIn("Patch H makes ship visual content data-first", APPLICATIONS_INDEX_HTML)
        self.assertIn("shuttle3dNormalizeMotherShipProps", APPLICATIONS_INDEX_HTML)
        self.assertIn("appendMotherShipInteriorProps(builder, nowMs)", APPLICATIONS_INDEX_HTML)
        self.assertIn("requireRenderableProps", APPLICATIONS_INDEX_HTML)
        self.assertIn("prop.bridge-tactical-marker", APPLICATIONS_INDEX_HTML)
        self.assertIn("prop.bridge-viewscreen-status", APPLICATIONS_INDEX_HTML)
        self.assertIn("Patch I also moves", APPLICATIONS_INDEX_HTML)
        self.assertIn('kind === "map-marker"', APPLICATIONS_INDEX_HTML)
        self.assertIn("prop.marker.bridge-viewscreen", APPLICATIONS_INDEX_HTML)
        self.assertIn("Patch J keeps data-defined visual content honest by validating prop targets", APPLICATIONS_INDEX_HTML)
        self.assertIn("requirePropTargets", APPLICATIONS_INDEX_HTML)
        self.assertIn("propTargetIsKnown", APPLICATIONS_INDEX_HTML)
        self.assertIn("targets missing content", APPLICATIONS_INDEX_HTML)
        self.assertIn("game-runtime-patch-J-prop-target-validation", APPLICATIONS_INDEX_HTML)
        self.assertIn('action: "fireBridgeTacticalConsole"', APPLICATIONS_INDEX_HTML)
        self.assertIn("shuttle3dNormalizeMotherShipRooms", APPLICATIONS_INDEX_HTML)
        self.assertIn("shuttle3dMovementBoundsFromRooms", APPLICATIONS_INDEX_HTML)
        self.assertIn("Patch B keeps the no-locked-door rule centralized", APPLICATIONS_INDEX_HTML)
        self.assertIn("fireBridgeTacticalConsole()", APPLICATIONS_INDEX_HTML)
        self.assertIn("objective.enemy-attack", APPLICATIONS_INDEX_HTML)
        self.assertIn("objective.enemy-disabled", APPLICATIONS_INDEX_HTML)
        self.assertIn("enemyShipHullPercent", APPLICATIONS_INDEX_HTML)
        self.assertIn("Bridge tactical console fired", APPLICATIONS_INDEX_HTML)
        self.assertIn('setShipTerminalState("terminal.bridge-viewscreen", "tracking")', APPLICATIONS_INDEX_HTML)
        self.assertIn("objective.enemy-track", APPLICATIONS_INDEX_HTML)
        self.assertIn("bridgeViewscreenTrackingActive", APPLICATIONS_INDEX_HTML)
        self.assertIn('nextLocation === "bridge.deck"', APPLICATIONS_INDEX_HTML)
        self.assertIn("Door state is informational only", APPLICATIONS_INDEX_HTML)
        self.assertIn("No door lock is required", APPLICATIONS_INDEX_HTML)
        self.assertIn("shipInteractionTarget()", APPLICATIONS_INDEX_HTML)
        self.assertIn("interactWithShip()", APPLICATIONS_INDEX_HTML)
        self.assertIn("Engineering Power Console", APPLICATIONS_INDEX_HTML)
        self.assertIn("motherShipWalkableRegions()", APPLICATIONS_INDEX_HTML)
        self.assertIn("Keep the access vestibule, visible corridor, and walkable bounds aligned", APPLICATIONS_INDEX_HTML)
        self.assertIn("Bay Ops interior transit spine", APPLICATIONS_INDEX_HTML)
        self.assertIn("zone.location && zone.location !== activeLocation", APPLICATIONS_INDEX_HTML)
        self.assertIn("twiddleSystem.hidden = !(pilot.dockingCutsceneActive || (!pilot.shuttleBayControlActive", APPLICATIONS_INDEX_HTML)
        self.assertIn('event.code === "KeyT"', APPLICATIONS_INDEX_HTML)
        self.assertIn("const bayLookConfig = shuttle3dCameraConfig(scene)", APPLICATIONS_INDEX_HTML)
        self.assertIn("Shuttle bay control handoff callback failed", APPLICATIONS_INDEX_HTML)
        self.assertNotIn("setShuttle3dLook(container, bay.yaw, bay.pitch, config);", APPLICATIONS_INDEX_HTML)
        self.assertIn("W/A/S/D to walk the", APPLICATIONS_INDEX_HTML)
        self.assertIn("Face into the mother ship and toward the starboard/right side of the bay.", APPLICATIONS_INDEX_HTML)
        self.assertIn("yaw: 32", APPLICATIONS_INDEX_HTML)
        self.assertIn("pitch: -4", APPLICATIONS_INDEX_HTML)
        self.assertIn("Mother Ship Shuttle Bay", APPLICATIONS_INDEX_HTML)
        self.assertIn("setMovementKey(code, active)", APPLICATIONS_INDEX_HTML)
        self.assertIn("updateMovement(deltaSeconds)", APPLICATIONS_INDEX_HTML)
        self.assertIn('movementCodes = new Set(["KeyW", "KeyA", "KeyS", "KeyD"', APPLICATIONS_INDEX_HTML)
        self.assertIn('container.addEventListener("keyup", keyUp)', APPLICATIONS_INDEX_HTML)
        self.assertIn('window.addEventListener("blur", blur)', APPLICATIONS_INDEX_HTML)
        self.assertIn("W/A/S/D", APPLICATIONS_INDEX_HTML)
        self.assertIn("enableClickMovement", APPLICATIONS_INDEX_HTML)
        self.assertIn("screenPointToIsoWorld", APPLICATIONS_INDEX_HTML)
        self.assertIn("scene-movement-marker", APPLICATIONS_INDEX_HTML)
        self.assertIn("W/A/S/D to walk", APPLICATIONS_INDEX_HTML)
        self.assertIn("removeEventListener(\"pointerdown\", container.__mainComputerClickMovementHandler)", APPLICATIONS_INDEX_HTML)
        self.assertIn("startSceneMovement", APPLICATIONS_INDEX_HTML)
        self.assertIn("movementSpeed(scene)", APPLICATIONS_INDEX_HTML)
        self.assertIn("emitterProjectionState(object, scene, projected)", APPLICATIONS_INDEX_HTML)
        self.assertIn("updateEmitter(object, scene, projected)", APPLICATIONS_INDEX_HTML)
        self.assertIn("bufferSubData(", APPLICATIONS_INDEX_HTML)
        self.assertNotIn("scene-click-move", APPLICATIONS_INDEX_HTML)
        self.assertNotIn("player-capsule", APPLICATIONS_INDEX_HTML)
        self.assertNotIn("mesh-actor", APPLICATIONS_INDEX_HTML)
        self.assertIn('id="webgl-demo"', APPLICATIONS_INDEX_HTML)
        self.assertIn('aria-label="Scene-aware game surface"', APPLICATIONS_INDEX_HTML)
        self.assertIn('data-scene-id="default-empty-scene"', APPLICATIONS_INDEX_HTML)

    def test_game_surface_uses_shared_scene_viewer_not_engine_runtime(self) -> None:
        self.assertIn("function initWebgl(", APPLICATIONS_INDEX_HTML)
        self.assertIn("MainComputerSceneStore", APPLICATIONS_INDEX_HTML)
        self.assertIn("MainComputerSceneViewer", APPLICATIONS_INDEX_HTML)
        self.assertIn("sceneWebglShader", APPLICATIONS_INDEX_HTML)
        self.assertIn("sceneWebglProgram", APPLICATIONS_INDEX_HTML)
        self.assertNotIn("MainComputerBabylonPreview", APPLICATIONS_INDEX_HTML)
        self.assertNotIn("BABYLON", APPLICATIONS_INDEX_HTML)
        self.assertNotIn("MeshBuilder", APPLICATIONS_INDEX_HTML)
        self.assertNotIn("SceneLoader", APPLICATIONS_INDEX_HTML)


if __name__ == "__main__":
    unittest.main()
