"""Install a Windows command shim for the Main Computer CLI.

Pip's unsigned console-script ``main-computer.exe`` is blocked by Windows
Smart App Control on developer machines.  Keep the normal CLI command by
using the already-working virtualenv Python rather than that executable.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path


LAUNCHER = """@echo off
rem Main Computer CLI -- generated by main_computer.bootstrap.windows_cmd_launcher
"%~dp0python.exe" -m main_computer.cli %*
exit /b %ERRORLEVEL%
"""


def install_windows_cmd_launcher(venv_python: Path) -> Path:
    """Install the Windows .cmd in the *given virtualenv*, not on the PATH.

    The conflicting .exe is removed only after the new .cmd is in place. This
    must run after each pip install, since pip regenerates the .exe.
    """
    venv_python = Path(venv_python)
    if venv_python.name.lower() != "python.exe" or venv_python.parent.name.lower() != "scripts":
        raise ValueError(f"Expected a Windows virtualenv Scripts/python.exe: {venv_python}")
    if not venv_python.is_file():
        raise FileNotFoundError(f"Virtualenv Python does not exist: {venv_python}")

    scripts_dir = venv_python.parent
    cmd_path = scripts_dir / "main-computer.cmd"
    exe_path = scripts_dir / "main-computer.exe"
    if exe_path.is_symlink():
        raise RuntimeError(f"Refusing to remove a symlinked CLI executable: {exe_path}")
    if cmd_path.is_symlink():
        raise RuntimeError(f"Refusing to overwrite a symlinked CLI command: {cmd_path}")

    # Atomic installation avoids leaving a truncated launcher on interruption.
    pending_path = scripts_dir / "main-computer.cmd.tmp"
    try:
        with pending_path.open("w", encoding="utf-8", newline="\r\n") as output:
            output.write(LAUNCHER)
        os.replace(pending_path, cmd_path)
    finally:
        pending_path.unlink(missing_ok=True)

    # cmd.exe will choose the .exe first if it remains in Scripts.  Only
    # remove the pip-generated launcher for this exact virtual environment.
    if exe_path.exists():
        if not exe_path.is_file():
            raise RuntimeError(f"Expected a file, not a directory: {exe_path}")
        exe_path.unlink()

    print(f"Main Computer CLI: {cmd_path}", flush=True)
    return cmd_path


def main() -> int:
    if os.name != "nt":
        raise SystemExit("This launcher is only for Windows virtual environments.")
    install_windows_cmd_launcher(Path(sys.executable))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
