// Generated by Main Computer Blog install.
// The deployed site server resolves DIRECTUS_URL from runtime env.
// Browser-side code should call the site /blog routes unless an explicit
// preview/session boundary is added later.
import { blogRuntimeConfig } from "./runtime-config.js";

export function directusPostsQuery(slug = "") {
  const params = new URLSearchParams();
  params.set("fields", blogRuntimeConfig.publicFields.join(","));
  params.set("sort", "-published_on,-id");
  params.set("filter[status][_eq]", "published");
  if (slug) params.set("filter[slug][_eq]", slug);
  return `/items/${blogRuntimeConfig.collection}?${params.toString()}`;
}

export async function listPublishedPosts(fetchJson) {
  const payload = await fetchJson(directusPostsQuery());
  return Array.isArray(payload?.data) ? payload.data : [];
}

export async function getPublishedPostBySlug(fetchJson, slug) {
  const payload = await fetchJson(directusPostsQuery(slug));
  const rows = Array.isArray(payload?.data) ? payload.data : [];
  return rows[0] || null;
}
