// Generated by Main Computer Blog install.
// No secrets belong in this client-visible file.
export const blogRuntimeConfig = {
  provider: "directus",
  contentRuntime: "deployed",
  collection: "posts",
  routes: {
    index: "/blog",
    post: "/blog/:slug"
  },
  publicFields: [
    "id",
    "status",
    "slug",
    "title",
    "excerpt",
    "body",
    "published_on",
    "read_time_minutes",
    "is_legacy"
  ],
  publishedFilter: {
    status: "published"
  }
};
