// Generated by Main Computer Blog install.
import { listPublishedPosts } from "../content/directus-client.js";

export async function listBlogPosts(fetchJson) {
  return listPublishedPosts(fetchJson);
}
