#!/usr/bin/env python3
"""API-only stress smoke for Mother's temporary static-node writer pathway.

This live diagnostic intentionally reproduces the boundary exercised by
``tools/mother_bootnode_precleanup.py`` without SSH, SCP, host-shell access, or
local Docker access.

Each iteration uses only the configured Coolify HTTP API to:

1. create a disposable target service on the selected controller;
2. wait until its target container is materialized;
3. create a separate long-lived observer service that watches Docker state and
   proof files for the uniquely named writer container;
4. create the exact production ``docker:27-cli`` writer compose generated by
   ``mother_bootnode_precleanup._writer_service_compose`` without modifying it;
5. start the writer through ``POST /api/v1/services/<uuid>/start``;
6. poll service/application state and capture runtime logs, deployment matches,
   server-resource matches, and observer evidence on failure;
7. verify the write through an API-visible verifier sidecar sharing the target
   volume; and
8. delete successful disposable services.

On the first failure, diagnostic evidence is captured before deletion and the
failed writer, observer, and target are preserved by default.
"""

from __future__ import annotations

import argparse
import base64
from datetime import datetime, timezone
import hashlib
import json
import os
from pathlib import Path
import re
import sys
import time
from typing import Any, Callable, Mapping, Sequence
import urllib.parse
import urllib.request

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

import tools.mother_bootnode_precleanup as bootnode
from tools.mother.common import deployment_coolify_service_lifecycle_probe as lifecycle


KIND = "main_computer.mother.static_node_writer_stress_smoke.v3"
EVIDENCE_SUBDIR = "mother-static-node-writer-stress-smoke"
TARGET_IMAGE = "alpine:3.20"
DEFAULT_ITERATIONS = 20
DEFAULT_TARGET_WAIT_SECONDS = 60.0
DEFAULT_WRITER_WAIT_SECONDS = 120.0
DEFAULT_VERIFY_WAIT_SECONDS = 30.0
DEFAULT_POLL_INTERVAL_SECONDS = 2.0
VERIFY_LOG_MARKER = "MOTHER_STATIC_NODE_SHA256="
OBSERVER_LOG_MARKER = "MOTHER_WRITER_STRESS_OBSERVER"
_SAFE_NAME = re.compile(r"^[a-z0-9][a-z0-9-]{0,62}$")


class WriterStressSmokeError(RuntimeError):
    pass


def _utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _stamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ").lower()


def _name(value: str, label: str) -> str:
    if _SAFE_NAME.fullmatch(value) is None:
        raise WriterStressSmokeError(f"{label} must match {_SAFE_NAME.pattern}")
    return value


def _iteration_name(prefix: str, iteration: int) -> str:
    suffix = f"{_stamp()}-{iteration:03d}"
    room = 63 - len(suffix) - 1
    base = prefix[:room].rstrip("-")
    return _name(f"{base}-{suffix}", "generated service name")


def _atomic_write_json(path: Path, value: Mapping[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    os.replace(tmp, path)


def _stress_static_nodes(iteration: int) -> list[str]:
    first = f"{iteration:0128x}"[-128:]
    second = f"{iteration + 1:0128x}"[-128:]
    return [
        f"enode://{first}@10.255.0.2:30303",
        f"enode://{second}@10.255.0.3:30304",
    ]


def _build_action(*, iteration: int, target_container: str, controller_id: str) -> dict[str, Any]:
    static_nodes = _stress_static_nodes(iteration)
    payload = bootnode._static_nodes_json(static_nodes)
    return {
        "action": "write-static-nodes",
        "node": f"writer-stress-{iteration}",
        "controller_id": controller_id,
        "container_name": target_container,
        "path": bootnode.STATIC_NODES_PATH,
        "static_nodes": static_nodes,
        "static_node_count": len(static_nodes),
        "static_nodes_sha256": hashlib.sha256(payload).hexdigest(),
        "peer_nodes": [f"stress-peer-{iteration}-a", f"stress-peer-{iteration}-b"],
        "survivor_count": 3,
    }


def _verifier_name(target_service_name: str) -> str:
    return _name((target_service_name[:53] + "-verify").rstrip("-"), "verifier_name")


def _target_compose(
    *,
    target_service_name: str,
    target_container: str,
    expected_sha256: str,
) -> str:
    target_service_name = _name(target_service_name, "target_service_name")
    target_container = _name(target_container, "target_container")
    verifier_name = _verifier_name(target_service_name)
    label = "main_computer.mother.component"
    verifier_command = (
        "set -eu; "
        "while true; do "
        "if test -f /var/lib/besu/static-nodes.json; then "
        "set -- $(sha256sum /var/lib/besu/static-nodes.json); "
        f'echo "{VERIFY_LOG_MARKER}$1"; '
        "else "
        f'echo "{VERIFY_LOG_MARKER}missing"; '
        "fi; "
        "sleep 1; "
        "done"
    )
    compose = {
        "services": {
            target_service_name: {
                "image": TARGET_IMAGE,
                "container_name": target_container,
                "command": [
                    "sh",
                    "-lc",
                    "set -eu; mkdir -p /var/lib/besu; while true; do sleep 3600; done",
                ],
                "restart": "no",
                "volumes": ["data:/var/lib/besu"],
                "labels": {
                    label: "static-node-writer-stress-target",
                    "main_computer.mother.not_a_validator": "true",
                    "main_computer.mother.not_a_chain_service": "true",
                },
                "healthcheck": {
                    "test": ["CMD-SHELL", "test -d /var/lib/besu"],
                    "interval": "2s",
                    "timeout": "1s",
                    "retries": 30,
                    "start_period": "1s",
                },
            },
            verifier_name: {
                "image": TARGET_IMAGE,
                "command": ["sh", "-lc", verifier_command],
                "restart": "no",
                "volumes": ["data:/var/lib/besu:ro"],
                "labels": {
                    label: "static-node-writer-stress-verifier",
                    "main_computer.mother.not_a_validator": "true",
                    "main_computer.mother.not_a_chain_service": "true",
                },
                "healthcheck": {
                    "test": ["CMD-SHELL", "test -d /var/lib/besu"],
                    "interval": "2s",
                    "timeout": "1s",
                    "retries": 30,
                    "start_period": "1s",
                },
            },
        },
        "volumes": {"data": {}},
    }
    return yaml.safe_dump(compose, sort_keys=False)



def _observer_script(writer_service_name: str) -> str:
    writer_service_name = _name(writer_service_name, "writer_service_name")
    marker = OBSERVER_LOG_MARKER
    lines = [
        "set -u",
        f"marker={bootnode._single_quote(marker)}",
        f"writer_service={bootnode._single_quote(writer_service_name)}",
        "last_state_key=''",
        'emit_file() {',
        '  label="$1"',
        '  path="$2"',
        '  tmp="/tmp/mother-writer-observer-$$-$label"',
        '  rm -f "$tmp"',
        '  if docker cp "$cid:$path" "$tmp" >/dev/null 2>&1; then',
        '    content_b64="$(base64 "$tmp" 2>/dev/null | tr -d \'\\n\' || true)"',
        '    printf \'%s phase=proof file=%s content_b64=%s\\n\' "$marker" "$label" "$content_b64"',
        '    rm -f "$tmp"',
        '  fi',
        '}',
        'printf \'%s phase=observer-start writer_service=%s\\n\' "$marker" "$writer_service"',
        "while true; do",
        '  cid="$(docker ps -aq --filter "label=com.docker.compose.service=$writer_service" 2>/dev/null | head -n 1 || true)"',
        '  if [ -z "$cid" ]; then',
        '    if [ "$last_state_key" != "missing" ]; then',
        '      printf \'%s phase=writer-container-missing writer_service=%s\\n\' "$marker" "$writer_service"',
        '      last_state_key="missing"',
        '    fi',
        '    sleep 1',
        '    continue',
        '  fi',
        '  state="$(docker inspect -f \'{{.State.Status}}\' "$cid" 2>/dev/null || true)"',
        '  exit_code="$(docker inspect -f \'{{.State.ExitCode}}\' "$cid" 2>/dev/null || true)"',
        '  oom_killed="$(docker inspect -f \'{{.State.OOMKilled}}\' "$cid" 2>/dev/null || true)"',
        '  state_json="$(docker inspect -f \'{{json .State}}\' "$cid" 2>/dev/null || true)"',
        '  state_b64="$(printf \'%s\' "$state_json" | base64 2>/dev/null | tr -d \'\\n\' || true)"',
        '  state_key="$cid|$state|$exit_code|$oom_killed"',
        '  if [ "$state_key" != "$last_state_key" ]; then',
        '    printf \'%s phase=writer-state cid=%s status=%s exit_code=%s oom_killed=%s state_b64=%s\\n\' "$marker" "$cid" "$state" "$exit_code" "$oom_killed" "$state_b64"',
        '    logs_b64="$(docker logs "$cid" 2>&1 | tail -n 300 | base64 2>/dev/null | tr -d \'\\n\' || true)"',
        '    printf \'%s phase=writer-logs cid=%s content_b64=%s\\n\' "$marker" "$cid" "$logs_b64"',
        '    emit_file result.json /proof/result.json',
        '    emit_file failed.json /proof/failed.json',
        '    emit_file docker-stderr.txt /proof/docker-stderr.txt',
        '    emit_file docker-stdout.txt /proof/docker-stdout.txt',
        '    if docker cp "$cid:/proof/healthy" "/tmp/mother-writer-observer-$$-healthy" >/dev/null 2>&1; then',
        '      printf \'%s phase=proof file=healthy content_b64=\\n\' "$marker"',
        '      rm -f "/tmp/mother-writer-observer-$$-healthy"',
        '    fi',
        '    last_state_key="$state_key"',
        '  fi',
        '  sleep 1',
        "done",
        "",
    ]
    return "\n".join(lines)


def _observer_compose(*, observer_service_name: str, writer_service_name: str) -> str:
    observer_service_name = _name(observer_service_name, "observer_service_name")
    script = bootnode._escape_docker_compose_interpolation(
        _observer_script(writer_service_name)
    )
    compose = {
        "services": {
            observer_service_name: {
                "image": bootnode.WRITER_IMAGE,
                "command": ["sh", "-lc", script],
                "restart": "no",
                "volumes": ["/var/run/docker.sock:/var/run/docker.sock"],
                "labels": {
                    "main_computer.mother.component": "static-node-writer-stress-observer",
                    "main_computer.mother.not_a_validator": "true",
                    "main_computer.mother.not_a_chain_service": "true",
                },
                "healthcheck": {
                    "test": ["CMD-SHELL", "test -S /var/run/docker.sock"],
                    "interval": "2s",
                    "timeout": "1s",
                    "retries": 30,
                    "start_period": "1s",
                },
            }
        }
    }
    return yaml.safe_dump(compose, sort_keys=False)


def _decode_observer_b64(value: str | None) -> str | None:
    if not value:
        return None
    try:
        return base64.b64decode(value.encode("ascii"), validate=False).decode(
            "utf-8",
            errors="replace",
        )
    except Exception:
        return None


def _observer_log_text(runtime_logs: Mapping[str, Any]) -> str:
    chunks: list[str] = []
    for attempt in runtime_logs.get("attempts") or []:
        if not isinstance(attempt, Mapping):
            continue
        logs = attempt.get("logs")
        if isinstance(logs, str) and logs:
            chunks.append(logs)
    return "\n".join(chunks)


def _parse_observer_logs(logs_text: str) -> dict[str, Any]:
    events: list[dict[str, Any]] = []
    proof_files: dict[str, str] = {}
    writer_logs: list[str] = []
    for raw_line in logs_text.splitlines():
        marker_at = raw_line.find(OBSERVER_LOG_MARKER)
        if marker_at < 0:
            continue
        line = raw_line[marker_at:]
        fields: dict[str, str] = {}
        for token in line.split()[1:]:
            if "=" not in token:
                continue
            key, value = token.split("=", 1)
            fields[key] = value
        if not fields:
            continue
        event: dict[str, Any] = dict(fields)
        if "state_b64" in fields:
            event["state_json"] = _decode_observer_b64(fields.get("state_b64"))
        if fields.get("phase") == "writer-logs":
            decoded = _decode_observer_b64(fields.get("content_b64"))
            event["content"] = decoded
            if decoded is not None:
                writer_logs.append(decoded)
        if fields.get("phase") == "proof":
            file_name = fields.get("file")
            decoded = _decode_observer_b64(fields.get("content_b64"))
            event["content"] = decoded
            if file_name and decoded is not None:
                proof_files[file_name] = decoded
        events.append(event)
    return {
        "events": events,
        "proof_files": proof_files,
        "writer_logs": writer_logs,
    }


def _capture_observer(
    *,
    controller: Any,
    service_uuid: str,
    service_name: str,
    timeout: float,
    max_response_bytes: int,
    opener: Any,
    reason: str,
) -> dict[str, Any]:
    response, snapshot = _detail(
        controller=controller,
        service_uuid=service_uuid,
        service_name=service_name,
        timeout=timeout,
        max_response_bytes=max_response_bytes,
        opener=opener,
        label=f"stress-observer-{reason}",
    )
    runtime_logs = _runtime_logs(
        controller=controller,
        service_uuid=service_uuid,
        service_name=service_name,
        service_detail_payload=response.get("payload"),
        timeout=timeout,
        max_response_bytes=max_response_bytes,
        opener=opener,
        application_name=service_name,
    )
    logs_text = _observer_log_text(runtime_logs)
    return {
        "captured_at": _utc_now(),
        "reason": reason,
        "service_uuid": service_uuid,
        "service_name": service_name,
        "service_detail_snapshot": snapshot,
        "runtime_logs": runtime_logs,
        "parsed": _parse_observer_logs(logs_text),
    }


def _service_body(
    controller_config: Mapping[str, Any],
    *,
    network: str,
    environment_uuid: str,
    name: str,
    compose: str,
    description: str,
) -> dict[str, Any]:
    body = bootnode._temporary_service_body(
        controller_config,
        network=network,
        name=name,
        compose=compose,
    )
    body["environment_uuid"] = environment_uuid
    body["description"] = description
    return body


def _http(
    controller: Any,
    method: str,
    endpoint: str,
    *,
    body: Mapping[str, Any] | None,
    timeout: float,
    max_response_bytes: int,
    opener: Any,
) -> dict[str, Any]:
    return bootnode._coolify_http(
        controller,
        method,
        endpoint,
        body=body,
        timeout=timeout,
        max_response_bytes=max_response_bytes,
        opener=opener,
    )


def _receipt(
    response: Mapping[str, Any],
    *,
    method: str,
    endpoint: str,
    service_uuid: str | None = None,
    service_name: str | None = None,
) -> dict[str, Any]:
    result = {
        "method": method,
        "endpoint": endpoint,
        "status": response.get("status"),
        "ok": response.get("ok"),
        "response_sha256": response.get("response_sha256"),
        "byte_length": response.get("byte_length"),
        "elapsed_ms": response.get("elapsed_ms"),
        "payload_summary": bootnode._safe_payload_summary(response.get("payload")),
    }
    if service_uuid:
        result["service_uuid"] = service_uuid
    if service_name:
        result["service_name"] = service_name
    return result


def _create_service(
    *,
    controller: Any,
    body: Mapping[str, Any],
    timeout: float,
    max_response_bytes: int,
    opener: Any,
) -> tuple[str | None, dict[str, Any]]:
    response = _http(
        controller,
        "POST",
        "/api/v1/services",
        body=body,
        timeout=timeout,
        max_response_bytes=max_response_bytes,
        opener=opener,
    )
    receipt = _receipt(
        response,
        method="POST",
        endpoint="/api/v1/services",
        service_name=str(body.get("name") or ""),
    )
    if response.get("ok") is not True:
        return None, receipt
    service_uuid = bootnode._application_uuid(response.get("payload"))
    receipt["service_uuid"] = service_uuid
    return service_uuid, receipt


def _start_service(
    *,
    controller: Any,
    service_uuid: str,
    service_name: str,
    timeout: float,
    max_response_bytes: int,
    opener: Any,
) -> dict[str, Any]:
    endpoint = f"/api/v1/services/{urllib.parse.quote(service_uuid, safe='')}/start"
    response = _http(
        controller,
        "POST",
        endpoint,
        body=None,
        timeout=timeout,
        max_response_bytes=max_response_bytes,
        opener=opener,
    )
    return _receipt(
        response,
        method="POST",
        endpoint=endpoint,
        service_uuid=service_uuid,
        service_name=service_name,
    )


def _delete_service(
    *,
    controller: Any,
    service_uuid: str,
    service_name: str,
    timeout: float,
    max_response_bytes: int,
    opener: Any,
) -> dict[str, Any]:
    endpoint = f"/api/v1/services/{urllib.parse.quote(service_uuid, safe='')}"
    response = _http(
        controller,
        "DELETE",
        endpoint,
        body=None,
        timeout=timeout,
        max_response_bytes=max_response_bytes,
        opener=opener,
    )
    return _receipt(
        response,
        method="DELETE",
        endpoint=endpoint,
        service_uuid=service_uuid,
        service_name=service_name,
    )


def _detail(
    *,
    controller: Any,
    service_uuid: str,
    service_name: str,
    timeout: float,
    max_response_bytes: int,
    opener: Any,
    label: str,
) -> tuple[dict[str, Any], dict[str, Any]]:
    endpoint = f"/api/v1/services/{urllib.parse.quote(service_uuid, safe='')}"
    response = _http(
        controller,
        "GET",
        endpoint,
        body=None,
        timeout=timeout,
        max_response_bytes=max_response_bytes,
        opener=opener,
    )
    snapshot = bootnode._writer_service_detail_snapshot(
        label,
        response,
        service_uuid=service_uuid,
        service_name=service_name,
    )
    return response, snapshot


def _record_statuses(snapshot: Mapping[str, Any]) -> list[str]:
    values: list[str] = []
    for record in snapshot.get("service_records") or []:
        if not isinstance(record, Mapping):
            continue
        for key in ("status", "human_status", "humanized_status", "application_status", "health_status"):
            value = record.get(key)
            if isinstance(value, str) and value.strip():
                values.append(value.strip().lower())
    return values


def _record_running(record: Mapping[str, Any]) -> bool:
    for key in ("status", "human_status", "humanized_status", "application_status", "health_status"):
        value = record.get(key)
        if isinstance(value, str) and value.strip().lower().startswith("running"):
            return True
    return False


def _application_record(
    snapshot: Mapping[str, Any],
    application_name: str,
) -> Mapping[str, Any] | None:
    for record in snapshot.get("service_records") or []:
        if not isinstance(record, Mapping):
            continue
        path = str(record.get("path") or "")
        if not path.startswith("$.applications["):
            continue
        if record.get("name") == application_name:
            return record
    return None


def _target_materialized(snapshot: Mapping[str, Any], target_service_name: str) -> bool:
    record = _application_record(snapshot, target_service_name)
    return bool(record and _record_running(record))


def _container_name_from_finalized_compose(
    payload: Any,
    *,
    target_service_name: str,
) -> str | None:
    """Resolve the Docker container name from Coolify's finalized compose only."""
    if not isinstance(payload, Mapping):
        return None
    finalized = payload.get("docker_compose")
    if isinstance(finalized, str):
        try:
            parsed = yaml.safe_load(finalized)
        except yaml.YAMLError:
            return None
    elif isinstance(finalized, Mapping):
        parsed = finalized
    else:
        return None
    if not isinstance(parsed, Mapping):
        return None
    services = parsed.get("services")
    if not isinstance(services, Mapping):
        return None
    service = services.get(target_service_name)
    if not isinstance(service, Mapping):
        return None
    value = service.get("container_name")
    if not isinstance(value, str):
        return None
    value = value.strip()
    if not value:
        return None
    return value


def _resolve_finalized_target_container(
    *,
    controller: Any,
    service_uuid: str,
    service_name: str,
    timeout: float,
    max_response_bytes: int,
    opener: Any,
) -> tuple[str | None, dict[str, Any]]:
    endpoint = f"/api/v1/services/{urllib.parse.quote(service_uuid, safe='')}"
    response = _http(
        controller,
        "GET",
        endpoint,
        body=None,
        timeout=timeout,
        max_response_bytes=max_response_bytes,
        opener=opener,
    )
    receipt = _receipt(
        response,
        method="GET",
        endpoint=endpoint,
        service_uuid=service_uuid,
        service_name=service_name,
    )
    container_name = None
    if response.get("ok") is True:
        container_name = _container_name_from_finalized_compose(
            response.get("payload"),
            target_service_name=service_name,
        )
    receipt["container_name"] = container_name
    finalized = response.get("payload")
    if isinstance(finalized, Mapping):
        compose = finalized.get("docker_compose")
        if isinstance(compose, str):
            receipt["finalized_compose_sha256"] = hashlib.sha256(
                compose.encode("utf-8")
            ).hexdigest()
    return container_name, receipt


def _logs_excerpt(value: Any, *, limit: int = 24000) -> str | None:
    if not isinstance(value, str):
        return None
    if len(value) <= limit:
        return value
    half = limit // 2
    return value[:half] + "\n...<truncated>...\n" + value[-half:]


def _runtime_logs(
    *,
    controller: Any,
    service_uuid: str,
    service_name: str,
    service_detail_payload: Any,
    timeout: float,
    max_response_bytes: int,
    opener: Any,
    application_name: str | None = None,
) -> dict[str, Any]:
    expected_application_name = application_name or service_name
    diagnostics = lifecycle._service_subresource_diagnostics(
        service_detail_payload,
        expected_application_name,
    )
    sub_service_name = diagnostics.get("selected_sub_service_name")
    application_uuid = diagnostics.get("selected_application_uuid")
    candidates: list[tuple[str, str]] = []
    if isinstance(application_uuid, str) and application_uuid:
        quoted_service = urllib.parse.quote(service_uuid, safe="")
        quoted_application = urllib.parse.quote(application_uuid, safe="")
        candidates.extend(
            [
                (
                    "service-application",
                    f"/api/v1/services/{quoted_service}/applications/{quoted_application}/logs?lines=300&show_timestamps=true",
                ),
                (
                    "application-resource",
                    f"/api/v1/applications/{quoted_application}/logs?lines=300",
                ),
            ]
        )
    if isinstance(sub_service_name, str) and sub_service_name:
        candidates.append(
            (
                "parent-service",
                f"/api/v1/services/{urllib.parse.quote(service_uuid, safe='')}/logs"
                f"?sub_service_name={urllib.parse.quote(sub_service_name, safe='')}"
                "&lines=300&show_timestamps=true",
            )
        )

    attempts: list[dict[str, Any]] = []
    for kind, endpoint in candidates:
        response = _http(
            controller,
            "GET",
            endpoint,
            body=None,
            timeout=timeout,
            max_response_bytes=max_response_bytes,
            opener=opener,
        )
        payload = response.get("payload")
        logs = payload.get("logs") if isinstance(payload, Mapping) else None
        item = _receipt(response, method="GET", endpoint=endpoint)
        item["endpoint_kind"] = kind
        item["logs"] = _logs_excerpt(logs)
        attempts.append(item)
        if response.get("status") == 200:
            break

    return {
        "expected_application_name": expected_application_name,
        "selected_sub_service_name": sub_service_name,
        "selected_application_uuid": application_uuid,
        "attempts": attempts,
    }


def _matching_inventory(
    *,
    controller: Any,
    controller_meta: Mapping[str, Any],
    service_uuid: str,
    service_name: str,
    timeout: float,
    max_response_bytes: int,
    opener: Any,
) -> list[dict[str, Any]]:
    observations: list[dict[str, Any]] = []
    for channel, endpoint in (
        ("deployments", "/api/v1/deployments"),
        ("server-resources", f"/api/v1/servers/{controller_meta['server_uuid']}/resources"),
    ):
        response = _http(
            controller,
            "GET",
            endpoint,
            body=None,
            timeout=timeout,
            max_response_bytes=max_response_bytes,
            opener=opener,
        )
        observations.append(
            {
                "channel": channel,
                **_receipt(response, method="GET", endpoint=endpoint),
                "matches": lifecycle._matching_records(
                    response.get("payload"),
                    service_uuid,
                    service_name,
                ),
            }
        )
    return observations


def _capture_diagnostics(
    *,
    controller: Any,
    controller_id: str,
    controller_meta: Mapping[str, Any],
    service_uuid: str,
    service_name: str,
    timeout: float,
    max_response_bytes: int,
    opener: Any,
    reason: str,
) -> dict[str, Any]:
    response, snapshot = _detail(
        controller=controller,
        service_uuid=service_uuid,
        service_name=service_name,
        timeout=timeout,
        max_response_bytes=max_response_bytes,
        opener=opener,
        label=f"stress-{reason}",
    )
    return {
        "captured_at": _utc_now(),
        "reason": reason,
        "controller_id": controller_id,
        "service_uuid": service_uuid,
        "service_name": service_name,
        "service_detail_snapshot": snapshot,
        "runtime_logs": _runtime_logs(
            controller=controller,
            service_uuid=service_uuid,
            service_name=service_name,
            service_detail_payload=response.get("payload"),
            timeout=timeout,
            max_response_bytes=max_response_bytes,
            opener=opener,
        ),
        "inventory": _matching_inventory(
            controller=controller,
            controller_meta=controller_meta,
            service_uuid=service_uuid,
            service_name=service_name,
            timeout=timeout,
            max_response_bytes=max_response_bytes,
            opener=opener,
        ),
    }


def _status_signature(snapshot: Mapping[str, Any]) -> tuple[str, tuple[str, ...]]:
    return (
        str(snapshot.get("service_status") or "").lower(),
        tuple(sorted(set(_record_statuses(snapshot)))),
    )


def _failure_signature(
    polls: Sequence[Mapping[str, Any]],
    diagnostics: Sequence[Mapping[str, Any]] = (),
) -> dict[str, Any]:
    service_statuses = [
        str(item.get("service_status") or "").lower()
        for item in polls
    ]
    diagnostic_service_statuses: list[str] = []
    for diagnostic in diagnostics:
        if not isinstance(diagnostic, Mapping):
            continue
        for inventory in diagnostic.get("inventory") or []:
            if not isinstance(inventory, Mapping):
                continue
            for match in inventory.get("matches") or []:
                if not isinstance(match, Mapping):
                    continue
                value = match.get("status")
                if isinstance(value, str) and value:
                    diagnostic_service_statuses.append(value.lower())

    application_statuses: list[str] = []
    for item in polls:
        snapshot = item.get("service_detail_snapshot")
        if not isinstance(snapshot, Mapping):
            continue
        for record in snapshot.get("service_records") or []:
            if not isinstance(record, Mapping):
                continue
            if str(record.get("image") or record.get("docker_image") or "") != bootnode.WRITER_IMAGE:
                continue
            for key in ("status", "human_status", "humanized_status", "application_status", "health_status"):
                value = record.get(key)
                if isinstance(value, str) and value:
                    application_statuses.append(value.lower())

    all_service_statuses = service_statuses + diagnostic_service_statuses
    saw_healthy = any(bootnode._healthy_status(value) for value in service_statuses)
    saw_starting_unhealthy = any(
        "starting:unhealthy" in value for value in all_service_statuses
    )
    saw_application_exited = any(value == "exited" for value in application_statuses)
    saw_application_running = any(value.startswith("running") for value in application_statuses)
    return {
        "service_statuses": service_statuses,
        "diagnostic_service_statuses": diagnostic_service_statuses,
        "application_statuses": application_statuses,
        "saw_starting_unhealthy": saw_starting_unhealthy,
        "saw_application_exited": saw_application_exited,
        "saw_application_running": saw_application_running,
        "saw_running_healthy": saw_healthy,
        "matches_observed_incident": (
            saw_starting_unhealthy
            and saw_application_exited
            and not saw_application_running
            and not saw_healthy
        ),
    }

def _wait_for_target_materialization(
    *,
    controller: Any,
    service_uuid: str,
    service_name: str,
    timeout: float,
    max_response_bytes: int,
    wait_seconds: float,
    poll_interval_seconds: float,
    opener: Any,
    sleeper: Callable[[float], None],
    label: str = "stress-target-materialization",
) -> tuple[bool, list[dict[str, Any]]]:
    started = time.monotonic()
    polls: list[dict[str, Any]] = []
    while True:
        _response, snapshot = _detail(
            controller=controller,
            service_uuid=service_uuid,
            service_name=service_name,
            timeout=timeout,
            max_response_bytes=max_response_bytes,
            opener=opener,
            label=label,
        )
        polls.append(snapshot)
        if _target_materialized(snapshot, service_name):
            return True, polls
        if time.monotonic() - started >= wait_seconds:
            return False, polls
        sleeper(poll_interval_seconds)


def _wait_for_target_start_marker(
    *,
    controller: Any,
    service_uuid: str,
    service_name: str,
    timeout: float,
    max_response_bytes: int,
    wait_seconds: float,
    poll_interval_seconds: float,
    opener: Any,
    sleeper: Callable[[float], None],
) -> tuple[bool, list[dict[str, Any]]]:
    verifier_name = _verifier_name(service_name)
    expected_marker = VERIFY_LOG_MARKER
    started = time.monotonic()
    observations: list[dict[str, Any]] = []

    while True:
        response, snapshot = _detail(
            controller=controller,
            service_uuid=service_uuid,
            service_name=service_name,
            timeout=timeout,
            max_response_bytes=max_response_bytes,
            opener=opener,
            label="stress-target-readiness",
        )
        verifier_record = _application_record(snapshot, verifier_name)
        runtime_logs = _runtime_logs(
            controller=controller,
            service_uuid=service_uuid,
            service_name=service_name,
            service_detail_payload=response.get("payload"),
            timeout=timeout,
            max_response_bytes=max_response_bytes,
            opener=opener,
            application_name=verifier_name,
        )
        logs_text = "\n".join(
            str(item.get("logs") or "")
            for item in runtime_logs.get("attempts") or []
            if isinstance(item, Mapping)
        )
        marker_observed = expected_marker in logs_text
        observations.append(
            {
                "observed_at": snapshot.get("observed_at"),
                "service_status": snapshot.get("service_status"),
                "service_detail_snapshot": snapshot,
                "verifier_name": verifier_name,
                "verifier_record": dict(verifier_record) if verifier_record else None,
                "runtime_logs": runtime_logs,
                "expected_marker": expected_marker,
                "expected_marker_observed": marker_observed,
            }
        )

        if marker_observed:
            return True, observations
        if time.monotonic() - started >= wait_seconds:
            return False, observations
        sleeper(poll_interval_seconds)


def _wait_for_observer_start_marker(
    *,
    controller: Any,
    service_uuid: str,
    service_name: str,
    timeout: float,
    max_response_bytes: int,
    wait_seconds: float,
    poll_interval_seconds: float,
    opener: Any,
    sleeper: Callable[[float], None],
) -> tuple[bool, list[dict[str, Any]]]:
    expected_marker = f"{OBSERVER_LOG_MARKER} phase=observer-start"
    started = time.monotonic()
    observations: list[dict[str, Any]] = []

    while True:
        response, snapshot = _detail(
            controller=controller,
            service_uuid=service_uuid,
            service_name=service_name,
            timeout=timeout,
            max_response_bytes=max_response_bytes,
            opener=opener,
            label="stress-observer-readiness",
        )
        runtime_logs = _runtime_logs(
            controller=controller,
            service_uuid=service_uuid,
            service_name=service_name,
            service_detail_payload=response.get("payload"),
            timeout=timeout,
            max_response_bytes=max_response_bytes,
            opener=opener,
            application_name=service_name,
        )
        logs_text = _observer_log_text(runtime_logs)
        marker_observed = expected_marker in logs_text
        observations.append(
            {
                "observed_at": snapshot.get("observed_at"),
                "service_status": snapshot.get("service_status"),
                "service_detail_snapshot": snapshot,
                "runtime_logs": runtime_logs,
                "expected_marker": expected_marker,
                "expected_marker_observed": marker_observed,
            }
        )

        if marker_observed:
            return True, observations
        if time.monotonic() - started >= wait_seconds:
            return False, observations
        sleeper(poll_interval_seconds)


def _wait_for_service_health(
    *,
    controller: Any,
    service_uuid: str,
    service_name: str,
    timeout: float,
    max_response_bytes: int,
    wait_seconds: float,
    poll_interval_seconds: float,
    opener: Any,
    sleeper: Callable[[float], None],
    controller_id: str,
    controller_meta: Mapping[str, Any],
    transition_diagnostics: bool,
) -> tuple[bool, list[dict[str, Any]], list[dict[str, Any]]]:
    started = time.monotonic()
    polls: list[dict[str, Any]] = []
    diagnostics: list[dict[str, Any]] = []
    previous: tuple[str, tuple[str, ...]] | None = None
    while True:
        _response, snapshot = _detail(
            controller=controller,
            service_uuid=service_uuid,
            service_name=service_name,
            timeout=timeout,
            max_response_bytes=max_response_bytes,
            opener=opener,
            label="stress-writer-health-poll",
        )
        poll = {
            "observed_at": snapshot.get("observed_at"),
            "service_status": snapshot.get("service_status"),
            "service_detail_snapshot": snapshot,
        }
        polls.append(poll)

        signature = _status_signature(snapshot)
        if transition_diagnostics and signature != previous:
            diagnostics.append(
                _capture_diagnostics(
                    controller=controller,
                    controller_id=controller_id,
                    controller_meta=controller_meta,
                    service_uuid=service_uuid,
                    service_name=service_name,
                    timeout=timeout,
                    max_response_bytes=max_response_bytes,
                    opener=opener,
                    reason=f"status-transition-{len(diagnostics) + 1}",
                )
            )
            previous = signature

        if bootnode._healthy_status(str(snapshot.get("service_status") or "")):
            return True, polls, diagnostics
        if time.monotonic() - started >= wait_seconds:
            return False, polls, diagnostics
        sleeper(poll_interval_seconds)


def _wait_for_verifier_sha(
    *,
    controller: Any,
    service_uuid: str,
    service_name: str,
    expected_sha256: str,
    timeout: float,
    max_response_bytes: int,
    wait_seconds: float,
    poll_interval_seconds: float,
    opener: Any,
    sleeper: Callable[[float], None],
) -> tuple[bool, list[dict[str, Any]]]:
    verifier_name = _verifier_name(service_name)
    expected_marker = f"{VERIFY_LOG_MARKER}{expected_sha256}"
    started = time.monotonic()
    observations: list[dict[str, Any]] = []

    while True:
        response, snapshot = _detail(
            controller=controller,
            service_uuid=service_uuid,
            service_name=service_name,
            timeout=timeout,
            max_response_bytes=max_response_bytes,
            opener=opener,
            label="stress-target-write-verification",
        )
        verifier_record = _application_record(snapshot, verifier_name)
        runtime_logs = _runtime_logs(
            controller=controller,
            service_uuid=service_uuid,
            service_name=service_name,
            service_detail_payload=response.get("payload"),
            timeout=timeout,
            max_response_bytes=max_response_bytes,
            opener=opener,
            application_name=verifier_name,
        )
        logs_text = "\n".join(
            str(item.get("logs") or "")
            for item in runtime_logs.get("attempts") or []
            if isinstance(item, Mapping)
        )
        observation = {
            "observed_at": snapshot.get("observed_at"),
            "verifier_name": verifier_name,
            "verifier_record": dict(verifier_record) if verifier_record else None,
            "runtime_logs": runtime_logs,
            "expected_marker_observed": expected_marker in logs_text,
        }
        observations.append(observation)

        if expected_marker in logs_text:
            return True, observations
        if time.monotonic() - started >= wait_seconds:
            return False, observations
        sleeper(poll_interval_seconds)


def _run_iteration(
    *,
    iteration: int,
    controller: Any,
    controller_id: str,
    controller_meta: Mapping[str, Any],
    network: str,
    environment_uuid: str,
    timeout: float,
    max_response_bytes: int,
    target_wait_seconds: float,
    writer_wait_seconds: float,
    verify_wait_seconds: float,
    poll_interval_seconds: float,
    opener: Any,
    sleeper: Callable[[float], None],
    cleanup_failed: bool,
) -> dict[str, Any]:
    target_service_name = _iteration_name("mother-writer-stress-target", iteration)
    requested_target_container = _iteration_name("mother-writer-stress-container", iteration)
    writer_service_name = _iteration_name("mother-static-node-writer-stress", iteration)
    observer_service_name = _iteration_name("mother-writer-stress-observer", iteration)
    provisional_action = _build_action(
        iteration=iteration,
        target_container=requested_target_container,
        controller_id=controller_id,
    )
    target_compose = _target_compose(
        target_service_name=target_service_name,
        target_container=requested_target_container,
        expected_sha256=provisional_action["static_nodes_sha256"],
    )
    observer_compose = _observer_compose(
        observer_service_name=observer_service_name,
        writer_service_name=writer_service_name,
    )

    action: dict[str, Any] | None = None
    writer_compose: str | None = None
    result: dict[str, Any] = {
        "iteration": iteration,
        "started_at": _utc_now(),
        "status": "failed",
        "controller_id": controller_id,
        "target": {
            "service_name": target_service_name,
            "requested_container_name": requested_target_container,
            "container_name": None,
            "expected_static_nodes_sha256": provisional_action["static_nodes_sha256"],
            "compose_sha256": hashlib.sha256(target_compose.encode("utf-8")).hexdigest(),
        },
        "observer": {
            "service_name": observer_service_name,
            "compose_sha256": hashlib.sha256(observer_compose.encode("utf-8")).hexdigest(),
            "observer_script_sha256": hashlib.sha256(
                _observer_script(writer_service_name).encode("utf-8")
            ).hexdigest(),
            "writer_service_name": writer_service_name,
        },
        "writer": {
            "service_name": writer_service_name,
            "production_compose_unmodified": True,
        },
        "failure_signature": None,
        "diagnostics": [],
        "cleanup": [],
    }

    target_uuid: str | None = None
    observer_uuid: str | None = None
    writer_uuid: str | None = None
    failure_reason: str | None = None

    try:
        target_body = _service_body(
            controller_meta,
            network=network,
            environment_uuid=environment_uuid,
            name=target_service_name,
            compose=target_compose,
            description="Disposable API-only Mother static-node writer stress target",
        )
        target_uuid, target_create = _create_service(
            controller=controller,
            body=target_body,
            timeout=timeout,
            max_response_bytes=max_response_bytes,
            opener=opener,
        )
        result["target"]["service_uuid"] = target_uuid
        result["target"]["create"] = target_create
        if not target_uuid:
            failure_reason = "target-create-failed"
            raise WriterStressSmokeError(failure_reason)

        target_start = _start_service(
            controller=controller,
            service_uuid=target_uuid,
            service_name=target_service_name,
            timeout=timeout,
            max_response_bytes=max_response_bytes,
            opener=opener,
        )
        result["target"]["start"] = target_start
        if target_start.get("ok") is not True:
            failure_reason = "target-start-failed"
            raise WriterStressSmokeError(failure_reason)

        target_ready, target_readiness_observations = _wait_for_target_start_marker(
            controller=controller,
            service_uuid=target_uuid,
            service_name=target_service_name,
            timeout=timeout,
            max_response_bytes=max_response_bytes,
            wait_seconds=target_wait_seconds,
            poll_interval_seconds=poll_interval_seconds,
            opener=opener,
            sleeper=sleeper,
        )
        result["target"]["readiness_observations"] = target_readiness_observations
        if not target_ready:
            failure_reason = "target-start-marker-not-observed"
            result["diagnostics"].append(
                _capture_diagnostics(
                    controller=controller,
                    controller_id=controller_id,
                    controller_meta=controller_meta,
                    service_uuid=target_uuid,
                    service_name=target_service_name,
                    timeout=timeout,
                    max_response_bytes=max_response_bytes,
                    opener=opener,
                    reason=failure_reason,
                )
            )
            raise WriterStressSmokeError(failure_reason)

        resolved_target_container, target_resolution = _resolve_finalized_target_container(
            controller=controller,
            service_uuid=target_uuid,
            service_name=target_service_name,
            timeout=timeout,
            max_response_bytes=max_response_bytes,
            opener=opener,
        )
        result["target"]["container_resolution"] = target_resolution
        result["target"]["container_name"] = resolved_target_container
        if not resolved_target_container:
            failure_reason = "target-container-name-unresolved"
            result["diagnostics"].append(
                _capture_diagnostics(
                    controller=controller,
                    controller_id=controller_id,
                    controller_meta=controller_meta,
                    service_uuid=target_uuid,
                    service_name=target_service_name,
                    timeout=timeout,
                    max_response_bytes=max_response_bytes,
                    opener=opener,
                    reason=failure_reason,
                )
            )
            raise WriterStressSmokeError(failure_reason)

        action = _build_action(
            iteration=iteration,
            target_container=resolved_target_container,
            controller_id=controller_id,
        )
        # Keep this exact production-generated writer compose untouched. The
        # diagnostic observer is a separate Coolify service.
        writer_compose = bootnode._writer_service_compose(writer_service_name, action)
        result["writer"]["compose_sha256"] = hashlib.sha256(
            writer_compose.encode("utf-8")
        ).hexdigest()
        result["writer"]["writer_script_sha256"] = hashlib.sha256(
            bootnode._writer_script(action).encode("utf-8")
        ).hexdigest()
        result["writer"]["target_container_name"] = resolved_target_container

        observer_body = _service_body(
            controller_meta,
            network=network,
            environment_uuid=environment_uuid,
            name=observer_service_name,
            compose=observer_compose,
            description="API-only observer for Mother static-node writer stress smoke",
        )
        observer_uuid, observer_create = _create_service(
            controller=controller,
            body=observer_body,
            timeout=timeout,
            max_response_bytes=max_response_bytes,
            opener=opener,
        )
        result["observer"]["service_uuid"] = observer_uuid
        result["observer"]["create"] = observer_create
        if not observer_uuid:
            failure_reason = "observer-create-failed"
            raise WriterStressSmokeError(failure_reason)

        observer_start = _start_service(
            controller=controller,
            service_uuid=observer_uuid,
            service_name=observer_service_name,
            timeout=timeout,
            max_response_bytes=max_response_bytes,
            opener=opener,
        )
        result["observer"]["start"] = observer_start
        if observer_start.get("ok") is not True:
            failure_reason = "observer-start-failed"
            result["observer"]["failure_capture"] = _capture_observer(
                controller=controller,
                service_uuid=observer_uuid,
                service_name=observer_service_name,
                timeout=timeout,
                max_response_bytes=max_response_bytes,
                opener=opener,
                reason=failure_reason,
            )
            raise WriterStressSmokeError(failure_reason)

        observer_ready, observer_observations = _wait_for_observer_start_marker(
            controller=controller,
            service_uuid=observer_uuid,
            service_name=observer_service_name,
            timeout=timeout,
            max_response_bytes=max_response_bytes,
            wait_seconds=target_wait_seconds,
            poll_interval_seconds=poll_interval_seconds,
            opener=opener,
            sleeper=sleeper,
        )
        result["observer"]["readiness_observations"] = observer_observations
        if not observer_ready:
            failure_reason = "observer-start-marker-not-observed"
            result["observer"]["failure_capture"] = _capture_observer(
                controller=controller,
                service_uuid=observer_uuid,
                service_name=observer_service_name,
                timeout=timeout,
                max_response_bytes=max_response_bytes,
                opener=opener,
                reason=failure_reason,
            )
            raise WriterStressSmokeError(failure_reason)

        writer_body = _service_body(
            controller_meta,
            network=network,
            environment_uuid=environment_uuid,
            name=writer_service_name,
            compose=writer_compose,
            description="API-only Mother production-shaped static-node writer stress smoke",
        )
        writer_uuid, writer_create = _create_service(
            controller=controller,
            body=writer_body,
            timeout=timeout,
            max_response_bytes=max_response_bytes,
            opener=opener,
        )
        result["writer"]["service_uuid"] = writer_uuid
        result["writer"]["create"] = writer_create
        if not writer_uuid:
            failure_reason = "writer-create-failed"
            result["observer"]["failure_capture"] = _capture_observer(
                controller=controller,
                service_uuid=observer_uuid,
                service_name=observer_service_name,
                timeout=timeout,
                max_response_bytes=max_response_bytes,
                opener=opener,
                reason=failure_reason,
            )
            raise WriterStressSmokeError(failure_reason)

        result["diagnostics"].append(
            _capture_diagnostics(
                controller=controller,
                controller_id=controller_id,
                controller_meta=controller_meta,
                service_uuid=writer_uuid,
                service_name=writer_service_name,
                timeout=timeout,
                max_response_bytes=max_response_bytes,
                opener=opener,
                reason="writer-pre-start",
            )
        )

        writer_start = _start_service(
            controller=controller,
            service_uuid=writer_uuid,
            service_name=writer_service_name,
            timeout=timeout,
            max_response_bytes=max_response_bytes,
            opener=opener,
        )
        result["writer"]["start"] = writer_start
        if writer_start.get("ok") is not True:
            failure_reason = "writer-start-failed"
            final_diag = _capture_diagnostics(
                controller=controller,
                controller_id=controller_id,
                controller_meta=controller_meta,
                service_uuid=writer_uuid,
                service_name=writer_service_name,
                timeout=timeout,
                max_response_bytes=max_response_bytes,
                opener=opener,
                reason=failure_reason,
            )
            result["diagnostics"].append(final_diag)
            result["observer"]["failure_capture"] = _capture_observer(
                controller=controller,
                service_uuid=observer_uuid,
                service_name=observer_service_name,
                timeout=timeout,
                max_response_bytes=max_response_bytes,
                opener=opener,
                reason=failure_reason,
            )
            raise WriterStressSmokeError(failure_reason)

        healthy, writer_polls, transition_diagnostics = _wait_for_service_health(
            controller=controller,
            service_uuid=writer_uuid,
            service_name=writer_service_name,
            timeout=timeout,
            max_response_bytes=max_response_bytes,
            wait_seconds=writer_wait_seconds,
            poll_interval_seconds=poll_interval_seconds,
            opener=opener,
            sleeper=sleeper,
            controller_id=controller_id,
            controller_meta=controller_meta,
            transition_diagnostics=True,
        )
        result["writer"]["polls"] = writer_polls
        result["diagnostics"].extend(transition_diagnostics)

        if not healthy:
            failure_reason = "writer-not-healthy"
            final_diag = _capture_diagnostics(
                controller=controller,
                controller_id=controller_id,
                controller_meta=controller_meta,
                service_uuid=writer_uuid,
                service_name=writer_service_name,
                timeout=timeout,
                max_response_bytes=max_response_bytes,
                opener=opener,
                reason=failure_reason,
            )
            result["diagnostics"].append(final_diag)
            signature_diagnostics = [*transition_diagnostics, final_diag]
            result["failure_signature"] = _failure_signature(
                writer_polls,
                signature_diagnostics,
            )
            result["observer"]["failure_capture"] = _capture_observer(
                controller=controller,
                service_uuid=observer_uuid,
                service_name=observer_service_name,
                timeout=timeout,
                max_response_bytes=max_response_bytes,
                opener=opener,
                reason=failure_reason,
            )
            raise WriterStressSmokeError(failure_reason)

        result["failure_signature"] = _failure_signature(
            writer_polls,
            transition_diagnostics,
        )
        result["observer"]["post_writer_capture"] = _capture_observer(
            controller=controller,
            service_uuid=observer_uuid,
            service_name=observer_service_name,
            timeout=timeout,
            max_response_bytes=max_response_bytes,
            opener=opener,
            reason="writer-healthy",
        )

        verified, verify_polls = _wait_for_verifier_sha(
            controller=controller,
            service_uuid=target_uuid,
            service_name=target_service_name,
            expected_sha256=action["static_nodes_sha256"],
            timeout=timeout,
            max_response_bytes=max_response_bytes,
            wait_seconds=verify_wait_seconds,
            poll_interval_seconds=poll_interval_seconds,
            opener=opener,
            sleeper=sleeper,
        )
        result["target"]["verification_polls"] = verify_polls
        result["target"]["write_verified_by_verifier_logs"] = verified
        if not verified:
            failure_reason = "target-write-not-verified"
            result["diagnostics"].append(
                _capture_diagnostics(
                    controller=controller,
                    controller_id=controller_id,
                    controller_meta=controller_meta,
                    service_uuid=writer_uuid,
                    service_name=writer_service_name,
                    timeout=timeout,
                    max_response_bytes=max_response_bytes,
                    opener=opener,
                    reason=failure_reason,
                )
            )
            result["diagnostics"].append(
                _capture_diagnostics(
                    controller=controller,
                    controller_id=controller_id,
                    controller_meta=controller_meta,
                    service_uuid=target_uuid,
                    service_name=target_service_name,
                    timeout=timeout,
                    max_response_bytes=max_response_bytes,
                    opener=opener,
                    reason=failure_reason,
                )
            )
            result["observer"]["failure_capture"] = _capture_observer(
                controller=controller,
                service_uuid=observer_uuid,
                service_name=observer_service_name,
                timeout=timeout,
                max_response_bytes=max_response_bytes,
                opener=opener,
                reason=failure_reason,
            )
            raise WriterStressSmokeError(failure_reason)

        result["status"] = "pass"
        result["reason"] = None
        return result
    except WriterStressSmokeError as exc:
        result["status"] = "failed"
        result["reason"] = failure_reason or str(exc)
        return result
    finally:
        should_cleanup = result.get("status") == "pass" or cleanup_failed
        if should_cleanup:
            for service_uuid, service_name, role in (
                (writer_uuid, writer_service_name, "writer"),
                (observer_uuid, observer_service_name, "observer"),
                (target_uuid, target_service_name, "target"),
            ):
                if not service_uuid:
                    continue
                result["cleanup"].append(
                    {
                        "role": role,
                        **_delete_service(
                            controller=controller,
                            service_uuid=service_uuid,
                            service_name=service_name,
                            timeout=timeout,
                            max_response_bytes=max_response_bytes,
                            opener=opener,
                        ),
                    }
                )
        else:
            result["failed_resources_preserved"] = {
                "writer_service_uuid": writer_uuid,
                "writer_service_name": writer_service_name if writer_uuid else None,
                "observer_service_uuid": observer_uuid,
                "observer_service_name": observer_service_name if observer_uuid else None,
                "target_service_uuid": target_uuid,
                "target_service_name": target_service_name if target_uuid else None,
            }
        result["completed_at"] = _utc_now()


def _failure_focus_role(result: Mapping[str, Any]) -> str:
    reason = str(result.get("reason") or "")
    resources = result.get("failed_resources_preserved")
    resources = resources if isinstance(resources, Mapping) else {}

    preferred: list[str]
    if reason.startswith("target-"):
        preferred = ["target", "writer", "observer"]
    elif reason.startswith("observer-"):
        preferred = ["observer", "writer", "target"]
    else:
        preferred = ["writer", "target", "observer"]

    for role in preferred:
        if resources.get(f"{role}_service_uuid"):
            return role
    return preferred[0]


def _host_application_names(result: Mapping[str, Any], role: str) -> list[str]:
    resource = result.get(role)
    resource = resource if isinstance(resource, Mapping) else {}
    service_name = str(resource.get("service_name") or "").strip()
    if not service_name:
        return []
    names = [service_name]
    if role == "target":
        verifier = _verifier_name(service_name)
        if verifier not in names:
            names.append(verifier)
    return names


def _host_inspection_commands(
    *,
    service_uuid: str,
    service_name: str,
    application_names: Sequence[str],
    started_at: str | None,
    completed_at: str | None,
) -> list[str]:
    # These commands are intentionally emitted for an operator who is already
    # on the Coolify host. The smoke never opens SSH or executes host commands.
    service_dir = f"/data/coolify/services/{service_uuid}"
    commands = [
        f"ls -la {service_dir}",
        f"find {service_dir} -maxdepth 2 -type f -print | sort",
        (
            f"for f in {service_dir}/docker-compose.yml {service_dir}/docker-compose.yaml; "
            'do if [ -f "$f" ]; then echo "===== $f ====="; sed -n \'1,260p\' "$f"; fi; done'
        ),
    ]
    for application_name in application_names:
        label = f"com.docker.compose.service={application_name}"
        commands.extend(
            [
                (
                    f"docker ps -a --no-trunc --filter 'label={label}' "
                    "--format '{{.ID}} {{.Names}} {{.Image}} {{.Status}}'"
                ),
                (
                    f"for cid in $(docker ps -aq --filter 'label={label}'); do "
                    'echo "===== STATE $cid ====="; '
                    "docker inspect \"$cid\" --format "
                    "'Status={{.State.Status}} ExitCode={{.State.ExitCode}} "
                    "OOMKilled={{.State.OOMKilled}} Error={{json .State.Error}} "
                    "StartedAt={{.State.StartedAt}} FinishedAt={{.State.FinishedAt}}'; "
                    'echo "===== CMD $cid ====="; '
                    "docker inspect \"$cid\" --format '{{json .Config.Cmd}}'; "
                    'echo "===== LOGS $cid ====="; '
                    'docker logs --timestamps --tail 300 "$cid" 2>&1; '
                    "done"
                ),
            ]
        )
    if started_at and completed_at:
        commands.append(
            (
                f"docker events --since '{started_at}' --until '{completed_at}' "
                "--filter type=container --format '{{json .}}' "
                f"| grep -F '{service_name}' || true"
            )
        )
        commands.append(
            (
                f"journalctl -u docker.service --since '{started_at}' --until '{completed_at}' "
                "--no-pager | tail -n 400"
            )
        )
        commands.append(
            (
                f"journalctl -u containerd.service --since '{started_at}' --until '{completed_at}' "
                "--no-pager | tail -n 400"
            )
        )
    return commands


def _build_failure_followup(
    *,
    result: Mapping[str, Any],
    evidence_path: str | Path,
    controller_id: str,
) -> dict[str, Any]:
    resources = result.get("failed_resources_preserved")
    resources = resources if isinstance(resources, Mapping) else {}
    role = _failure_focus_role(result)
    service_uuid = str(resources.get(f"{role}_service_uuid") or "").strip()
    service_name = str(resources.get(f"{role}_service_name") or "").strip()
    evidence_arg = str(evidence_path)
    per_resource: list[dict[str, str]] = []
    for candidate_role in ("target", "observer", "writer"):
        candidate_uuid = str(resources.get(f"{candidate_role}_service_uuid") or "").strip()
        if not candidate_uuid:
            continue
        per_resource.append(
            {
                "role": candidate_role,
                "service_uuid": candidate_uuid,
                "command": (
                    "python tools/mother_writer_stress_failure_twiddle.py "
                    f'--evidence "{evidence_arg}" --role {candidate_role}'
                ),
            }
        )

    followup: dict[str, Any] = {
        "preserved_failure": True,
        "controller_id": controller_id,
        "failure_reason": result.get("reason"),
        "primary_role": role,
        "twiddle": {
            "command": (
                "python tools/mother_writer_stress_failure_twiddle.py "
                f'--evidence "{evidence_arg}" --role auto'
            ),
            "per_resource": per_resource,
        },
        "coolify_host": {
            "run_on_controller_host": controller_id,
            "ssh_invoked_by_smoke": False,
            "service_uuid": service_uuid or None,
            "service_name": service_name or None,
            "service_dir": f"/data/coolify/services/{service_uuid}" if service_uuid else None,
            "commands": [],
        },
    }
    if service_uuid and service_name:
        followup["coolify_host"]["commands"] = _host_inspection_commands(
            service_uuid=service_uuid,
            service_name=service_name,
            application_names=_host_application_names(result, role),
            started_at=str(result.get("started_at") or "") or None,
            completed_at=str(result.get("completed_at") or "") or None,
        )
    return followup


def run_stress(
    *,
    network: str,
    controller_id: str,
    runtime_state_root: str | Path,
    iterations: int,
    execute: bool,
    allow_mutation: bool,
    cleanup_failed: bool,
    continue_after_failure: bool,
    timeout: float,
    max_response_bytes: int,
    target_wait_seconds: float,
    writer_wait_seconds: float,
    verify_wait_seconds: float,
    poll_interval_seconds: float,
    opener: Any = urllib.request.urlopen,
    sleeper: Callable[[float], None] = time.sleep,
) -> dict[str, Any]:
    if not execute or not allow_mutation:
        raise WriterStressSmokeError(
            "live stress requires both --execute and --allow-mutation"
        )
    if iterations < 1:
        raise WriterStressSmokeError("iterations must be >= 1")
    for label, value in (
        ("timeout", timeout),
        ("max_response_bytes", max_response_bytes),
        ("target_wait_seconds", target_wait_seconds),
        ("writer_wait_seconds", writer_wait_seconds),
        ("verify_wait_seconds", verify_wait_seconds),
        ("poll_interval_seconds", poll_interval_seconds),
    ):
        if float(value) <= 0:
            raise WriterStressSmokeError(f"{label} must be positive")

    private_state = bootnode._load_private_state(
        runtime_state_root,
        network=network,
        mode="execute",
    )
    controller = bootnode._controller(
        private_state,
        network=network,
        controller_id=controller_id,
    )
    controller_meta = bootnode._controller_config(
        private_state,
        network=network,
        controller_id=controller_id,
    )
    environment_uuid = bootnode._resolve_environment_uuid(
        controller=controller,
        controller_id=controller_id,
        project_uuid=str(controller_meta["project_uuid"]),
        expected_name=network,
        timeout=timeout,
        max_response_bytes=max_response_bytes,
        opener=opener,
        observations=[],
    )

    evidence: dict[str, Any] = {
        "kind": KIND,
        "schema_version": 2,
        "started_at": _utc_now(),
        "network": network,
        "controller_id": controller_id,
        "transport": "coolify-http-api-only",
        "ssh_used": False,
        "host_shell_used": False,
        "local_docker_used": False,
        "iterations_requested": iterations,
        "cleanup_failed": cleanup_failed,
        "continue_after_failure": continue_after_failure,
        "results": [],
    }
    root = Path(runtime_state_root) / "mother" / "evidence" / EVIDENCE_SUBDIR
    evidence_path = root / f"{_stamp()}-{controller_id}.json"

    for iteration in range(1, iterations + 1):
        item = _run_iteration(
            iteration=iteration,
            controller=controller,
            controller_id=controller_id,
            controller_meta=controller_meta,
            network=network,
            environment_uuid=environment_uuid,
            timeout=timeout,
            max_response_bytes=max_response_bytes,
            target_wait_seconds=target_wait_seconds,
            writer_wait_seconds=writer_wait_seconds,
            verify_wait_seconds=verify_wait_seconds,
            poll_interval_seconds=poll_interval_seconds,
            opener=opener,
            sleeper=sleeper,
            cleanup_failed=cleanup_failed,
        )
        evidence["results"].append(item)
        evidence["completed_iterations"] = iteration
        evidence["status"] = (
            "pass"
            if all(result.get("status") == "pass" for result in evidence["results"])
            else "failed"
        )
        evidence["completed_at"] = _utc_now()
        if item.get("status") != "pass" and item.get("failed_resources_preserved"):
            item["operator_followup"] = _build_failure_followup(
                result=item,
                evidence_path=evidence_path,
                controller_id=controller_id,
            )
        _atomic_write_json(evidence_path, evidence)
        print(
            json.dumps(
                {
                    "iteration": iteration,
                    "status": item.get("status"),
                    "reason": item.get("reason"),
                    "writer_service_uuid": item.get("writer", {}).get("service_uuid"),
                    "observer_service_uuid": item.get("observer", {}).get("service_uuid"),
                    "target_service_uuid": item.get("target", {}).get("service_uuid"),
                    "matches_observed_incident": (
                        item.get("failure_signature") or {}
                    ).get("matches_observed_incident"),
                    "evidence_path": str(evidence_path),
                    "twiddle_command": (
                        (item.get("operator_followup") or {}).get("twiddle") or {}
                    ).get("command"),
                    "coolify_host_commands": (
                        (item.get("operator_followup") or {}).get("coolify_host") or {}
                    ).get("commands"),
                },
                sort_keys=True,
            ),
            flush=True,
        )
        if item.get("status") != "pass" and not continue_after_failure:
            break

    evidence["status"] = (
        "pass"
        if evidence["results"]
        and all(result.get("status") == "pass" for result in evidence["results"])
        else "failed"
    )
    evidence["summary"] = {
        "pass_count": sum(1 for item in evidence["results"] if item.get("status") == "pass"),
        "failure_count": sum(1 for item in evidence["results"] if item.get("status") != "pass"),
        "incident_signature_count": sum(
            1
            for item in evidence["results"]
            if (item.get("failure_signature") or {}).get("matches_observed_incident") is True
        ),
        "failed_resources_preserved": any(
            bool(item.get("failed_resources_preserved"))
            for item in evidence["results"]
        ),
    }
    evidence["completed_at"] = _utc_now()
    _atomic_write_json(evidence_path, evidence)
    evidence["evidence_path"] = str(evidence_path)
    return evidence


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "API-only stress smoke for Mother's production static-node writer "
            "materialization pathway."
        )
    )
    parser.add_argument("network", nargs="?", default="mainnet")
    parser.add_argument("--controller", default="coolify-c")
    parser.add_argument("--runtime-state-root", default="runtime/state")
    parser.add_argument("--iterations", type=int, default=DEFAULT_ITERATIONS)
    parser.add_argument("--execute", action="store_true")
    parser.add_argument("--allow-mutation", action="store_true")
    parser.add_argument(
        "--cleanup-failed",
        action="store_true",
        help="delete failed writer/observer/target services; default preserves them for diagnosis",
    )
    parser.add_argument("--continue-after-failure", action="store_true")
    parser.add_argument("--timeout", type=float, default=15.0)
    parser.add_argument("--max-response-bytes", type=int, default=bootnode.DEFAULT_MAX_RESPONSE_BYTES)
    parser.add_argument("--target-wait-seconds", type=float, default=DEFAULT_TARGET_WAIT_SECONDS)
    parser.add_argument("--writer-wait-seconds", type=float, default=DEFAULT_WRITER_WAIT_SECONDS)
    parser.add_argument("--verify-wait-seconds", type=float, default=DEFAULT_VERIFY_WAIT_SECONDS)
    parser.add_argument("--poll-interval-seconds", type=float, default=DEFAULT_POLL_INTERVAL_SECONDS)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)
    try:
        result = run_stress(
            network=args.network,
            controller_id=args.controller,
            runtime_state_root=args.runtime_state_root,
            iterations=args.iterations,
            execute=args.execute,
            allow_mutation=args.allow_mutation,
            cleanup_failed=args.cleanup_failed,
            continue_after_failure=args.continue_after_failure,
            timeout=args.timeout,
            max_response_bytes=args.max_response_bytes,
            target_wait_seconds=args.target_wait_seconds,
            writer_wait_seconds=args.writer_wait_seconds,
            verify_wait_seconds=args.verify_wait_seconds,
            poll_interval_seconds=args.poll_interval_seconds,
        )
    except (WriterStressSmokeError, bootnode.MotherBootnodePrecleanupError) as exc:
        print(
            json.dumps(
                {
                    "status": "failed",
                    "error": str(exc),
                    "transport": "coolify-http-api-only",
                    "ssh_used": False,
                },
                indent=2,
                sort_keys=True,
            ),
            file=sys.stderr,
        )
        return 2
    print(json.dumps(result, indent=2, sort_keys=True))
    return 0 if result.get("status") == "pass" else 1


if __name__ == "__main__":
    raise SystemExit(main())
