#!/usr/bin/env python3
"""Continual NanoJev primary-only consensus curriculum.

This is the deliberate rollback from explicit meta-analysis training.

The optimizer population is exactly the primary population that was already
working inside the consensus-heavy meta experiment:
  * 108 consensus questions
  *   4 triad rehearsal questions
  *   4 dictionary-definition rehearsal questions
  *   4 English/code rehearsal questions

Total: 120 primary questions per cycle, trained for the same default 32
ordinary cross-entropy optimizer steps. No candidate-correctness questions,
primary-error-prediction questions, meta caches, relative arbitration, or meta
evaluation are generated by this script.

The script creates a separate experiment lineage. By default it cuts over from
the latest committed checkpoint of the existing consensus-heavy meta experiment,
including its optimizer moments and RNG state. --source-checkpoint may be used to
start from a specific committed checkpoint in that source experiment.

Training remains ordinary cross entropy on the generic
Question -> Candidate -> ObjectPath boundary with the frozen Qwen backbone.
"""
from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import os
from pathlib import Path
import random
import shutil
import sqlite3
import sys
import time
from typing import Any, Sequence

from nanojev_dictionary_code_store import DictionaryCodeStore
from nanojev_objective_api import ObjectQuestion, ObjectiveRegistry, validate_questions


SCHEMA = "main-computer-nanojev-consensus-primary-only-curriculum-v1"
DEFAULT_EXPERIMENT = r"C:\Users\subsi\NanoJev\runs\main_computer_consensus_primary_only_curriculum_v1"
DEFAULT_SOURCE_EXPERIMENT = r"C:\Users\subsi\NanoJev\runs\main_computer_consensus_heavy_meta_curriculum_v1"
DEFAULT_TRAIN_FILES_PER_CYCLE = 40
DEFAULT_TRIAD_MAX_CODE_TOKENS = 128
DEFAULT_CONSENSUS_MAX_CODE_TOKENS = 128

CONSENSUS_TASK = "consensus"
TRIAD_TASK = "triad"
DICTIONARY_TASK = "dictionary_definition"
ENGLISH_CODE_TASK = "english_code"

TRAINING_PLAN = {
    CONSENSUS_TASK: 108,
    TRIAD_TASK: 4,
    DICTIONARY_TASK: 4,
    ENGLISH_CODE_TASK: 4,
}
TRAIN_QUESTIONS_PER_CYCLE = sum(TRAINING_PLAN.values())


def emit(event: str, **fields: Any) -> None:
    print(json.dumps({"event": event, **fields}, sort_keys=True), flush=True)


def read_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def atomic_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temp = path.with_name(path.name + ".tmp")
    temp.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    os.replace(temp, path)


def load_local_module(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, str(path))
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot import module from {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


def stable_seed(*parts: object) -> int:
    raw = "\0".join(str(part) for part in parts).encode("utf-8")
    return int.from_bytes(hashlib.sha256(raw).digest()[:8], "big")


def clone_sqlite(source: Path, target: Path) -> None:
    source = Path(source).expanduser().resolve(strict=True)
    target = Path(target).expanduser()
    if target.exists():
        return
    target.parent.mkdir(parents=True, exist_ok=True)
    temp = target.with_name(target.name + ".tmp")
    temp.unlink(missing_ok=True)
    src = sqlite3.connect(f"file:{source.as_posix()}?mode=ro", uri=True)
    dst = sqlite3.connect(temp)
    try:
        src.backup(dst)
        dst.commit()
    finally:
        dst.close()
        src.close()
    os.replace(temp, target)


def validate_training_plan(plan: dict[str, int]) -> dict[str, int]:
    expected = dict(TRAINING_PLAN)
    normalized = {str(k): int(v) for k, v in plan.items()}
    if normalized != expected:
        raise ValueError(f"primary-only training plan is fixed: expected={expected} got={normalized}")
    if sum(normalized.values()) != TRAIN_QUESTIONS_PER_CYCLE:
        raise ValueError("primary-only training population does not sum to 120")
    if normalized[CONSENSUS_TASK] % 4:
        raise ValueError("consensus objective requires exact A/B/C/NONE balance")
    if normalized[TRIAD_TASK] % 2:
        raise ValueError("triad rehearsal count must be even")
    if normalized[ENGLISH_CODE_TASK] % 4:
        raise ValueError("English/code rehearsal count must be a multiple of four")
    return normalized


def resolve_source_checkpoint(source_experiment: Path, source_checkpoint: str | None) -> dict[str, Any]:
    source_experiment = Path(source_experiment).expanduser().resolve(strict=True)
    manifest = read_json(source_experiment / "experiment.json")
    state = read_json(source_experiment / "state.json")

    if source_checkpoint:
        checkpoint = Path(source_checkpoint).expanduser().resolve(strict=True)
        checkpoints_root = (source_experiment / "checkpoints").resolve(strict=True)
        try:
            checkpoint.relative_to(checkpoints_root)
        except ValueError as exc:
            raise RuntimeError(
                f"--source-checkpoint must be inside {checkpoints_root}: {checkpoint}"
            ) from exc
        selection_kind = "explicit_committed_checkpoint"
    else:
        latest = state.get("latest_checkpoint")
        if not latest:
            raise RuntimeError(f"source experiment has no committed latest_checkpoint: {source_experiment}")
        checkpoint = Path(str(latest)).expanduser().resolve(strict=True)
        selection_kind = "latest_committed_checkpoint"

    required_checkpoint_files = (
        checkpoint / "head.safetensors",
        checkpoint / "optimizer.pt",
        checkpoint / "rng_state.pt",
        checkpoint / "meta.json",
    )
    missing = [str(path) for path in required_checkpoint_files if not path.is_file()]
    if missing:
        raise RuntimeError(f"source checkpoint is incomplete: {missing}")

    checkpoint_meta = read_json(checkpoint / "meta.json")
    inherited = dict(manifest.get("source") or {})
    required_source = ("model", "revision", "probe_experiment", "legacy_experiment", "repo_root")
    missing_source = [name for name in required_source if not inherited.get(name)]
    if missing_source:
        raise RuntimeError(f"source experiment metadata missing fields: {missing_source}")

    database = manifest.get("database")
    if not database:
        raise RuntimeError("source experiment manifest does not identify its lexical DB")

    source_cycle = int(checkpoint_meta.get("cycle", state.get("cycle", 0)))
    source_global_step = int(checkpoint_meta.get("global_step", state.get("global_step", 0)))
    inherited.update({
        "kind": "logp_experiment",
        "source_lineage": "consensus_heavy_meta_to_primary_only",
        "checkpoint": str(checkpoint),
        "optimizer": str((checkpoint / "optimizer.pt").resolve(strict=True)),
        "rng": str((checkpoint / "rng_state.pt").resolve(strict=True)),
        "source_experiment": str(source_experiment),
        "source_cycle": source_cycle,
        "source_global_step": source_global_step,
        "source_database": str(Path(str(database)).expanduser().resolve(strict=True)),
        "selection": {
            "selection": selection_kind,
            "cycle": source_cycle,
            "global_step": source_global_step,
            "checkpoint": str(checkpoint),
        },
    })
    return inherited


def load_preservation_holdout(*, source_experiment: Path, target: Path,
                              dictionary_curriculum) -> list[ObjectQuestion]:
    source_path = source_experiment / "preservation_holdout.json"
    if not source_path.is_file():
        raise RuntimeError(f"source preservation holdout is missing: {source_path}")
    if not target.is_file():
        shutil.copy2(source_path, target)
    payload = read_json(target)
    questions = [dictionary_curriculum.question_from_dict(row) for row in payload["questions"]]
    validate_questions(questions)
    return questions


def load_old_probe_source_questions(*, direct, source: dict[str, Any], tools_dir: Path,
                                    task: str) -> list[ObjectQuestion]:
    probe_exp = Path(str(source["probe_experiment"])).expanduser().resolve(strict=True)
    repo_root = Path(str(source["repo_root"])).expanduser().resolve(strict=True)
    ordered_api = load_local_module(
        "nanojev_ordered_for_primary_only_probe",
        tools_dir / "nanojev_frozen_qwen_ordered_signal_smoke.py",
    )
    raw = direct.read_jsonl(probe_exp / "probes" / direct.PROBE_FILES[task])
    questions = direct.objectize(task, raw, repo_root=repo_root, ordered_api=ordered_api)
    validate_questions(questions)
    return questions


class ConsensusObjective:
    name = CONSENSUS_TASK

    def __init__(self, *, direct, source_sampler, data, mutation, ordered_api,
                 tokenizer, repo_root: Path, train_manifest: Sequence[dict],
                 max_length: int, max_prompt_tokens: int, max_answer_tokens: int,
                 train_files_per_cycle: int, max_code_tokens: int, seed: int):
        self.direct = direct
        self.source_sampler = source_sampler
        self.data = data
        self.mutation = mutation
        self.ordered_api = ordered_api
        self.tokenizer = tokenizer
        self.repo_root = repo_root
        self.python_manifest = [row for row in train_manifest if row.get("language") == "python"]
        if not self.python_manifest:
            raise RuntimeError("consensus objective found no Python rows in training manifest")
        self.max_length = int(max_length)
        self.max_prompt_tokens = int(max_prompt_tokens)
        self.max_answer_tokens = int(max_answer_tokens)
        self.train_files_per_cycle = int(train_files_per_cycle)
        self.max_code_tokens = int(max_code_tokens)
        self.seed = int(seed)

    def _docs(self, *, cycle: int, split: str, attempt: int):
        rows = list(self.python_manifest)
        file_rng = random.Random(stable_seed(self.seed, cycle, split, attempt, "consensus-files"))
        file_rng.shuffle(rows)
        rows = rows[:min(self.train_files_per_cycle, len(rows))]
        return self.data.load_docs(rows, self.repo_root)

    def _questions(self, *, count: int, cycle: int, split: str) -> list[ObjectQuestion]:
        if count <= 0:
            return []
        if count % 4:
            raise RuntimeError(f"consensus count must be divisible by four: {count}")
        need_each = count // 4
        buckets: dict[str, list[ObjectQuestion]] = {label: [] for label in self.direct.CONSENSUS_LABELS}
        seen: set[str] = set()
        for attempt in range(6):
            docs = self._docs(cycle=cycle, split=split, attempt=attempt)
            oversupply = max(count * 2, count + 24)
            oversupply += (-oversupply) % 4
            seed = stable_seed(self.seed, cycle, split, attempt, "consensus-records")
            raw = self.source_sampler.sample_consensus_records(
                docs=docs,
                mutation=self.mutation,
                data=self.data,
                tokenizer=self.tokenizer,
                split=f"{split}-c{cycle:06d}-a{attempt}",
                record_count=oversupply,
                max_code_tokens=self.max_code_tokens,
                max_length=self.max_length,
                seed=seed,
            )
            questions = self.direct.objectize(
                CONSENSUS_TASK, raw, repo_root=self.repo_root, ordered_api=self.ordered_api
            )
            questions, _filter = self.direct.filter_bounded_questions(
                questions,
                self.tokenizer,
                max_prompt_tokens=self.max_prompt_tokens,
                max_answer_tokens=self.max_answer_tokens,
            )
            for question in questions:
                if question.question_id in seen:
                    continue
                seen.add(question.question_id)
                gold = question.candidates[question.gold_index].candidate_id
                if gold not in buckets:
                    raise RuntimeError(f"consensus question has unexpected gold candidate: {gold}")
                buckets[gold].append(question)
            if all(len(pool) >= need_each for pool in buckets.values()):
                break
        if any(len(pool) < need_each for pool in buckets.values()):
            raise RuntimeError(
                "consensus objective could not build exact balanced cache: "
                f"requested_each={need_each} available={ {k: len(v) for k, v in buckets.items()} }"
            )
        selection_rng = random.Random(stable_seed(self.seed, cycle, split, "consensus-select"))
        selected: list[ObjectQuestion] = []
        for label in self.direct.CONSENSUS_LABELS:
            pool = list(buckets[label])
            selection_rng.shuffle(pool)
            selected.extend(pool[:need_each])
        selection_rng.shuffle(selected)
        validate_questions(selected)
        if len(selected) != count:
            raise RuntimeError(f"consensus objective returned wrong count: {len(selected)} != {count}")
        return selected

    def generate_train(self, *, count: int, cycle: int, rng: random.Random) -> list[ObjectQuestion]:
        return self._questions(count=count, cycle=cycle, split="train")

    def generate_eval(self, *, count: int, cycle: int, rng: random.Random) -> list[ObjectQuestion]:
        return self._questions(count=count, cycle=cycle, split="eval")


def evaluate_preservation(*, dictionary_curriculum, smoke, direct, model, cached,
                          source_questions: Sequence[ObjectQuestion], batch_questions: int) -> dict[str, Any]:
    return dictionary_curriculum.evaluate_holdout(
        smoke=smoke,
        direct=direct,
        model=model,
        cached=cached,
        source_questions=source_questions,
        batch_questions=batch_questions,
    )


def save_checkpoint(*, smoke, direct, experiment_dir: Path, model, optimizer,
                    cycle: int, global_step: int, metrics: dict[str, Any], source: dict,
                    plan: dict[str, int]) -> Path:
    import torch
    from safetensors.torch import save_file

    root = experiment_dir / "checkpoints"
    final = root / f"cycle-{cycle:06d}"
    temp = root / f".cycle-{cycle:06d}.tmp"
    if final.exists() or temp.exists():
        raise RuntimeError(f"primary-only checkpoint already exists: {final}")
    temp.mkdir(parents=True, exist_ok=False)
    save_file(smoke.checkpoint_head_state(model, direct.HEAD_PREFIXES), str(temp / "head.safetensors"))
    torch.save(optimizer.state_dict(), temp / "optimizer.pt")
    direct.save_rng(temp / "rng_state.pt")
    atomic_json(temp / "meta.json", {
        "schema_version": SCHEMA,
        "cycle": cycle,
        "global_step": global_step,
        "source": source,
        "training_plan": plan,
        "metrics": metrics,
    })
    os.replace(temp, final)
    return final


def self_test() -> None:
    plan = validate_training_plan(TRAINING_PLAN)
    assert plan == {
        CONSENSUS_TASK: 108,
        TRIAD_TASK: 4,
        DICTIONARY_TASK: 4,
        ENGLISH_CODE_TASK: 4,
    }
    assert TRAIN_QUESTIONS_PER_CYCLE == 120
    assert sum(plan.values()) == 120
    assert plan[CONSENSUS_TASK] % 4 == 0
    assert plan[TRIAD_TASK] % 2 == 0
    assert plan[ENGLISH_CODE_TASK] % 4 == 0
    assert not any("meta" in task.lower() for task in plan)
    emit("consensus_primary_only_curriculum_self_test_ok", training_plan=plan)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--experiment-dir", default=DEFAULT_EXPERIMENT)
    parser.add_argument("--source-experiment", default=DEFAULT_SOURCE_EXPERIMENT)
    parser.add_argument(
        "--source-checkpoint",
        default=None,
        help="optional committed checkpoint inside --source-experiment/checkpoints; default is latest committed",
    )
    parser.add_argument("--train-files-per-cycle", type=int, default=DEFAULT_TRAIN_FILES_PER_CYCLE)
    parser.add_argument("--triad-max-code-tokens", type=int, default=DEFAULT_TRIAD_MAX_CODE_TOKENS)
    parser.add_argument("--consensus-max-code-tokens", type=int, default=DEFAULT_CONSENSUS_MAX_CODE_TOKENS)
    parser.add_argument("--steps-per-cycle", type=int, default=32)
    parser.add_argument("--batch-questions", type=int, default=10)
    parser.add_argument("--eval-batch-questions", type=int, default=32)
    parser.add_argument("--cache-qwen-batch-questions", type=int, default=4)
    parser.add_argument("--max-prompt-tokens", type=int, default=768)
    parser.add_argument("--max-answer-tokens", type=int, default=128)
    parser.add_argument("--head-lr", type=float, default=2e-5)
    parser.add_argument("--weight-decay", type=float, default=0.01)
    parser.add_argument("--precision", choices=("bf16", "fp32"), default="bf16")
    parser.add_argument("--old-probe-every", type=int, default=10)
    parser.add_argument("--seed", type=int, default=20260930)
    parser.add_argument("--local-files-only", action="store_true", default=True)
    parser.add_argument("--allow-model-download", action="store_false", dest="local_files_only")
    parser.add_argument("--disable-native-triton", action="store_true")
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()

    if args.self_test:
        self_test()
        return

    for name in (
        "train_files_per_cycle", "triad_max_code_tokens", "consensus_max_code_tokens",
        "steps_per_cycle", "batch_questions", "eval_batch_questions", "cache_qwen_batch_questions",
        "max_prompt_tokens", "max_answer_tokens",
    ):
        if int(getattr(args, name)) <= 0:
            parser.error(f"--{name.replace('_', '-')} must be positive")
    if args.old_probe_every < 0:
        parser.error("--old-probe-every must be nonnegative")
    if args.batch_questions > TRAIN_QUESTIONS_PER_CYCLE:
        parser.error("--batch-questions cannot exceed the fixed 120-question training population")

    plan = validate_training_plan(TRAINING_PLAN)

    tools_dir = Path(__file__).resolve().parent
    smoke = load_local_module(
        "nanojev_dictionary_code_smoke_for_primary_only",
        tools_dir / "nanojev_dictionary_code_objective_smoke.py",
    )
    direct = load_local_module(
        "nanojev_direct_logp_for_primary_only",
        tools_dir / "nanojev_code_direct_qwen_logp_train.py",
    )
    dictionary_curriculum = load_local_module(
        "nanojev_dictionary_curriculum_for_primary_only",
        tools_dir / "nanojev_dictionary_definition_curriculum_train.py",
    )
    triad_curriculum = load_local_module(
        "nanojev_triad_curriculum_for_primary_only",
        tools_dir / "nanojev_triad_curriculum_train.py",
    )
    data = load_local_module(
        "nanojev_code_lexeme_data_for_primary_only",
        tools_dir / "nanojev_code_lexeme_data.py",
    )
    mutation = load_local_module(
        "nanojev_code_mutation_for_primary_only",
        tools_dir / "nanojev_code_mutation_train.py",
    )
    source_sampler = load_local_module(
        "nanojev_pairwise_triad_source_for_primary_only",
        tools_dir / "nanojev_code_sparse_register_k1000_s_first_r2_full_head_dictionary_train.py",
    )
    ordered_api = load_local_module(
        "nanojev_ordered_for_primary_only_train",
        tools_dir / "nanojev_frozen_qwen_ordered_signal_smoke.py",
    )

    experiment_dir = Path(args.experiment_dir).expanduser()
    experiment_dir.mkdir(parents=True, exist_ok=True)
    manifest_path = experiment_dir / "experiment.json"
    state_path = experiment_dir / "state.json"
    db_path = experiment_dir / "lexical.db"

    if manifest_path.is_file():
        manifest = read_json(manifest_path)
        if manifest.get("schema_version") != SCHEMA:
            raise RuntimeError(f"existing primary-only experiment has wrong schema: {manifest_path}")
        source = dict(manifest["source"])
        stored_plan = validate_training_plan(dict(manifest["training_plan"]))
        if stored_plan != plan:
            raise RuntimeError(f"cannot resume with a different primary-only training plan: {stored_plan}")
        if not db_path.is_file():
            raise RuntimeError(f"primary-only lexical DB is missing: {db_path}")
    else:
        source = resolve_source_checkpoint(Path(args.source_experiment), args.source_checkpoint)
        clone_sqlite(Path(source["source_database"]), db_path)
        manifest = {
            "schema_version": SCHEMA,
            "created_unix": time.time(),
            "source": source,
            "database": str(db_path.resolve()),
            "training_plan": plan,
            "training_questions_per_cycle": TRAIN_QUESTIONS_PER_CYCLE,
            "training_contract": (
                "120 primary questions only: 108 consensus + 4 triad + 4 dictionary-definition + "
                "4 English/code -> 32 ordinary cross-entropy steps by default -> checkpoint -> repeat"
            ),
            "meta_contract": "none: no meta questions, meta caches, meta arbitration, or meta evaluation",
            "generic_boundary": "Question->Candidate->ObjectPath(prompt,answer)",
        }
        atomic_json(manifest_path, manifest)
        emit(
            "consensus_primary_only_curriculum_source_selected",
            checkpoint=source["checkpoint"],
            source_cycle=source["source_cycle"],
            source_global_step=source["source_global_step"],
            selection=source["selection"],
        )

    source_checkpoint = Path(str(source["checkpoint"])).resolve(strict=True)
    loaded = smoke.load_model(
        direct=direct,
        source=source,
        cutover_dir=source_checkpoint,
        tools_dir=tools_dir,
        max_answer_tokens=args.max_answer_tokens,
        head_lr=args.head_lr,
        weight_decay=args.weight_decay,
        local_files_only=args.local_files_only,
        precision=args.precision,
        disable_native_triton=args.disable_native_triton,
    )
    torch = loaded["torch"]
    model = loaded["model"]
    tokenizer = loaded["tokenizer"]
    optimizer = loaded["optimizer"]
    head_params = loaded["head_params"]

    if state_path.is_file():
        state = read_json(state_path)
        latest = state.get("latest_checkpoint")
        if latest:
            checkpoint = Path(str(latest)).expanduser().resolve(strict=True)
            direct.load_own_checkpoint(model, checkpoint)
            optimizer.load_state_dict(torch.load(checkpoint / "optimizer.pt", map_location="cpu", weights_only=False))
            for group in optimizer.param_groups:
                group["lr"] = float(args.head_lr)
                group["weight_decay"] = float(args.weight_decay)
            direct.move_optimizer_state_to_cuda(optimizer)
            direct.load_rng(checkpoint / "rng_state.pt")
        cycle = int(state.get("cycle", source["source_cycle"]))
        global_step = int(state.get("global_step", source["source_global_step"]))
    else:
        cycle = int(source["source_cycle"])
        global_step = int(source["source_global_step"])
        atomic_json(state_path, {
            "cycle": cycle,
            "global_step": global_step,
            "latest_checkpoint": None,
            "cutover_checkpoint": source["checkpoint"],
            "training_plan": plan,
        })

    legacy_exp = Path(str(source["legacy_experiment"])).expanduser().resolve(strict=True)
    legacy_meta = read_json(legacy_exp / "experiment.json")
    train_manifest = read_json(Path(str(legacy_meta["manifests"]["train"])).expanduser().resolve(strict=True))
    repo_root = Path(str(source["repo_root"])).expanduser().resolve(strict=True)

    with DictionaryCodeStore(db_path) as store:
        english_code_objective = smoke.EnglishCodeObjective(store, repo_root)
        dictionary_objective = dictionary_curriculum.DictionaryDefinitionObjective(store)
        triad_objective = triad_curriculum.TriadObjective(
            direct=direct,
            source_sampler=source_sampler,
            data=data,
            mutation=mutation,
            ordered_api=ordered_api,
            tokenizer=tokenizer,
            repo_root=repo_root,
            train_manifest=train_manifest,
            max_length=int(legacy_meta["max_length"]),
            max_prompt_tokens=args.max_prompt_tokens,
            max_answer_tokens=args.max_answer_tokens,
            train_files_per_cycle=args.train_files_per_cycle,
            max_code_tokens=args.triad_max_code_tokens,
            seed=args.seed,
        )
        consensus_objective = ConsensusObjective(
            direct=direct,
            source_sampler=source_sampler,
            data=data,
            mutation=mutation,
            ordered_api=ordered_api,
            tokenizer=tokenizer,
            repo_root=repo_root,
            train_manifest=train_manifest,
            max_length=int(legacy_meta["max_length"]),
            max_prompt_tokens=args.max_prompt_tokens,
            max_answer_tokens=args.max_answer_tokens,
            train_files_per_cycle=args.train_files_per_cycle,
            max_code_tokens=args.consensus_max_code_tokens,
            seed=args.seed,
        )
        registry = ObjectiveRegistry([
            consensus_objective,
            triad_objective,
            dictionary_objective,
            english_code_objective,
        ])

        source_experiment = Path(str(source["source_experiment"])).expanduser().resolve(strict=True)
        preservation_questions = load_preservation_holdout(
            source_experiment=source_experiment,
            target=experiment_dir / "preservation_holdout.json",
            dictionary_curriculum=dictionary_curriculum,
        )
        preservation_cached, preservation_cache_stats = smoke.cache_questions(
            direct=direct,
            model=model,
            tokenizer=tokenizer,
            questions=preservation_questions,
            args=args,
        )

        triad_source_questions = load_old_probe_source_questions(
            direct=direct,
            source=source,
            tools_dir=tools_dir,
            task=TRIAD_TASK,
        )
        triad_source_questions, triad_filter_stats = direct.filter_bounded_questions(
            triad_source_questions,
            tokenizer,
            max_prompt_tokens=args.max_prompt_tokens,
            max_answer_tokens=args.max_answer_tokens,
        )
        if not triad_source_questions:
            raise RuntimeError(f"all fixed triad questions filtered: {triad_filter_stats}")
        triad_cached, triad_cache_stats = direct.materialize_cached_questions(
            model=model,
            tokenizer=tokenizer,
            questions=triad_source_questions,
            max_prompt_tokens=args.max_prompt_tokens,
            pad_token_id=int(tokenizer.pad_token_id),
            precision=args.precision,
            qwen_batch_questions=args.cache_qwen_batch_questions,
        )

        consensus_source_questions = load_old_probe_source_questions(
            direct=direct,
            source=source,
            tools_dir=tools_dir,
            task=CONSENSUS_TASK,
        )
        consensus_source_questions, consensus_filter_stats = direct.filter_bounded_questions(
            consensus_source_questions,
            tokenizer,
            max_prompt_tokens=args.max_prompt_tokens,
            max_answer_tokens=args.max_answer_tokens,
        )
        if not consensus_source_questions:
            raise RuntimeError(f"all fixed consensus questions filtered: {consensus_filter_stats}")
        consensus_cached, consensus_cache_stats = direct.materialize_cached_questions(
            model=model,
            tokenizer=tokenizer,
            questions=consensus_source_questions,
            max_prompt_tokens=args.max_prompt_tokens,
            pad_token_id=int(tokenizer.pad_token_id),
            precision=args.precision,
            qwen_batch_questions=args.cache_qwen_batch_questions,
        )

        args.skip_old_probes = False
        old_cached = smoke.old_probe_cache(
            direct=direct,
            model=model,
            tokenizer=tokenizer,
            source=source,
            tools_dir=tools_dir,
            args=args,
        )

        cutover_eval_path = experiment_dir / "eval_cutover.json"
        if not cutover_eval_path.is_file():
            preservation = evaluate_preservation(
                dictionary_curriculum=dictionary_curriculum,
                smoke=smoke,
                direct=direct,
                model=model,
                cached=preservation_cached,
                source_questions=preservation_questions,
                batch_questions=args.eval_batch_questions,
            )
            triad_eval = direct.evaluate_cached(
                model=model,
                questions=triad_cached,
                batch_questions=args.eval_batch_questions,
            )
            consensus_eval = direct.evaluate_cached(
                model=model,
                questions=consensus_cached,
                batch_questions=args.eval_batch_questions,
            )
            cutover_eval = {
                "preservation": preservation,
                TRIAD_TASK: triad_eval,
                CONSENSUS_TASK: consensus_eval,
            }
            atomic_json(cutover_eval_path, cutover_eval)
            emit(
                "consensus_primary_only_curriculum_eval_cutover",
                metrics=cutover_eval,
                preservation_cache=preservation_cache_stats,
                triad_cache=triad_cache_stats,
                consensus_cache=consensus_cache_stats,
            )

        emit(
            "consensus_primary_only_curriculum_ready",
            source_checkpoint=source["checkpoint"],
            source_cycle=source["source_cycle"],
            source_selection=source.get("selection"),
            cycle=cycle,
            global_step=global_step,
            registered_objectives=registry.names(),
            training_plan=plan,
            training_questions_per_cycle=TRAIN_QUESTIONS_PER_CYCLE,
            steps_per_cycle=args.steps_per_cycle,
            backbone_frozen=all(not parameter.requires_grad for parameter in model.backbone.parameters()),
            trainable_head_params=sum(parameter.numel() for parameter in head_params),
            database=store.stats(),
            reserve=store.reserve_counts(),
            meta_training=False,
            meta_evaluation=False,
            continuous=True,
        )

        while True:
            cycle += 1
            train_rng = random.Random(stable_seed(args.seed, cycle, "train"))
            train_questions = registry.generate_train(plan, cycle=cycle, rng=train_rng)
            if len(train_questions) != TRAIN_QUESTIONS_PER_CYCLE:
                raise RuntimeError(
                    f"primary training generator returned wrong population: "
                    f"{len(train_questions)} != {TRAIN_QUESTIONS_PER_CYCLE}"
                )
            training_cached, training_cache_stats = smoke.cache_questions(
                direct=direct,
                model=model,
                tokenizer=tokenizer,
                questions=train_questions,
                args=args,
            )
            if len(training_cached) != TRAIN_QUESTIONS_PER_CYCLE:
                raise RuntimeError(
                    f"primary training cache has wrong size: "
                    f"{len(training_cached)} != {TRAIN_QUESTIONS_PER_CYCLE}"
                )

            shuffle_rng = random.Random(stable_seed(args.seed, cycle, "final-train-shuffle"))
            shuffle_rng.shuffle(training_cached)
            train_metrics = smoke.train_cached_questions(
                direct=direct,
                model=model,
                optimizer=optimizer,
                head_params=head_params,
                questions=training_cached,
                steps=args.steps_per_cycle,
                batch_questions=args.batch_questions,
                rng=train_rng,
            )
            global_step += int(args.steps_per_cycle)

            preservation = evaluate_preservation(
                dictionary_curriculum=dictionary_curriculum,
                smoke=smoke,
                direct=direct,
                model=model,
                cached=preservation_cached,
                source_questions=preservation_questions,
                batch_questions=args.eval_batch_questions,
            )
            triad_eval = direct.evaluate_cached(
                model=model,
                questions=triad_cached,
                batch_questions=args.eval_batch_questions,
            )
            consensus_eval = direct.evaluate_cached(
                model=model,
                questions=consensus_cached,
                batch_questions=args.eval_batch_questions,
            )

            old_metrics = None
            if args.old_probe_every and cycle % args.old_probe_every == 0:
                old_metrics = smoke.evaluate_old_probes(
                    direct=direct,
                    model=model,
                    cached=old_cached,
                    batch_questions=args.eval_batch_questions,
                )

            metrics = {
                "training_plan": plan,
                "train": train_metrics,
                "eval": {
                    "preservation": preservation,
                    TRIAD_TASK: triad_eval,
                    CONSENSUS_TASK: consensus_eval,
                },
                "old_probe": old_metrics,
                "database": store.stats(),
                "reserve": store.reserve_counts(),
                "primary_train_cache": training_cache_stats,
                "consensus_eval_cache": consensus_cache_stats,
                "meta_training": False,
                "meta_evaluation": False,
            }
            checkpoint = save_checkpoint(
                smoke=smoke,
                direct=direct,
                experiment_dir=experiment_dir,
                model=model,
                optimizer=optimizer,
                cycle=cycle,
                global_step=global_step,
                metrics=metrics,
                source=source,
                plan=plan,
            )
            state = {
                "cycle": cycle,
                "global_step": global_step,
                "latest_checkpoint": str(checkpoint.resolve()),
                "cutover_checkpoint": source["checkpoint"],
                "training_plan": plan,
                "last_eval": metrics["eval"],
                "database": store.stats(),
                "reserve": store.reserve_counts(),
                "meta_training": False,
                "meta_evaluation": False,
            }
            atomic_json(state_path, state)
            emit(
                "consensus_primary_only_curriculum_cycle",
                cycle=cycle,
                checkpoint=str(checkpoint),
                metrics=metrics,
            )


if __name__ == "__main__":
    main()
